// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.31.1
// source: identifier_type.proto

/* eslint-disable */

export const protobufPackage = "tesla.proto.energy.command.v1";

/**
 * TESLEMETRY SOURCE-OF-RECORD - no upstream.
 * Provenance: Tesla Energy gateway (TEG) local API, from our own
 * observations and contributions from the community
 */

export enum IdentifierType {
  IDENTIFIER_TYPE_INVALID = 0,
  IDENTIFIER_TYPE_GATEWAY_DIN = 1,
  IDENTIFIER_TYPE_SITE_UUID = 2,
  IDENTIFIER_TYPE_SOLAR_INVERTER_DIN = 3,
  IDENTIFIER_TYPE_WALL_CONNECTOR_DIN = 4,
  UNRECOGNIZED = -1,
}

export function identifierTypeFromJSON(object: any): IdentifierType {
  switch (object) {
    case 0:
    case "IDENTIFIER_TYPE_INVALID":
      return IdentifierType.IDENTIFIER_TYPE_INVALID;
    case 1:
    case "IDENTIFIER_TYPE_GATEWAY_DIN":
      return IdentifierType.IDENTIFIER_TYPE_GATEWAY_DIN;
    case 2:
    case "IDENTIFIER_TYPE_SITE_UUID":
      return IdentifierType.IDENTIFIER_TYPE_SITE_UUID;
    case 3:
    case "IDENTIFIER_TYPE_SOLAR_INVERTER_DIN":
      return IdentifierType.IDENTIFIER_TYPE_SOLAR_INVERTER_DIN;
    case 4:
    case "IDENTIFIER_TYPE_WALL_CONNECTOR_DIN":
      return IdentifierType.IDENTIFIER_TYPE_WALL_CONNECTOR_DIN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return IdentifierType.UNRECOGNIZED;
  }
}

export function identifierTypeToJSON(object: IdentifierType): string {
  switch (object) {
    case IdentifierType.IDENTIFIER_TYPE_INVALID:
      return "IDENTIFIER_TYPE_INVALID";
    case IdentifierType.IDENTIFIER_TYPE_GATEWAY_DIN:
      return "IDENTIFIER_TYPE_GATEWAY_DIN";
    case IdentifierType.IDENTIFIER_TYPE_SITE_UUID:
      return "IDENTIFIER_TYPE_SITE_UUID";
    case IdentifierType.IDENTIFIER_TYPE_SOLAR_INVERTER_DIN:
      return "IDENTIFIER_TYPE_SOLAR_INVERTER_DIN";
    case IdentifierType.IDENTIFIER_TYPE_WALL_CONNECTOR_DIN:
      return "IDENTIFIER_TYPE_WALL_CONNECTOR_DIN";
    case IdentifierType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
