// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.31.1
// source: vehicle_connectivity.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "./google/protobuf/timestamp.js";

export const protobufPackage = "telemetry.vehicle_connectivity";

/**
 * UPSTREAM-SOURCE: teslamotors/fleet-telemetry
 * UPSTREAM-PATH:   protos/vehicle_connectivity.proto
 * UPSTREAM-COMMIT: see upstream.json
 * This file tracks upstream verbatim; no Teslemetry extensions.
 */

/** ConnectivityEvent represents connection state of the vehicle */
export enum ConnectivityEvent {
  UNKNOWN = 0,
  CONNECTED = 1,
  DISCONNECTED = 2,
  UNRECOGNIZED = -1,
}

export function connectivityEventFromJSON(object: any): ConnectivityEvent {
  switch (object) {
    case 0:
    case "UNKNOWN":
      return ConnectivityEvent.UNKNOWN;
    case 1:
    case "CONNECTED":
      return ConnectivityEvent.CONNECTED;
    case 2:
    case "DISCONNECTED":
      return ConnectivityEvent.DISCONNECTED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ConnectivityEvent.UNRECOGNIZED;
  }
}

export function connectivityEventToJSON(object: ConnectivityEvent): string {
  switch (object) {
    case ConnectivityEvent.UNKNOWN:
      return "UNKNOWN";
    case ConnectivityEvent.CONNECTED:
      return "CONNECTED";
    case ConnectivityEvent.DISCONNECTED:
      return "DISCONNECTED";
    case ConnectivityEvent.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** VehicleConnectivity represents connection status change for the vehicle */
export interface VehicleConnectivity {
  vin: string;
  connectionId: string;
  status: ConnectivityEvent;
  createdAt: Date | undefined;
  networkInterface: string;
}

function createBaseVehicleConnectivity(): VehicleConnectivity {
  return { vin: "", connectionId: "", status: 0, createdAt: undefined, networkInterface: "" };
}

export const VehicleConnectivity: MessageFns<VehicleConnectivity> = {
  encode(message: VehicleConnectivity, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.vin !== "") {
      writer.uint32(10).string(message.vin);
    }
    if (message.connectionId !== "") {
      writer.uint32(18).string(message.connectionId);
    }
    if (message.status !== 0) {
      writer.uint32(24).int32(message.status);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(34).fork()).join();
    }
    if (message.networkInterface !== "") {
      writer.uint32(42).string(message.networkInterface);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VehicleConnectivity {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVehicleConnectivity();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.vin = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.connectionId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.networkInterface = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VehicleConnectivity {
    return {
      vin: isSet(object.vin) ? globalThis.String(object.vin) : "",
      connectionId: isSet(object.connectionId) ? globalThis.String(object.connectionId) : "",
      status: isSet(object.status) ? connectivityEventFromJSON(object.status) : 0,
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      networkInterface: isSet(object.networkInterface) ? globalThis.String(object.networkInterface) : "",
    };
  },

  toJSON(message: VehicleConnectivity): unknown {
    const obj: any = {};
    if (message.vin !== undefined) {
      obj.vin = message.vin;
    }
    if (message.connectionId !== undefined) {
      obj.connectionId = message.connectionId;
    }
    if (message.status !== undefined) {
      obj.status = connectivityEventToJSON(message.status);
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.networkInterface !== undefined) {
      obj.networkInterface = message.networkInterface;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VehicleConnectivity>, I>>(base?: I): VehicleConnectivity {
    return VehicleConnectivity.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VehicleConnectivity>, I>>(object: I): VehicleConnectivity {
    const message = createBaseVehicleConnectivity();
    message.vin = object.vin ?? "";
    message.connectionId = object.connectionId ?? "";
    message.status = object.status ?? 0;
    message.createdAt = object.createdAt ?? undefined;
    message.networkInterface = object.networkInterface ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
