// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.31.1
// source: charging.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.tesla.proto.charging.v1";

/**
 * Split integer energy representation: whole watt-hours plus a
 * sub-watt-hour remainder in milli-watt-hours.
 */
export interface Energy {
  wattHours: number;
  milliWattHours: number;
}

/** Identity and firmware of the metering device that recorded a charge session. */
export interface StemInfo {
  fwGithash: Uint8Array;
  serialNumber: string;
  partNumber: string;
  meterId: string;
}

/** Validity flags for a charge-session metering record. */
export interface StemEventInfo {
  eventOccurred: boolean;
  invalidated: boolean;
  timeSynchronized: boolean;
}

/** Bucketed energy vended (delivered) over a charge session. */
export interface ChargeSessionTimeSeries {
  startTimeEpochS: number;
  endTimeEpochS: number;
  totalEnergyVendedWh: number;
  bucketDurationS: number;
  firstBucketDurationS: number;
  bucketEnergyVendedWh: number[];
  totalEnergyVended: Energy | undefined;
  bucketEnergyVended: Energy[];
}

/** UI-facing summary of a live or recently completed charge session. */
export interface StemUi {
  stemInfo: StemInfo | undefined;
  sessionId: number;
  systemTimeEpochS: number;
  idleTimeS: number;
  startTimeEpochS: number;
  stemEventInfo: StemEventInfo | undefined;
  sessionEnergyKwh: number;
}

/** Billing record for a completed charge session. */
export interface StemBilling {
  stemInfo: StemInfo | undefined;
  sessionId: number;
  stemEventInfo: StemEventInfo | undefined;
  lifetimeEnergyStartKwh: number;
  lifetimeEnergyEndKwh: number;
  idleTimeS: number;
  chargeSessionTimeSeries: ChargeSessionTimeSeries | undefined;
}

function createBaseEnergy(): Energy {
  return { wattHours: 0, milliWattHours: 0 };
}

export const Energy: MessageFns<Energy> = {
  encode(message: Energy, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.wattHours !== 0) {
      writer.uint32(8).uint32(message.wattHours);
    }
    if (message.milliWattHours !== 0) {
      writer.uint32(16).uint32(message.milliWattHours);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Energy {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEnergy();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.wattHours = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.milliWattHours = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Energy {
    return {
      wattHours: isSet(object.wattHours) ? globalThis.Number(object.wattHours) : 0,
      milliWattHours: isSet(object.milliWattHours) ? globalThis.Number(object.milliWattHours) : 0,
    };
  },

  toJSON(message: Energy): unknown {
    const obj: any = {};
    if (message.wattHours !== undefined) {
      obj.wattHours = Math.round(message.wattHours);
    }
    if (message.milliWattHours !== undefined) {
      obj.milliWattHours = Math.round(message.milliWattHours);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Energy>, I>>(base?: I): Energy {
    return Energy.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Energy>, I>>(object: I): Energy {
    const message = createBaseEnergy();
    message.wattHours = object.wattHours ?? 0;
    message.milliWattHours = object.milliWattHours ?? 0;
    return message;
  },
};

function createBaseStemInfo(): StemInfo {
  return { fwGithash: new Uint8Array(0), serialNumber: "", partNumber: "", meterId: "" };
}

export const StemInfo: MessageFns<StemInfo> = {
  encode(message: StemInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fwGithash.length !== 0) {
      writer.uint32(10).bytes(message.fwGithash);
    }
    if (message.serialNumber !== "") {
      writer.uint32(18).string(message.serialNumber);
    }
    if (message.partNumber !== "") {
      writer.uint32(26).string(message.partNumber);
    }
    if (message.meterId !== "") {
      writer.uint32(34).string(message.meterId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StemInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStemInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fwGithash = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.serialNumber = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.partNumber = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.meterId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StemInfo {
    return {
      fwGithash: isSet(object.fwGithash) ? bytesFromBase64(object.fwGithash) : new Uint8Array(0),
      serialNumber: isSet(object.serialNumber) ? globalThis.String(object.serialNumber) : "",
      partNumber: isSet(object.partNumber) ? globalThis.String(object.partNumber) : "",
      meterId: isSet(object.meterId) ? globalThis.String(object.meterId) : "",
    };
  },

  toJSON(message: StemInfo): unknown {
    const obj: any = {};
    if (message.fwGithash !== undefined) {
      obj.fwGithash = base64FromBytes(message.fwGithash);
    }
    if (message.serialNumber !== undefined) {
      obj.serialNumber = message.serialNumber;
    }
    if (message.partNumber !== undefined) {
      obj.partNumber = message.partNumber;
    }
    if (message.meterId !== undefined) {
      obj.meterId = message.meterId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StemInfo>, I>>(base?: I): StemInfo {
    return StemInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StemInfo>, I>>(object: I): StemInfo {
    const message = createBaseStemInfo();
    message.fwGithash = object.fwGithash ?? new Uint8Array(0);
    message.serialNumber = object.serialNumber ?? "";
    message.partNumber = object.partNumber ?? "";
    message.meterId = object.meterId ?? "";
    return message;
  },
};

function createBaseStemEventInfo(): StemEventInfo {
  return { eventOccurred: false, invalidated: false, timeSynchronized: false };
}

export const StemEventInfo: MessageFns<StemEventInfo> = {
  encode(message: StemEventInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventOccurred !== false) {
      writer.uint32(8).bool(message.eventOccurred);
    }
    if (message.invalidated !== false) {
      writer.uint32(16).bool(message.invalidated);
    }
    if (message.timeSynchronized !== false) {
      writer.uint32(24).bool(message.timeSynchronized);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StemEventInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStemEventInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.eventOccurred = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.invalidated = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timeSynchronized = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StemEventInfo {
    return {
      eventOccurred: isSet(object.eventOccurred) ? globalThis.Boolean(object.eventOccurred) : false,
      invalidated: isSet(object.invalidated) ? globalThis.Boolean(object.invalidated) : false,
      timeSynchronized: isSet(object.timeSynchronized) ? globalThis.Boolean(object.timeSynchronized) : false,
    };
  },

  toJSON(message: StemEventInfo): unknown {
    const obj: any = {};
    if (message.eventOccurred !== undefined) {
      obj.eventOccurred = message.eventOccurred;
    }
    if (message.invalidated !== undefined) {
      obj.invalidated = message.invalidated;
    }
    if (message.timeSynchronized !== undefined) {
      obj.timeSynchronized = message.timeSynchronized;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StemEventInfo>, I>>(base?: I): StemEventInfo {
    return StemEventInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StemEventInfo>, I>>(object: I): StemEventInfo {
    const message = createBaseStemEventInfo();
    message.eventOccurred = object.eventOccurred ?? false;
    message.invalidated = object.invalidated ?? false;
    message.timeSynchronized = object.timeSynchronized ?? false;
    return message;
  },
};

function createBaseChargeSessionTimeSeries(): ChargeSessionTimeSeries {
  return {
    startTimeEpochS: 0,
    endTimeEpochS: 0,
    totalEnergyVendedWh: 0,
    bucketDurationS: 0,
    firstBucketDurationS: 0,
    bucketEnergyVendedWh: [],
    totalEnergyVended: undefined,
    bucketEnergyVended: [],
  };
}

export const ChargeSessionTimeSeries: MessageFns<ChargeSessionTimeSeries> = {
  encode(message: ChargeSessionTimeSeries, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.startTimeEpochS !== 0) {
      writer.uint32(8).uint64(message.startTimeEpochS);
    }
    if (message.endTimeEpochS !== 0) {
      writer.uint32(16).uint64(message.endTimeEpochS);
    }
    if (message.totalEnergyVendedWh !== 0) {
      writer.uint32(24).uint32(message.totalEnergyVendedWh);
    }
    if (message.bucketDurationS !== 0) {
      writer.uint32(32).uint32(message.bucketDurationS);
    }
    if (message.firstBucketDurationS !== 0) {
      writer.uint32(40).uint32(message.firstBucketDurationS);
    }
    writer.uint32(50).fork();
    for (const v of message.bucketEnergyVendedWh) {
      writer.uint32(v);
    }
    writer.join();
    if (message.totalEnergyVended !== undefined) {
      Energy.encode(message.totalEnergyVended, writer.uint32(58).fork()).join();
    }
    for (const v of message.bucketEnergyVended) {
      Energy.encode(v!, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChargeSessionTimeSeries {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChargeSessionTimeSeries();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.startTimeEpochS = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.endTimeEpochS = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalEnergyVendedWh = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.bucketDurationS = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.firstBucketDurationS = reader.uint32();
          continue;
        }
        case 6: {
          if (tag === 48) {
            message.bucketEnergyVendedWh.push(reader.uint32());

            continue;
          }

          if (tag === 50) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.bucketEnergyVendedWh.push(reader.uint32());
            }

            continue;
          }

          break;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.totalEnergyVended = Energy.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.bucketEnergyVended.push(Energy.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChargeSessionTimeSeries {
    return {
      startTimeEpochS: isSet(object.startTimeEpochS) ? globalThis.Number(object.startTimeEpochS) : 0,
      endTimeEpochS: isSet(object.endTimeEpochS) ? globalThis.Number(object.endTimeEpochS) : 0,
      totalEnergyVendedWh: isSet(object.totalEnergyVendedWh) ? globalThis.Number(object.totalEnergyVendedWh) : 0,
      bucketDurationS: isSet(object.bucketDurationS) ? globalThis.Number(object.bucketDurationS) : 0,
      firstBucketDurationS: isSet(object.firstBucketDurationS) ? globalThis.Number(object.firstBucketDurationS) : 0,
      bucketEnergyVendedWh: globalThis.Array.isArray(object?.bucketEnergyVendedWh)
        ? object.bucketEnergyVendedWh.map((e: any) => globalThis.Number(e))
        : [],
      totalEnergyVended: isSet(object.totalEnergyVended) ? Energy.fromJSON(object.totalEnergyVended) : undefined,
      bucketEnergyVended: globalThis.Array.isArray(object?.bucketEnergyVended)
        ? object.bucketEnergyVended.map((e: any) => Energy.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ChargeSessionTimeSeries): unknown {
    const obj: any = {};
    if (message.startTimeEpochS !== undefined) {
      obj.startTimeEpochS = Math.round(message.startTimeEpochS);
    }
    if (message.endTimeEpochS !== undefined) {
      obj.endTimeEpochS = Math.round(message.endTimeEpochS);
    }
    if (message.totalEnergyVendedWh !== undefined) {
      obj.totalEnergyVendedWh = Math.round(message.totalEnergyVendedWh);
    }
    if (message.bucketDurationS !== undefined) {
      obj.bucketDurationS = Math.round(message.bucketDurationS);
    }
    if (message.firstBucketDurationS !== undefined) {
      obj.firstBucketDurationS = Math.round(message.firstBucketDurationS);
    }
    if (message.bucketEnergyVendedWh?.length) {
      obj.bucketEnergyVendedWh = message.bucketEnergyVendedWh.map((e) => Math.round(e));
    }
    if (message.totalEnergyVended !== undefined) {
      obj.totalEnergyVended = Energy.toJSON(message.totalEnergyVended);
    }
    if (message.bucketEnergyVended?.length) {
      obj.bucketEnergyVended = message.bucketEnergyVended.map((e) => Energy.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChargeSessionTimeSeries>, I>>(base?: I): ChargeSessionTimeSeries {
    return ChargeSessionTimeSeries.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChargeSessionTimeSeries>, I>>(object: I): ChargeSessionTimeSeries {
    const message = createBaseChargeSessionTimeSeries();
    message.startTimeEpochS = object.startTimeEpochS ?? 0;
    message.endTimeEpochS = object.endTimeEpochS ?? 0;
    message.totalEnergyVendedWh = object.totalEnergyVendedWh ?? 0;
    message.bucketDurationS = object.bucketDurationS ?? 0;
    message.firstBucketDurationS = object.firstBucketDurationS ?? 0;
    message.bucketEnergyVendedWh = object.bucketEnergyVendedWh?.map((e) => e) || [];
    message.totalEnergyVended = (object.totalEnergyVended !== undefined && object.totalEnergyVended !== null)
      ? Energy.fromPartial(object.totalEnergyVended)
      : undefined;
    message.bucketEnergyVended = object.bucketEnergyVended?.map((e) => Energy.fromPartial(e)) || [];
    return message;
  },
};

function createBaseStemUi(): StemUi {
  return {
    stemInfo: undefined,
    sessionId: 0,
    systemTimeEpochS: 0,
    idleTimeS: 0,
    startTimeEpochS: 0,
    stemEventInfo: undefined,
    sessionEnergyKwh: 0,
  };
}

export const StemUi: MessageFns<StemUi> = {
  encode(message: StemUi, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stemInfo !== undefined) {
      StemInfo.encode(message.stemInfo, writer.uint32(10).fork()).join();
    }
    if (message.sessionId !== 0) {
      writer.uint32(16).uint32(message.sessionId);
    }
    if (message.systemTimeEpochS !== 0) {
      writer.uint32(24).uint64(message.systemTimeEpochS);
    }
    if (message.idleTimeS !== 0) {
      writer.uint32(32).uint32(message.idleTimeS);
    }
    if (message.startTimeEpochS !== 0) {
      writer.uint32(40).uint64(message.startTimeEpochS);
    }
    if (message.stemEventInfo !== undefined) {
      StemEventInfo.encode(message.stemEventInfo, writer.uint32(50).fork()).join();
    }
    if (message.sessionEnergyKwh !== 0) {
      writer.uint32(61).float(message.sessionEnergyKwh);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StemUi {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStemUi();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stemInfo = StemInfo.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sessionId = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.systemTimeEpochS = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.idleTimeS = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.startTimeEpochS = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.stemEventInfo = StemEventInfo.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 61) {
            break;
          }

          message.sessionEnergyKwh = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StemUi {
    return {
      stemInfo: isSet(object.stemInfo) ? StemInfo.fromJSON(object.stemInfo) : undefined,
      sessionId: isSet(object.sessionId) ? globalThis.Number(object.sessionId) : 0,
      systemTimeEpochS: isSet(object.systemTimeEpochS) ? globalThis.Number(object.systemTimeEpochS) : 0,
      idleTimeS: isSet(object.idleTimeS) ? globalThis.Number(object.idleTimeS) : 0,
      startTimeEpochS: isSet(object.startTimeEpochS) ? globalThis.Number(object.startTimeEpochS) : 0,
      stemEventInfo: isSet(object.stemEventInfo) ? StemEventInfo.fromJSON(object.stemEventInfo) : undefined,
      sessionEnergyKwh: isSet(object.sessionEnergyKwh) ? globalThis.Number(object.sessionEnergyKwh) : 0,
    };
  },

  toJSON(message: StemUi): unknown {
    const obj: any = {};
    if (message.stemInfo !== undefined) {
      obj.stemInfo = StemInfo.toJSON(message.stemInfo);
    }
    if (message.sessionId !== undefined) {
      obj.sessionId = Math.round(message.sessionId);
    }
    if (message.systemTimeEpochS !== undefined) {
      obj.systemTimeEpochS = Math.round(message.systemTimeEpochS);
    }
    if (message.idleTimeS !== undefined) {
      obj.idleTimeS = Math.round(message.idleTimeS);
    }
    if (message.startTimeEpochS !== undefined) {
      obj.startTimeEpochS = Math.round(message.startTimeEpochS);
    }
    if (message.stemEventInfo !== undefined) {
      obj.stemEventInfo = StemEventInfo.toJSON(message.stemEventInfo);
    }
    if (message.sessionEnergyKwh !== undefined) {
      obj.sessionEnergyKwh = message.sessionEnergyKwh;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StemUi>, I>>(base?: I): StemUi {
    return StemUi.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StemUi>, I>>(object: I): StemUi {
    const message = createBaseStemUi();
    message.stemInfo = (object.stemInfo !== undefined && object.stemInfo !== null)
      ? StemInfo.fromPartial(object.stemInfo)
      : undefined;
    message.sessionId = object.sessionId ?? 0;
    message.systemTimeEpochS = object.systemTimeEpochS ?? 0;
    message.idleTimeS = object.idleTimeS ?? 0;
    message.startTimeEpochS = object.startTimeEpochS ?? 0;
    message.stemEventInfo = (object.stemEventInfo !== undefined && object.stemEventInfo !== null)
      ? StemEventInfo.fromPartial(object.stemEventInfo)
      : undefined;
    message.sessionEnergyKwh = object.sessionEnergyKwh ?? 0;
    return message;
  },
};

function createBaseStemBilling(): StemBilling {
  return {
    stemInfo: undefined,
    sessionId: 0,
    stemEventInfo: undefined,
    lifetimeEnergyStartKwh: 0,
    lifetimeEnergyEndKwh: 0,
    idleTimeS: 0,
    chargeSessionTimeSeries: undefined,
  };
}

export const StemBilling: MessageFns<StemBilling> = {
  encode(message: StemBilling, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stemInfo !== undefined) {
      StemInfo.encode(message.stemInfo, writer.uint32(10).fork()).join();
    }
    if (message.sessionId !== 0) {
      writer.uint32(16).uint32(message.sessionId);
    }
    if (message.stemEventInfo !== undefined) {
      StemEventInfo.encode(message.stemEventInfo, writer.uint32(26).fork()).join();
    }
    if (message.lifetimeEnergyStartKwh !== 0) {
      writer.uint32(37).float(message.lifetimeEnergyStartKwh);
    }
    if (message.lifetimeEnergyEndKwh !== 0) {
      writer.uint32(45).float(message.lifetimeEnergyEndKwh);
    }
    if (message.idleTimeS !== 0) {
      writer.uint32(48).uint32(message.idleTimeS);
    }
    if (message.chargeSessionTimeSeries !== undefined) {
      ChargeSessionTimeSeries.encode(message.chargeSessionTimeSeries, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StemBilling {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStemBilling();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stemInfo = StemInfo.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sessionId = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.stemEventInfo = StemEventInfo.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.lifetimeEnergyStartKwh = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.lifetimeEnergyEndKwh = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.idleTimeS = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.chargeSessionTimeSeries = ChargeSessionTimeSeries.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StemBilling {
    return {
      stemInfo: isSet(object.stemInfo) ? StemInfo.fromJSON(object.stemInfo) : undefined,
      sessionId: isSet(object.sessionId) ? globalThis.Number(object.sessionId) : 0,
      stemEventInfo: isSet(object.stemEventInfo) ? StemEventInfo.fromJSON(object.stemEventInfo) : undefined,
      lifetimeEnergyStartKwh: isSet(object.lifetimeEnergyStartKwh)
        ? globalThis.Number(object.lifetimeEnergyStartKwh)
        : 0,
      lifetimeEnergyEndKwh: isSet(object.lifetimeEnergyEndKwh) ? globalThis.Number(object.lifetimeEnergyEndKwh) : 0,
      idleTimeS: isSet(object.idleTimeS) ? globalThis.Number(object.idleTimeS) : 0,
      chargeSessionTimeSeries: isSet(object.chargeSessionTimeSeries)
        ? ChargeSessionTimeSeries.fromJSON(object.chargeSessionTimeSeries)
        : undefined,
    };
  },

  toJSON(message: StemBilling): unknown {
    const obj: any = {};
    if (message.stemInfo !== undefined) {
      obj.stemInfo = StemInfo.toJSON(message.stemInfo);
    }
    if (message.sessionId !== undefined) {
      obj.sessionId = Math.round(message.sessionId);
    }
    if (message.stemEventInfo !== undefined) {
      obj.stemEventInfo = StemEventInfo.toJSON(message.stemEventInfo);
    }
    if (message.lifetimeEnergyStartKwh !== undefined) {
      obj.lifetimeEnergyStartKwh = message.lifetimeEnergyStartKwh;
    }
    if (message.lifetimeEnergyEndKwh !== undefined) {
      obj.lifetimeEnergyEndKwh = message.lifetimeEnergyEndKwh;
    }
    if (message.idleTimeS !== undefined) {
      obj.idleTimeS = Math.round(message.idleTimeS);
    }
    if (message.chargeSessionTimeSeries !== undefined) {
      obj.chargeSessionTimeSeries = ChargeSessionTimeSeries.toJSON(message.chargeSessionTimeSeries);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StemBilling>, I>>(base?: I): StemBilling {
    return StemBilling.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StemBilling>, I>>(object: I): StemBilling {
    const message = createBaseStemBilling();
    message.stemInfo = (object.stemInfo !== undefined && object.stemInfo !== null)
      ? StemInfo.fromPartial(object.stemInfo)
      : undefined;
    message.sessionId = object.sessionId ?? 0;
    message.stemEventInfo = (object.stemEventInfo !== undefined && object.stemEventInfo !== null)
      ? StemEventInfo.fromPartial(object.stemEventInfo)
      : undefined;
    message.lifetimeEnergyStartKwh = object.lifetimeEnergyStartKwh ?? 0;
    message.lifetimeEnergyEndKwh = object.lifetimeEnergyEndKwh ?? 0;
    message.idleTimeS = object.idleTimeS ?? 0;
    message.chargeSessionTimeSeries =
      (object.chargeSessionTimeSeries !== undefined && object.chargeSessionTimeSeries !== null)
        ? ChargeSessionTimeSeries.fromPartial(object.chargeSessionTimeSeries)
        : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
