// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.31.1
// source: common.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "CarServer";

/**
 * UPSTREAM-SOURCE: teslamotors/vehicle-command
 * UPSTREAM-PATH:   pkg/protocol/protobuf/common.proto
 * UPSTREAM-COMMIT: see upstream.json
 * This file = upstream base + Teslemetry extensions marked TESLEMETRY-EXT.
 */

export enum Invalid {
  INVALID = 0,
  UNRECOGNIZED = -1,
}

export function invalidFromJSON(object: any): Invalid {
  switch (object) {
    case 0:
    case "INVALID":
      return Invalid.INVALID;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Invalid.UNRECOGNIZED;
  }
}

export function invalidToJSON(object: Invalid): string {
  switch (object) {
    case Invalid.INVALID:
      return "INVALID";
    case Invalid.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum MediaPlaybackStatus {
  Stopped = 0,
  Playing = 1,
  Paused = 2,
  UNRECOGNIZED = -1,
}

export function mediaPlaybackStatusFromJSON(object: any): MediaPlaybackStatus {
  switch (object) {
    case 0:
    case "Stopped":
      return MediaPlaybackStatus.Stopped;
    case 1:
    case "Playing":
      return MediaPlaybackStatus.Playing;
    case 2:
    case "Paused":
      return MediaPlaybackStatus.Paused;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MediaPlaybackStatus.UNRECOGNIZED;
  }
}

export function mediaPlaybackStatusToJSON(object: MediaPlaybackStatus): string {
  switch (object) {
    case MediaPlaybackStatus.Stopped:
      return "Stopped";
    case MediaPlaybackStatus.Playing:
      return "Playing";
    case MediaPlaybackStatus.Paused:
      return "Paused";
    case MediaPlaybackStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum StwHeatLevel {
  StwHeatLevel_Unknown = 0,
  StwHeatLevel_Off = 1,
  StwHeatLevel_Low = 2,
  StwHeatLevel_High = 3,
  UNRECOGNIZED = -1,
}

export function stwHeatLevelFromJSON(object: any): StwHeatLevel {
  switch (object) {
    case 0:
    case "StwHeatLevel_Unknown":
      return StwHeatLevel.StwHeatLevel_Unknown;
    case 1:
    case "StwHeatLevel_Off":
      return StwHeatLevel.StwHeatLevel_Off;
    case 2:
    case "StwHeatLevel_Low":
      return StwHeatLevel.StwHeatLevel_Low;
    case 3:
    case "StwHeatLevel_High":
      return StwHeatLevel.StwHeatLevel_High;
    case -1:
    case "UNRECOGNIZED":
    default:
      return StwHeatLevel.UNRECOGNIZED;
  }
}

export function stwHeatLevelToJSON(object: StwHeatLevel): string {
  switch (object) {
    case StwHeatLevel.StwHeatLevel_Unknown:
      return "StwHeatLevel_Unknown";
    case StwHeatLevel.StwHeatLevel_Off:
      return "StwHeatLevel_Off";
    case StwHeatLevel.StwHeatLevel_Low:
      return "StwHeatLevel_Low";
    case StwHeatLevel.StwHeatLevel_High:
      return "StwHeatLevel_High";
    case StwHeatLevel.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ChargingAlertType {
  INVALID_ALERT_TYPE = 0,
  WARNING = 1,
  NOTIFICATION = 2,
  UNRECOGNIZED = -1,
}

export function chargingAlertTypeFromJSON(object: any): ChargingAlertType {
  switch (object) {
    case 0:
    case "INVALID_ALERT_TYPE":
      return ChargingAlertType.INVALID_ALERT_TYPE;
    case 1:
    case "WARNING":
      return ChargingAlertType.WARNING;
    case 2:
    case "NOTIFICATION":
      return ChargingAlertType.NOTIFICATION;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ChargingAlertType.UNRECOGNIZED;
  }
}

export function chargingAlertTypeToJSON(object: ChargingAlertType): string {
  switch (object) {
    case ChargingAlertType.INVALID_ALERT_TYPE:
      return "INVALID_ALERT_TYPE";
    case ChargingAlertType.WARNING:
      return "WARNING";
    case ChargingAlertType.NOTIFICATION:
      return "NOTIFICATION";
    case ChargingAlertType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ChargingAlertName {
  INVALID_ALERT_NAME = 0,
  BMS_a007_SW_Slowed_Chg_Batt_Cold_OBSOLETE = 1,
  BMS_a076_SW_Dch_While_Charging = 2,
  CC_a001_gndMonIntrptLineSide = 3,
  CC_a002_gndMonIntrptLoadSide = 4,
  CC_a003_CCIDTripped = 5,
  CC_a004_CCIDSelfTestFault = 6,
  CC_a005_groundedNeutral = 7,
  CC_a006_inputOverCurrent = 8,
  CC_a007_inputOverVoltage = 9,
  CC_a008_inputUnderVoltage = 10,
  CC_a009_inputMiswired = 11,
  CC_a010_contactorWelded = 12,
  CC_a011_ambientOT = 13,
  CC_a012_wallPlugOT = 14,
  CC_a013_vehConnOT = 15,
  CC_a014_mcuSelfTestFault = 16,
  CC_a015_PilotAFault = 17,
  CC_a016_PilotBFault = 18,
  CC_a017_PilotCFault = 19,
  CC_a018_PilotDFault = 20,
  CC_a019_proxDisconnected = 21,
  CC_a020_3vRailIncorrect = 22,
  CC_a021_CB_noMaster = 23,
  CC_a022_CB_tooManyMasters = 24,
  CC_a023_CB_tooManySlaves = 25,
  CC_a024_CB_masterISetTooLow = 26,
  CC_a025_evseTemp = 27,
  CC_a026_wallPlugTemp = 28,
  CC_a027_vehicleHandleTemp = 29,
  CC_a028_CB_rotarySelect = 30,
  CC_a029_PilotFFault = 31,
  CC_a030_masterSlaveMismatch = 32,
  CC_a041_inputWiringFoldback = 33,
  CC_a042_pcbaTempFoldback = 34,
  CC_a043_configurationRequired = 35,
  CP_a004_proximityRationality = 36,
  CP_a010_pilotRationality = 37,
  CP_a046_lostCommsEVSE = 38,
  CP_a049_multipleCablesDetected = 39,
  CP_a052_chademoNotSupported = 40,
  CP_a053_proxLatchedNoPilot = 41,
  CP_a055_chargeStoppedNoPilot = 42,
  CP_a058_acChargingBlocked = 43,
  CP_a062_scOutOfService = 44,
  CP_a063_scUpdateInProgress = 45,
  CP_a064_superchargingBlocked = 46,
  CP_a066_proxLatchedIdlePilot = 47,
  CP_a067_gbdcConnFault = 48,
  CP_a074_failedToEstablishV2gComm = 49,
  CP_a091_wrongSuperchargerHandle = 50,
  CP_a101_wcFoldbackActive = 51,
  CP_a102_wcOvertempFault = 52,
  CP_a108_chademoOvertempFault = 53,
  CP_a110_thermalVelocityHigh = 54,
  CP_a120_comboAdapterFoldback = 55,
  CP_a131_evseCommTimeout = 56,
  CP_a132_contractAuthTimeout = 57,
  CP_a133_proxNeverLatched = 58,
  CP_a135_sdpAttemptsFailed = 59,
  CP_a139_pilotFaulted = 60,
  CP_a140_superchargerFaulted = 61,
  CP_a141_chademoAdapterFault = 62,
  CP_a142_gbdcScConnFault = 63,
  CP_a143_unsupportedChargeAdapter = 64,
  CP_a146_ccsEvseMalfunction = 65,
  CP_a151_badPilotDiodeDetected = 66,
  CP_a152_pilotEdgeDetectionFailed = 67,
  FC_a141_CA_vehConn_OT = 68,
  FC_a142_CA_evseConn_OT = 69,
  FC_a143_CA_pcb_OT = 70,
  FC_a151_CA_vehToEvseDeltaLo = 71,
  FC_a154_CA_vehToPcbDeltaLo = 72,
  FC_a161_CA_vehTempHiFoldBk = 73,
  FC_a162_CA_evseTempHiFoldBk = 74,
  FC_a163_CA_pcbTempHiFoldBk = 75,
  FC_a266_GB_negPin_OT = 76,
  FC_a267_GB_posPin_OT = 77,
  FC_a268_GB_pcb_OT = 78,
  FC_a272_GB_negToPosDeltaHi = 79,
  FC_a273_GB_negToPosDeltaLo = 80,
  FC_a274_GB_negToPcbDeltaHi = 81,
  FC_a282_GB_negTempHiFoldBk = 82,
  FC_a283_GB_posTempHiFoldBk = 83,
  FC_a284_GB_pcbTempHiFoldBk = 84,
  FC_a286_GB_evseConnUnlocked = 85,
  PCS_a007_chgPhaseTempHot = 86,
  PCS_a016_chgAllPhasesFaulted = 87,
  PCS_a017_chgWallPowerRemoval = 88,
  PCS_a019_acChargePowerLimited = 89,
  PCS_a032_excessiveGridTransientsDetected = 90,
  PCS_a052_acVoltageNotPresent = 91,
  PCS_a053_chgInputVDropHigh = 92,
  PCS_a054_chgInputVDropTooHigh = 93,
  PCS_a055_chgLineImpedanceHigh = 94,
  PCS_a056_chgLineImpedanceTooHigh = 95,
  PCS_a059_chgInputOvRms = 96,
  PCS_a073_unexpectedAcInputVoltage = 97,
  PCS_a078_chgStopDcdcTooHot = 98,
  PCS_a088_gridFreqDroopDetected = 99,
  PCS_a090_expectedAcVoltageSourceMissing = 100,
  PCS_a096_microGridOverLoaded = 101,
  PCS2_a019_DcacADcTempTooHigh = 102,
  PCS2_a020_DcacBDcTempTooHigh = 103,
  PCS2_a024_DcacATxTempTooHigh = 104,
  PCS2_a025_DcacBTxTempTooHigh = 105,
  PCS2_a062_acVoltageNotPresent = 106,
  PCS2_a063_chgUnknownGridConfig = 107,
  PCS2_a112_chgInputVDropTooHigh = 108,
  PCS2_a115_chgWallPowerRemoval = 109,
  PCS2_a116_chgPersistentFault = 110,
  UMC_a001_gndMonIntrptLineSide = 111,
  UMC_a002_GFCITripped = 112,
  UMC_a003_GFCISelfTestFault = 113,
  UMC_a004_inputOverVoltage = 114,
  UMC_a005_inputUnderVoltage = 115,
  UMC_a006_contactorWelded = 116,
  UMC_a007_pcbaOT = 117,
  UMC_a008_wallPlugOT = 118,
  UMC_a009_vehConnOT = 119,
  UMC_a010_inputOT = 120,
  UMC_a011_proxDisconnected = 121,
  UMC_a012_pilotFault = 122,
  UMC_a013_SA_Temperature = 123,
  UMC_a014_SA_Genealogy = 124,
  UMC_a015_SA_Connection = 125,
  UMC_a016_pcbaOTFoldback = 126,
  UMC_a017_wallPlugOTFoldback = 127,
  UMC_a018_vehConnOTFoldback = 128,
  UMC_a019_inputOTFoldback = 129,
  UNRECOGNIZED = -1,
}

export function chargingAlertNameFromJSON(object: any): ChargingAlertName {
  switch (object) {
    case 0:
    case "INVALID_ALERT_NAME":
      return ChargingAlertName.INVALID_ALERT_NAME;
    case 1:
    case "BMS_a007_SW_Slowed_Chg_Batt_Cold_OBSOLETE":
      return ChargingAlertName.BMS_a007_SW_Slowed_Chg_Batt_Cold_OBSOLETE;
    case 2:
    case "BMS_a076_SW_Dch_While_Charging":
      return ChargingAlertName.BMS_a076_SW_Dch_While_Charging;
    case 3:
    case "CC_a001_gndMonIntrptLineSide":
      return ChargingAlertName.CC_a001_gndMonIntrptLineSide;
    case 4:
    case "CC_a002_gndMonIntrptLoadSide":
      return ChargingAlertName.CC_a002_gndMonIntrptLoadSide;
    case 5:
    case "CC_a003_CCIDTripped":
      return ChargingAlertName.CC_a003_CCIDTripped;
    case 6:
    case "CC_a004_CCIDSelfTestFault":
      return ChargingAlertName.CC_a004_CCIDSelfTestFault;
    case 7:
    case "CC_a005_groundedNeutral":
      return ChargingAlertName.CC_a005_groundedNeutral;
    case 8:
    case "CC_a006_inputOverCurrent":
      return ChargingAlertName.CC_a006_inputOverCurrent;
    case 9:
    case "CC_a007_inputOverVoltage":
      return ChargingAlertName.CC_a007_inputOverVoltage;
    case 10:
    case "CC_a008_inputUnderVoltage":
      return ChargingAlertName.CC_a008_inputUnderVoltage;
    case 11:
    case "CC_a009_inputMiswired":
      return ChargingAlertName.CC_a009_inputMiswired;
    case 12:
    case "CC_a010_contactorWelded":
      return ChargingAlertName.CC_a010_contactorWelded;
    case 13:
    case "CC_a011_ambientOT":
      return ChargingAlertName.CC_a011_ambientOT;
    case 14:
    case "CC_a012_wallPlugOT":
      return ChargingAlertName.CC_a012_wallPlugOT;
    case 15:
    case "CC_a013_vehConnOT":
      return ChargingAlertName.CC_a013_vehConnOT;
    case 16:
    case "CC_a014_mcuSelfTestFault":
      return ChargingAlertName.CC_a014_mcuSelfTestFault;
    case 17:
    case "CC_a015_PilotAFault":
      return ChargingAlertName.CC_a015_PilotAFault;
    case 18:
    case "CC_a016_PilotBFault":
      return ChargingAlertName.CC_a016_PilotBFault;
    case 19:
    case "CC_a017_PilotCFault":
      return ChargingAlertName.CC_a017_PilotCFault;
    case 20:
    case "CC_a018_PilotDFault":
      return ChargingAlertName.CC_a018_PilotDFault;
    case 21:
    case "CC_a019_proxDisconnected":
      return ChargingAlertName.CC_a019_proxDisconnected;
    case 22:
    case "CC_a020_3vRailIncorrect":
      return ChargingAlertName.CC_a020_3vRailIncorrect;
    case 23:
    case "CC_a021_CB_noMaster":
      return ChargingAlertName.CC_a021_CB_noMaster;
    case 24:
    case "CC_a022_CB_tooManyMasters":
      return ChargingAlertName.CC_a022_CB_tooManyMasters;
    case 25:
    case "CC_a023_CB_tooManySlaves":
      return ChargingAlertName.CC_a023_CB_tooManySlaves;
    case 26:
    case "CC_a024_CB_masterISetTooLow":
      return ChargingAlertName.CC_a024_CB_masterISetTooLow;
    case 27:
    case "CC_a025_evseTemp":
      return ChargingAlertName.CC_a025_evseTemp;
    case 28:
    case "CC_a026_wallPlugTemp":
      return ChargingAlertName.CC_a026_wallPlugTemp;
    case 29:
    case "CC_a027_vehicleHandleTemp":
      return ChargingAlertName.CC_a027_vehicleHandleTemp;
    case 30:
    case "CC_a028_CB_rotarySelect":
      return ChargingAlertName.CC_a028_CB_rotarySelect;
    case 31:
    case "CC_a029_PilotFFault":
      return ChargingAlertName.CC_a029_PilotFFault;
    case 32:
    case "CC_a030_masterSlaveMismatch":
      return ChargingAlertName.CC_a030_masterSlaveMismatch;
    case 33:
    case "CC_a041_inputWiringFoldback":
      return ChargingAlertName.CC_a041_inputWiringFoldback;
    case 34:
    case "CC_a042_pcbaTempFoldback":
      return ChargingAlertName.CC_a042_pcbaTempFoldback;
    case 35:
    case "CC_a043_configurationRequired":
      return ChargingAlertName.CC_a043_configurationRequired;
    case 36:
    case "CP_a004_proximityRationality":
      return ChargingAlertName.CP_a004_proximityRationality;
    case 37:
    case "CP_a010_pilotRationality":
      return ChargingAlertName.CP_a010_pilotRationality;
    case 38:
    case "CP_a046_lostCommsEVSE":
      return ChargingAlertName.CP_a046_lostCommsEVSE;
    case 39:
    case "CP_a049_multipleCablesDetected":
      return ChargingAlertName.CP_a049_multipleCablesDetected;
    case 40:
    case "CP_a052_chademoNotSupported":
      return ChargingAlertName.CP_a052_chademoNotSupported;
    case 41:
    case "CP_a053_proxLatchedNoPilot":
      return ChargingAlertName.CP_a053_proxLatchedNoPilot;
    case 42:
    case "CP_a055_chargeStoppedNoPilot":
      return ChargingAlertName.CP_a055_chargeStoppedNoPilot;
    case 43:
    case "CP_a058_acChargingBlocked":
      return ChargingAlertName.CP_a058_acChargingBlocked;
    case 44:
    case "CP_a062_scOutOfService":
      return ChargingAlertName.CP_a062_scOutOfService;
    case 45:
    case "CP_a063_scUpdateInProgress":
      return ChargingAlertName.CP_a063_scUpdateInProgress;
    case 46:
    case "CP_a064_superchargingBlocked":
      return ChargingAlertName.CP_a064_superchargingBlocked;
    case 47:
    case "CP_a066_proxLatchedIdlePilot":
      return ChargingAlertName.CP_a066_proxLatchedIdlePilot;
    case 48:
    case "CP_a067_gbdcConnFault":
      return ChargingAlertName.CP_a067_gbdcConnFault;
    case 49:
    case "CP_a074_failedToEstablishV2gComm":
      return ChargingAlertName.CP_a074_failedToEstablishV2gComm;
    case 50:
    case "CP_a091_wrongSuperchargerHandle":
      return ChargingAlertName.CP_a091_wrongSuperchargerHandle;
    case 51:
    case "CP_a101_wcFoldbackActive":
      return ChargingAlertName.CP_a101_wcFoldbackActive;
    case 52:
    case "CP_a102_wcOvertempFault":
      return ChargingAlertName.CP_a102_wcOvertempFault;
    case 53:
    case "CP_a108_chademoOvertempFault":
      return ChargingAlertName.CP_a108_chademoOvertempFault;
    case 54:
    case "CP_a110_thermalVelocityHigh":
      return ChargingAlertName.CP_a110_thermalVelocityHigh;
    case 55:
    case "CP_a120_comboAdapterFoldback":
      return ChargingAlertName.CP_a120_comboAdapterFoldback;
    case 56:
    case "CP_a131_evseCommTimeout":
      return ChargingAlertName.CP_a131_evseCommTimeout;
    case 57:
    case "CP_a132_contractAuthTimeout":
      return ChargingAlertName.CP_a132_contractAuthTimeout;
    case 58:
    case "CP_a133_proxNeverLatched":
      return ChargingAlertName.CP_a133_proxNeverLatched;
    case 59:
    case "CP_a135_sdpAttemptsFailed":
      return ChargingAlertName.CP_a135_sdpAttemptsFailed;
    case 60:
    case "CP_a139_pilotFaulted":
      return ChargingAlertName.CP_a139_pilotFaulted;
    case 61:
    case "CP_a140_superchargerFaulted":
      return ChargingAlertName.CP_a140_superchargerFaulted;
    case 62:
    case "CP_a141_chademoAdapterFault":
      return ChargingAlertName.CP_a141_chademoAdapterFault;
    case 63:
    case "CP_a142_gbdcScConnFault":
      return ChargingAlertName.CP_a142_gbdcScConnFault;
    case 64:
    case "CP_a143_unsupportedChargeAdapter":
      return ChargingAlertName.CP_a143_unsupportedChargeAdapter;
    case 65:
    case "CP_a146_ccsEvseMalfunction":
      return ChargingAlertName.CP_a146_ccsEvseMalfunction;
    case 66:
    case "CP_a151_badPilotDiodeDetected":
      return ChargingAlertName.CP_a151_badPilotDiodeDetected;
    case 67:
    case "CP_a152_pilotEdgeDetectionFailed":
      return ChargingAlertName.CP_a152_pilotEdgeDetectionFailed;
    case 68:
    case "FC_a141_CA_vehConn_OT":
      return ChargingAlertName.FC_a141_CA_vehConn_OT;
    case 69:
    case "FC_a142_CA_evseConn_OT":
      return ChargingAlertName.FC_a142_CA_evseConn_OT;
    case 70:
    case "FC_a143_CA_pcb_OT":
      return ChargingAlertName.FC_a143_CA_pcb_OT;
    case 71:
    case "FC_a151_CA_vehToEvseDeltaLo":
      return ChargingAlertName.FC_a151_CA_vehToEvseDeltaLo;
    case 72:
    case "FC_a154_CA_vehToPcbDeltaLo":
      return ChargingAlertName.FC_a154_CA_vehToPcbDeltaLo;
    case 73:
    case "FC_a161_CA_vehTempHiFoldBk":
      return ChargingAlertName.FC_a161_CA_vehTempHiFoldBk;
    case 74:
    case "FC_a162_CA_evseTempHiFoldBk":
      return ChargingAlertName.FC_a162_CA_evseTempHiFoldBk;
    case 75:
    case "FC_a163_CA_pcbTempHiFoldBk":
      return ChargingAlertName.FC_a163_CA_pcbTempHiFoldBk;
    case 76:
    case "FC_a266_GB_negPin_OT":
      return ChargingAlertName.FC_a266_GB_negPin_OT;
    case 77:
    case "FC_a267_GB_posPin_OT":
      return ChargingAlertName.FC_a267_GB_posPin_OT;
    case 78:
    case "FC_a268_GB_pcb_OT":
      return ChargingAlertName.FC_a268_GB_pcb_OT;
    case 79:
    case "FC_a272_GB_negToPosDeltaHi":
      return ChargingAlertName.FC_a272_GB_negToPosDeltaHi;
    case 80:
    case "FC_a273_GB_negToPosDeltaLo":
      return ChargingAlertName.FC_a273_GB_negToPosDeltaLo;
    case 81:
    case "FC_a274_GB_negToPcbDeltaHi":
      return ChargingAlertName.FC_a274_GB_negToPcbDeltaHi;
    case 82:
    case "FC_a282_GB_negTempHiFoldBk":
      return ChargingAlertName.FC_a282_GB_negTempHiFoldBk;
    case 83:
    case "FC_a283_GB_posTempHiFoldBk":
      return ChargingAlertName.FC_a283_GB_posTempHiFoldBk;
    case 84:
    case "FC_a284_GB_pcbTempHiFoldBk":
      return ChargingAlertName.FC_a284_GB_pcbTempHiFoldBk;
    case 85:
    case "FC_a286_GB_evseConnUnlocked":
      return ChargingAlertName.FC_a286_GB_evseConnUnlocked;
    case 86:
    case "PCS_a007_chgPhaseTempHot":
      return ChargingAlertName.PCS_a007_chgPhaseTempHot;
    case 87:
    case "PCS_a016_chgAllPhasesFaulted":
      return ChargingAlertName.PCS_a016_chgAllPhasesFaulted;
    case 88:
    case "PCS_a017_chgWallPowerRemoval":
      return ChargingAlertName.PCS_a017_chgWallPowerRemoval;
    case 89:
    case "PCS_a019_acChargePowerLimited":
      return ChargingAlertName.PCS_a019_acChargePowerLimited;
    case 90:
    case "PCS_a032_excessiveGridTransientsDetected":
      return ChargingAlertName.PCS_a032_excessiveGridTransientsDetected;
    case 91:
    case "PCS_a052_acVoltageNotPresent":
      return ChargingAlertName.PCS_a052_acVoltageNotPresent;
    case 92:
    case "PCS_a053_chgInputVDropHigh":
      return ChargingAlertName.PCS_a053_chgInputVDropHigh;
    case 93:
    case "PCS_a054_chgInputVDropTooHigh":
      return ChargingAlertName.PCS_a054_chgInputVDropTooHigh;
    case 94:
    case "PCS_a055_chgLineImpedanceHigh":
      return ChargingAlertName.PCS_a055_chgLineImpedanceHigh;
    case 95:
    case "PCS_a056_chgLineImpedanceTooHigh":
      return ChargingAlertName.PCS_a056_chgLineImpedanceTooHigh;
    case 96:
    case "PCS_a059_chgInputOvRms":
      return ChargingAlertName.PCS_a059_chgInputOvRms;
    case 97:
    case "PCS_a073_unexpectedAcInputVoltage":
      return ChargingAlertName.PCS_a073_unexpectedAcInputVoltage;
    case 98:
    case "PCS_a078_chgStopDcdcTooHot":
      return ChargingAlertName.PCS_a078_chgStopDcdcTooHot;
    case 99:
    case "PCS_a088_gridFreqDroopDetected":
      return ChargingAlertName.PCS_a088_gridFreqDroopDetected;
    case 100:
    case "PCS_a090_expectedAcVoltageSourceMissing":
      return ChargingAlertName.PCS_a090_expectedAcVoltageSourceMissing;
    case 101:
    case "PCS_a096_microGridOverLoaded":
      return ChargingAlertName.PCS_a096_microGridOverLoaded;
    case 102:
    case "PCS2_a019_DcacADcTempTooHigh":
      return ChargingAlertName.PCS2_a019_DcacADcTempTooHigh;
    case 103:
    case "PCS2_a020_DcacBDcTempTooHigh":
      return ChargingAlertName.PCS2_a020_DcacBDcTempTooHigh;
    case 104:
    case "PCS2_a024_DcacATxTempTooHigh":
      return ChargingAlertName.PCS2_a024_DcacATxTempTooHigh;
    case 105:
    case "PCS2_a025_DcacBTxTempTooHigh":
      return ChargingAlertName.PCS2_a025_DcacBTxTempTooHigh;
    case 106:
    case "PCS2_a062_acVoltageNotPresent":
      return ChargingAlertName.PCS2_a062_acVoltageNotPresent;
    case 107:
    case "PCS2_a063_chgUnknownGridConfig":
      return ChargingAlertName.PCS2_a063_chgUnknownGridConfig;
    case 108:
    case "PCS2_a112_chgInputVDropTooHigh":
      return ChargingAlertName.PCS2_a112_chgInputVDropTooHigh;
    case 109:
    case "PCS2_a115_chgWallPowerRemoval":
      return ChargingAlertName.PCS2_a115_chgWallPowerRemoval;
    case 110:
    case "PCS2_a116_chgPersistentFault":
      return ChargingAlertName.PCS2_a116_chgPersistentFault;
    case 111:
    case "UMC_a001_gndMonIntrptLineSide":
      return ChargingAlertName.UMC_a001_gndMonIntrptLineSide;
    case 112:
    case "UMC_a002_GFCITripped":
      return ChargingAlertName.UMC_a002_GFCITripped;
    case 113:
    case "UMC_a003_GFCISelfTestFault":
      return ChargingAlertName.UMC_a003_GFCISelfTestFault;
    case 114:
    case "UMC_a004_inputOverVoltage":
      return ChargingAlertName.UMC_a004_inputOverVoltage;
    case 115:
    case "UMC_a005_inputUnderVoltage":
      return ChargingAlertName.UMC_a005_inputUnderVoltage;
    case 116:
    case "UMC_a006_contactorWelded":
      return ChargingAlertName.UMC_a006_contactorWelded;
    case 117:
    case "UMC_a007_pcbaOT":
      return ChargingAlertName.UMC_a007_pcbaOT;
    case 118:
    case "UMC_a008_wallPlugOT":
      return ChargingAlertName.UMC_a008_wallPlugOT;
    case 119:
    case "UMC_a009_vehConnOT":
      return ChargingAlertName.UMC_a009_vehConnOT;
    case 120:
    case "UMC_a010_inputOT":
      return ChargingAlertName.UMC_a010_inputOT;
    case 121:
    case "UMC_a011_proxDisconnected":
      return ChargingAlertName.UMC_a011_proxDisconnected;
    case 122:
    case "UMC_a012_pilotFault":
      return ChargingAlertName.UMC_a012_pilotFault;
    case 123:
    case "UMC_a013_SA_Temperature":
      return ChargingAlertName.UMC_a013_SA_Temperature;
    case 124:
    case "UMC_a014_SA_Genealogy":
      return ChargingAlertName.UMC_a014_SA_Genealogy;
    case 125:
    case "UMC_a015_SA_Connection":
      return ChargingAlertName.UMC_a015_SA_Connection;
    case 126:
    case "UMC_a016_pcbaOTFoldback":
      return ChargingAlertName.UMC_a016_pcbaOTFoldback;
    case 127:
    case "UMC_a017_wallPlugOTFoldback":
      return ChargingAlertName.UMC_a017_wallPlugOTFoldback;
    case 128:
    case "UMC_a018_vehConnOTFoldback":
      return ChargingAlertName.UMC_a018_vehConnOTFoldback;
    case 129:
    case "UMC_a019_inputOTFoldback":
      return ChargingAlertName.UMC_a019_inputOTFoldback;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ChargingAlertName.UNRECOGNIZED;
  }
}

export function chargingAlertNameToJSON(object: ChargingAlertName): string {
  switch (object) {
    case ChargingAlertName.INVALID_ALERT_NAME:
      return "INVALID_ALERT_NAME";
    case ChargingAlertName.BMS_a007_SW_Slowed_Chg_Batt_Cold_OBSOLETE:
      return "BMS_a007_SW_Slowed_Chg_Batt_Cold_OBSOLETE";
    case ChargingAlertName.BMS_a076_SW_Dch_While_Charging:
      return "BMS_a076_SW_Dch_While_Charging";
    case ChargingAlertName.CC_a001_gndMonIntrptLineSide:
      return "CC_a001_gndMonIntrptLineSide";
    case ChargingAlertName.CC_a002_gndMonIntrptLoadSide:
      return "CC_a002_gndMonIntrptLoadSide";
    case ChargingAlertName.CC_a003_CCIDTripped:
      return "CC_a003_CCIDTripped";
    case ChargingAlertName.CC_a004_CCIDSelfTestFault:
      return "CC_a004_CCIDSelfTestFault";
    case ChargingAlertName.CC_a005_groundedNeutral:
      return "CC_a005_groundedNeutral";
    case ChargingAlertName.CC_a006_inputOverCurrent:
      return "CC_a006_inputOverCurrent";
    case ChargingAlertName.CC_a007_inputOverVoltage:
      return "CC_a007_inputOverVoltage";
    case ChargingAlertName.CC_a008_inputUnderVoltage:
      return "CC_a008_inputUnderVoltage";
    case ChargingAlertName.CC_a009_inputMiswired:
      return "CC_a009_inputMiswired";
    case ChargingAlertName.CC_a010_contactorWelded:
      return "CC_a010_contactorWelded";
    case ChargingAlertName.CC_a011_ambientOT:
      return "CC_a011_ambientOT";
    case ChargingAlertName.CC_a012_wallPlugOT:
      return "CC_a012_wallPlugOT";
    case ChargingAlertName.CC_a013_vehConnOT:
      return "CC_a013_vehConnOT";
    case ChargingAlertName.CC_a014_mcuSelfTestFault:
      return "CC_a014_mcuSelfTestFault";
    case ChargingAlertName.CC_a015_PilotAFault:
      return "CC_a015_PilotAFault";
    case ChargingAlertName.CC_a016_PilotBFault:
      return "CC_a016_PilotBFault";
    case ChargingAlertName.CC_a017_PilotCFault:
      return "CC_a017_PilotCFault";
    case ChargingAlertName.CC_a018_PilotDFault:
      return "CC_a018_PilotDFault";
    case ChargingAlertName.CC_a019_proxDisconnected:
      return "CC_a019_proxDisconnected";
    case ChargingAlertName.CC_a020_3vRailIncorrect:
      return "CC_a020_3vRailIncorrect";
    case ChargingAlertName.CC_a021_CB_noMaster:
      return "CC_a021_CB_noMaster";
    case ChargingAlertName.CC_a022_CB_tooManyMasters:
      return "CC_a022_CB_tooManyMasters";
    case ChargingAlertName.CC_a023_CB_tooManySlaves:
      return "CC_a023_CB_tooManySlaves";
    case ChargingAlertName.CC_a024_CB_masterISetTooLow:
      return "CC_a024_CB_masterISetTooLow";
    case ChargingAlertName.CC_a025_evseTemp:
      return "CC_a025_evseTemp";
    case ChargingAlertName.CC_a026_wallPlugTemp:
      return "CC_a026_wallPlugTemp";
    case ChargingAlertName.CC_a027_vehicleHandleTemp:
      return "CC_a027_vehicleHandleTemp";
    case ChargingAlertName.CC_a028_CB_rotarySelect:
      return "CC_a028_CB_rotarySelect";
    case ChargingAlertName.CC_a029_PilotFFault:
      return "CC_a029_PilotFFault";
    case ChargingAlertName.CC_a030_masterSlaveMismatch:
      return "CC_a030_masterSlaveMismatch";
    case ChargingAlertName.CC_a041_inputWiringFoldback:
      return "CC_a041_inputWiringFoldback";
    case ChargingAlertName.CC_a042_pcbaTempFoldback:
      return "CC_a042_pcbaTempFoldback";
    case ChargingAlertName.CC_a043_configurationRequired:
      return "CC_a043_configurationRequired";
    case ChargingAlertName.CP_a004_proximityRationality:
      return "CP_a004_proximityRationality";
    case ChargingAlertName.CP_a010_pilotRationality:
      return "CP_a010_pilotRationality";
    case ChargingAlertName.CP_a046_lostCommsEVSE:
      return "CP_a046_lostCommsEVSE";
    case ChargingAlertName.CP_a049_multipleCablesDetected:
      return "CP_a049_multipleCablesDetected";
    case ChargingAlertName.CP_a052_chademoNotSupported:
      return "CP_a052_chademoNotSupported";
    case ChargingAlertName.CP_a053_proxLatchedNoPilot:
      return "CP_a053_proxLatchedNoPilot";
    case ChargingAlertName.CP_a055_chargeStoppedNoPilot:
      return "CP_a055_chargeStoppedNoPilot";
    case ChargingAlertName.CP_a058_acChargingBlocked:
      return "CP_a058_acChargingBlocked";
    case ChargingAlertName.CP_a062_scOutOfService:
      return "CP_a062_scOutOfService";
    case ChargingAlertName.CP_a063_scUpdateInProgress:
      return "CP_a063_scUpdateInProgress";
    case ChargingAlertName.CP_a064_superchargingBlocked:
      return "CP_a064_superchargingBlocked";
    case ChargingAlertName.CP_a066_proxLatchedIdlePilot:
      return "CP_a066_proxLatchedIdlePilot";
    case ChargingAlertName.CP_a067_gbdcConnFault:
      return "CP_a067_gbdcConnFault";
    case ChargingAlertName.CP_a074_failedToEstablishV2gComm:
      return "CP_a074_failedToEstablishV2gComm";
    case ChargingAlertName.CP_a091_wrongSuperchargerHandle:
      return "CP_a091_wrongSuperchargerHandle";
    case ChargingAlertName.CP_a101_wcFoldbackActive:
      return "CP_a101_wcFoldbackActive";
    case ChargingAlertName.CP_a102_wcOvertempFault:
      return "CP_a102_wcOvertempFault";
    case ChargingAlertName.CP_a108_chademoOvertempFault:
      return "CP_a108_chademoOvertempFault";
    case ChargingAlertName.CP_a110_thermalVelocityHigh:
      return "CP_a110_thermalVelocityHigh";
    case ChargingAlertName.CP_a120_comboAdapterFoldback:
      return "CP_a120_comboAdapterFoldback";
    case ChargingAlertName.CP_a131_evseCommTimeout:
      return "CP_a131_evseCommTimeout";
    case ChargingAlertName.CP_a132_contractAuthTimeout:
      return "CP_a132_contractAuthTimeout";
    case ChargingAlertName.CP_a133_proxNeverLatched:
      return "CP_a133_proxNeverLatched";
    case ChargingAlertName.CP_a135_sdpAttemptsFailed:
      return "CP_a135_sdpAttemptsFailed";
    case ChargingAlertName.CP_a139_pilotFaulted:
      return "CP_a139_pilotFaulted";
    case ChargingAlertName.CP_a140_superchargerFaulted:
      return "CP_a140_superchargerFaulted";
    case ChargingAlertName.CP_a141_chademoAdapterFault:
      return "CP_a141_chademoAdapterFault";
    case ChargingAlertName.CP_a142_gbdcScConnFault:
      return "CP_a142_gbdcScConnFault";
    case ChargingAlertName.CP_a143_unsupportedChargeAdapter:
      return "CP_a143_unsupportedChargeAdapter";
    case ChargingAlertName.CP_a146_ccsEvseMalfunction:
      return "CP_a146_ccsEvseMalfunction";
    case ChargingAlertName.CP_a151_badPilotDiodeDetected:
      return "CP_a151_badPilotDiodeDetected";
    case ChargingAlertName.CP_a152_pilotEdgeDetectionFailed:
      return "CP_a152_pilotEdgeDetectionFailed";
    case ChargingAlertName.FC_a141_CA_vehConn_OT:
      return "FC_a141_CA_vehConn_OT";
    case ChargingAlertName.FC_a142_CA_evseConn_OT:
      return "FC_a142_CA_evseConn_OT";
    case ChargingAlertName.FC_a143_CA_pcb_OT:
      return "FC_a143_CA_pcb_OT";
    case ChargingAlertName.FC_a151_CA_vehToEvseDeltaLo:
      return "FC_a151_CA_vehToEvseDeltaLo";
    case ChargingAlertName.FC_a154_CA_vehToPcbDeltaLo:
      return "FC_a154_CA_vehToPcbDeltaLo";
    case ChargingAlertName.FC_a161_CA_vehTempHiFoldBk:
      return "FC_a161_CA_vehTempHiFoldBk";
    case ChargingAlertName.FC_a162_CA_evseTempHiFoldBk:
      return "FC_a162_CA_evseTempHiFoldBk";
    case ChargingAlertName.FC_a163_CA_pcbTempHiFoldBk:
      return "FC_a163_CA_pcbTempHiFoldBk";
    case ChargingAlertName.FC_a266_GB_negPin_OT:
      return "FC_a266_GB_negPin_OT";
    case ChargingAlertName.FC_a267_GB_posPin_OT:
      return "FC_a267_GB_posPin_OT";
    case ChargingAlertName.FC_a268_GB_pcb_OT:
      return "FC_a268_GB_pcb_OT";
    case ChargingAlertName.FC_a272_GB_negToPosDeltaHi:
      return "FC_a272_GB_negToPosDeltaHi";
    case ChargingAlertName.FC_a273_GB_negToPosDeltaLo:
      return "FC_a273_GB_negToPosDeltaLo";
    case ChargingAlertName.FC_a274_GB_negToPcbDeltaHi:
      return "FC_a274_GB_negToPcbDeltaHi";
    case ChargingAlertName.FC_a282_GB_negTempHiFoldBk:
      return "FC_a282_GB_negTempHiFoldBk";
    case ChargingAlertName.FC_a283_GB_posTempHiFoldBk:
      return "FC_a283_GB_posTempHiFoldBk";
    case ChargingAlertName.FC_a284_GB_pcbTempHiFoldBk:
      return "FC_a284_GB_pcbTempHiFoldBk";
    case ChargingAlertName.FC_a286_GB_evseConnUnlocked:
      return "FC_a286_GB_evseConnUnlocked";
    case ChargingAlertName.PCS_a007_chgPhaseTempHot:
      return "PCS_a007_chgPhaseTempHot";
    case ChargingAlertName.PCS_a016_chgAllPhasesFaulted:
      return "PCS_a016_chgAllPhasesFaulted";
    case ChargingAlertName.PCS_a017_chgWallPowerRemoval:
      return "PCS_a017_chgWallPowerRemoval";
    case ChargingAlertName.PCS_a019_acChargePowerLimited:
      return "PCS_a019_acChargePowerLimited";
    case ChargingAlertName.PCS_a032_excessiveGridTransientsDetected:
      return "PCS_a032_excessiveGridTransientsDetected";
    case ChargingAlertName.PCS_a052_acVoltageNotPresent:
      return "PCS_a052_acVoltageNotPresent";
    case ChargingAlertName.PCS_a053_chgInputVDropHigh:
      return "PCS_a053_chgInputVDropHigh";
    case ChargingAlertName.PCS_a054_chgInputVDropTooHigh:
      return "PCS_a054_chgInputVDropTooHigh";
    case ChargingAlertName.PCS_a055_chgLineImpedanceHigh:
      return "PCS_a055_chgLineImpedanceHigh";
    case ChargingAlertName.PCS_a056_chgLineImpedanceTooHigh:
      return "PCS_a056_chgLineImpedanceTooHigh";
    case ChargingAlertName.PCS_a059_chgInputOvRms:
      return "PCS_a059_chgInputOvRms";
    case ChargingAlertName.PCS_a073_unexpectedAcInputVoltage:
      return "PCS_a073_unexpectedAcInputVoltage";
    case ChargingAlertName.PCS_a078_chgStopDcdcTooHot:
      return "PCS_a078_chgStopDcdcTooHot";
    case ChargingAlertName.PCS_a088_gridFreqDroopDetected:
      return "PCS_a088_gridFreqDroopDetected";
    case ChargingAlertName.PCS_a090_expectedAcVoltageSourceMissing:
      return "PCS_a090_expectedAcVoltageSourceMissing";
    case ChargingAlertName.PCS_a096_microGridOverLoaded:
      return "PCS_a096_microGridOverLoaded";
    case ChargingAlertName.PCS2_a019_DcacADcTempTooHigh:
      return "PCS2_a019_DcacADcTempTooHigh";
    case ChargingAlertName.PCS2_a020_DcacBDcTempTooHigh:
      return "PCS2_a020_DcacBDcTempTooHigh";
    case ChargingAlertName.PCS2_a024_DcacATxTempTooHigh:
      return "PCS2_a024_DcacATxTempTooHigh";
    case ChargingAlertName.PCS2_a025_DcacBTxTempTooHigh:
      return "PCS2_a025_DcacBTxTempTooHigh";
    case ChargingAlertName.PCS2_a062_acVoltageNotPresent:
      return "PCS2_a062_acVoltageNotPresent";
    case ChargingAlertName.PCS2_a063_chgUnknownGridConfig:
      return "PCS2_a063_chgUnknownGridConfig";
    case ChargingAlertName.PCS2_a112_chgInputVDropTooHigh:
      return "PCS2_a112_chgInputVDropTooHigh";
    case ChargingAlertName.PCS2_a115_chgWallPowerRemoval:
      return "PCS2_a115_chgWallPowerRemoval";
    case ChargingAlertName.PCS2_a116_chgPersistentFault:
      return "PCS2_a116_chgPersistentFault";
    case ChargingAlertName.UMC_a001_gndMonIntrptLineSide:
      return "UMC_a001_gndMonIntrptLineSide";
    case ChargingAlertName.UMC_a002_GFCITripped:
      return "UMC_a002_GFCITripped";
    case ChargingAlertName.UMC_a003_GFCISelfTestFault:
      return "UMC_a003_GFCISelfTestFault";
    case ChargingAlertName.UMC_a004_inputOverVoltage:
      return "UMC_a004_inputOverVoltage";
    case ChargingAlertName.UMC_a005_inputUnderVoltage:
      return "UMC_a005_inputUnderVoltage";
    case ChargingAlertName.UMC_a006_contactorWelded:
      return "UMC_a006_contactorWelded";
    case ChargingAlertName.UMC_a007_pcbaOT:
      return "UMC_a007_pcbaOT";
    case ChargingAlertName.UMC_a008_wallPlugOT:
      return "UMC_a008_wallPlugOT";
    case ChargingAlertName.UMC_a009_vehConnOT:
      return "UMC_a009_vehConnOT";
    case ChargingAlertName.UMC_a010_inputOT:
      return "UMC_a010_inputOT";
    case ChargingAlertName.UMC_a011_proxDisconnected:
      return "UMC_a011_proxDisconnected";
    case ChargingAlertName.UMC_a012_pilotFault:
      return "UMC_a012_pilotFault";
    case ChargingAlertName.UMC_a013_SA_Temperature:
      return "UMC_a013_SA_Temperature";
    case ChargingAlertName.UMC_a014_SA_Genealogy:
      return "UMC_a014_SA_Genealogy";
    case ChargingAlertName.UMC_a015_SA_Connection:
      return "UMC_a015_SA_Connection";
    case ChargingAlertName.UMC_a016_pcbaOTFoldback:
      return "UMC_a016_pcbaOTFoldback";
    case ChargingAlertName.UMC_a017_wallPlugOTFoldback:
      return "UMC_a017_wallPlugOTFoldback";
    case ChargingAlertName.UMC_a018_vehConnOTFoldback:
      return "UMC_a018_vehConnOTFoldback";
    case ChargingAlertName.UMC_a019_inputOTFoldback:
      return "UMC_a019_inputOTFoldback";
    case ChargingAlertName.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ChassisType {
  ChassisTypeModel3 = 0,
  ChassisTypeModelY = 1,
  ChassisTypeModelYLongWheelBase = 2,
  UNRECOGNIZED = -1,
}

export function chassisTypeFromJSON(object: any): ChassisType {
  switch (object) {
    case 0:
    case "ChassisTypeModel3":
      return ChassisType.ChassisTypeModel3;
    case 1:
    case "ChassisTypeModelY":
      return ChassisType.ChassisTypeModelY;
    case 2:
    case "ChassisTypeModelYLongWheelBase":
      return ChassisType.ChassisTypeModelYLongWheelBase;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ChassisType.UNRECOGNIZED;
  }
}

export function chassisTypeToJSON(object: ChassisType): string {
  switch (object) {
    case ChassisType.ChassisTypeModel3:
      return "ChassisTypeModel3";
    case ChassisType.ChassisTypeModelY:
      return "ChassisTypeModelY";
    case ChassisType.ChassisTypeModelYLongWheelBase:
      return "ChassisTypeModelYLongWheelBase";
    case ChassisType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum FasciaType {
  FasciaTypeOriginal = 0,
  FasciaTypeBasePoppyseed = 1,
  FasciaTypePerformancePoppyseed = 2,
  FasciaTypeBaseBayberry = 4,
  FasciaTypePerformanceBayberry = 6,
  FasciaTypeP3S = 7,
  FasciaTypeE41Bayberry = 8,
  FasciaTypeD50Poppyseed = 9,
  UNRECOGNIZED = -1,
}

export function fasciaTypeFromJSON(object: any): FasciaType {
  switch (object) {
    case 0:
    case "FasciaTypeOriginal":
      return FasciaType.FasciaTypeOriginal;
    case 1:
    case "FasciaTypeBasePoppyseed":
      return FasciaType.FasciaTypeBasePoppyseed;
    case 2:
    case "FasciaTypePerformancePoppyseed":
      return FasciaType.FasciaTypePerformancePoppyseed;
    case 4:
    case "FasciaTypeBaseBayberry":
      return FasciaType.FasciaTypeBaseBayberry;
    case 6:
    case "FasciaTypePerformanceBayberry":
      return FasciaType.FasciaTypePerformanceBayberry;
    case 7:
    case "FasciaTypeP3S":
      return FasciaType.FasciaTypeP3S;
    case 8:
    case "FasciaTypeE41Bayberry":
      return FasciaType.FasciaTypeE41Bayberry;
    case 9:
    case "FasciaTypeD50Poppyseed":
      return FasciaType.FasciaTypeD50Poppyseed;
    case -1:
    case "UNRECOGNIZED":
    default:
      return FasciaType.UNRECOGNIZED;
  }
}

export function fasciaTypeToJSON(object: FasciaType): string {
  switch (object) {
    case FasciaType.FasciaTypeOriginal:
      return "FasciaTypeOriginal";
    case FasciaType.FasciaTypeBasePoppyseed:
      return "FasciaTypeBasePoppyseed";
    case FasciaType.FasciaTypePerformancePoppyseed:
      return "FasciaTypePerformancePoppyseed";
    case FasciaType.FasciaTypeBaseBayberry:
      return "FasciaTypeBaseBayberry";
    case FasciaType.FasciaTypePerformanceBayberry:
      return "FasciaTypePerformanceBayberry";
    case FasciaType.FasciaTypeP3S:
      return "FasciaTypeP3S";
    case FasciaType.FasciaTypeE41Bayberry:
      return "FasciaTypeE41Bayberry";
    case FasciaType.FasciaTypeD50Poppyseed:
      return "FasciaTypeD50Poppyseed";
    case FasciaType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum GtwDiagLevel {
  GtwDiagLevelFactory = 0,
  GtwDiagLevelDiagLinkActive = 1,
  GtwDiagLevelService = 2,
  GtwDiagLevelServiceDrive = 3,
  GtwDiagLevelPark = 4,
  GtwDiagLevelNormalOperation = 5,
  GtwDiagLevelParkRobotaxi = 6,
  UNRECOGNIZED = -1,
}

export function gtwDiagLevelFromJSON(object: any): GtwDiagLevel {
  switch (object) {
    case 0:
    case "GtwDiagLevelFactory":
      return GtwDiagLevel.GtwDiagLevelFactory;
    case 1:
    case "GtwDiagLevelDiagLinkActive":
      return GtwDiagLevel.GtwDiagLevelDiagLinkActive;
    case 2:
    case "GtwDiagLevelService":
      return GtwDiagLevel.GtwDiagLevelService;
    case 3:
    case "GtwDiagLevelServiceDrive":
      return GtwDiagLevel.GtwDiagLevelServiceDrive;
    case 4:
    case "GtwDiagLevelPark":
      return GtwDiagLevel.GtwDiagLevelPark;
    case 5:
    case "GtwDiagLevelNormalOperation":
      return GtwDiagLevel.GtwDiagLevelNormalOperation;
    case 6:
    case "GtwDiagLevelParkRobotaxi":
      return GtwDiagLevel.GtwDiagLevelParkRobotaxi;
    case -1:
    case "UNRECOGNIZED":
    default:
      return GtwDiagLevel.UNRECOGNIZED;
  }
}

export function gtwDiagLevelToJSON(object: GtwDiagLevel): string {
  switch (object) {
    case GtwDiagLevel.GtwDiagLevelFactory:
      return "GtwDiagLevelFactory";
    case GtwDiagLevel.GtwDiagLevelDiagLinkActive:
      return "GtwDiagLevelDiagLinkActive";
    case GtwDiagLevel.GtwDiagLevelService:
      return "GtwDiagLevelService";
    case GtwDiagLevel.GtwDiagLevelServiceDrive:
      return "GtwDiagLevelServiceDrive";
    case GtwDiagLevel.GtwDiagLevelPark:
      return "GtwDiagLevelPark";
    case GtwDiagLevel.GtwDiagLevelNormalOperation:
      return "GtwDiagLevelNormalOperation";
    case GtwDiagLevel.GtwDiagLevelParkRobotaxi:
      return "GtwDiagLevelParkRobotaxi";
    case GtwDiagLevel.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum RearSeatHeaterType {
  RearSeatHeaterTypeInvalid = 0,
  ThreeSeatsKongsberg = 1,
  LeftRightOnlyKongsberg = 2,
  UNRECOGNIZED = -1,
}

export function rearSeatHeaterTypeFromJSON(object: any): RearSeatHeaterType {
  switch (object) {
    case 0:
    case "RearSeatHeaterTypeInvalid":
      return RearSeatHeaterType.RearSeatHeaterTypeInvalid;
    case 1:
    case "ThreeSeatsKongsberg":
      return RearSeatHeaterType.ThreeSeatsKongsberg;
    case 2:
    case "LeftRightOnlyKongsberg":
      return RearSeatHeaterType.LeftRightOnlyKongsberg;
    case -1:
    case "UNRECOGNIZED":
    default:
      return RearSeatHeaterType.UNRECOGNIZED;
  }
}

export function rearSeatHeaterTypeToJSON(object: RearSeatHeaterType): string {
  switch (object) {
    case RearSeatHeaterType.RearSeatHeaterTypeInvalid:
      return "RearSeatHeaterTypeInvalid";
    case RearSeatHeaterType.ThreeSeatsKongsberg:
      return "ThreeSeatsKongsberg";
    case RearSeatHeaterType.LeftRightOnlyKongsberg:
      return "LeftRightOnlyKongsberg";
    case RearSeatHeaterType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum AccessoryLightbarType {
  AccessoryLightbarTypeNone = 0,
  AccessoryLightbarTypeHella = 1,
  UNRECOGNIZED = -1,
}

export function accessoryLightbarTypeFromJSON(object: any): AccessoryLightbarType {
  switch (object) {
    case 0:
    case "AccessoryLightbarTypeNone":
      return AccessoryLightbarType.AccessoryLightbarTypeNone;
    case 1:
    case "AccessoryLightbarTypeHella":
      return AccessoryLightbarType.AccessoryLightbarTypeHella;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AccessoryLightbarType.UNRECOGNIZED;
  }
}

export function accessoryLightbarTypeToJSON(object: AccessoryLightbarType): string {
  switch (object) {
    case AccessoryLightbarType.AccessoryLightbarTypeNone:
      return "AccessoryLightbarTypeNone";
    case AccessoryLightbarType.AccessoryLightbarTypeHella:
      return "AccessoryLightbarTypeHella";
    case AccessoryLightbarType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum SuspensionActuationState {
  INVALID_SUSPENSION_ACTION = 0,
  NONE = 1,
  RAISING = 2,
  LOWERING = 3,
  UNRECOGNIZED = -1,
}

export function suspensionActuationStateFromJSON(object: any): SuspensionActuationState {
  switch (object) {
    case 0:
    case "INVALID_SUSPENSION_ACTION":
      return SuspensionActuationState.INVALID_SUSPENSION_ACTION;
    case 1:
    case "NONE":
      return SuspensionActuationState.NONE;
    case 2:
    case "RAISING":
      return SuspensionActuationState.RAISING;
    case 3:
    case "LOWERING":
      return SuspensionActuationState.LOWERING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SuspensionActuationState.UNRECOGNIZED;
  }
}

export function suspensionActuationStateToJSON(object: SuspensionActuationState): string {
  switch (object) {
    case SuspensionActuationState.INVALID_SUSPENSION_ACTION:
      return "INVALID_SUSPENSION_ACTION";
    case SuspensionActuationState.NONE:
      return "NONE";
    case SuspensionActuationState.RAISING:
      return "RAISING";
    case SuspensionActuationState.LOWERING:
      return "LOWERING";
    case SuspensionActuationState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum SuspensionLevel {
  INVALID_SUSPENSION_LEVEL = 0,
  ENTRY = 1,
  LOW = 2,
  MEDIUM = 3,
  HIGH = 4,
  VERY_HIGH = 5,
  EXTRACT = 6,
  UNRECOGNIZED = -1,
}

export function suspensionLevelFromJSON(object: any): SuspensionLevel {
  switch (object) {
    case 0:
    case "INVALID_SUSPENSION_LEVEL":
      return SuspensionLevel.INVALID_SUSPENSION_LEVEL;
    case 1:
    case "ENTRY":
      return SuspensionLevel.ENTRY;
    case 2:
    case "LOW":
      return SuspensionLevel.LOW;
    case 3:
    case "MEDIUM":
      return SuspensionLevel.MEDIUM;
    case 4:
    case "HIGH":
      return SuspensionLevel.HIGH;
    case 5:
    case "VERY_HIGH":
      return SuspensionLevel.VERY_HIGH;
    case 6:
    case "EXTRACT":
      return SuspensionLevel.EXTRACT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SuspensionLevel.UNRECOGNIZED;
  }
}

export function suspensionLevelToJSON(object: SuspensionLevel): string {
  switch (object) {
    case SuspensionLevel.INVALID_SUSPENSION_LEVEL:
      return "INVALID_SUSPENSION_LEVEL";
    case SuspensionLevel.ENTRY:
      return "ENTRY";
    case SuspensionLevel.LOW:
      return "LOW";
    case SuspensionLevel.MEDIUM:
      return "MEDIUM";
    case SuspensionLevel.HIGH:
      return "HIGH";
    case SuspensionLevel.VERY_HIGH:
      return "VERY_HIGH";
    case SuspensionLevel.EXTRACT:
      return "EXTRACT";
    case SuspensionLevel.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ZoneLightRequest {
  ZoneLightRequestOff = 0,
  ZoneLightRequestLow = 1,
  ZoneLightRequestMedium = 2,
  ZoneLightRequestHigh = 3,
  UNRECOGNIZED = -1,
}

export function zoneLightRequestFromJSON(object: any): ZoneLightRequest {
  switch (object) {
    case 0:
    case "ZoneLightRequestOff":
      return ZoneLightRequest.ZoneLightRequestOff;
    case 1:
    case "ZoneLightRequestLow":
      return ZoneLightRequest.ZoneLightRequestLow;
    case 2:
    case "ZoneLightRequestMedium":
      return ZoneLightRequest.ZoneLightRequestMedium;
    case 3:
    case "ZoneLightRequestHigh":
      return ZoneLightRequest.ZoneLightRequestHigh;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ZoneLightRequest.UNRECOGNIZED;
  }
}

export function zoneLightRequestToJSON(object: ZoneLightRequest): string {
  switch (object) {
    case ZoneLightRequest.ZoneLightRequestOff:
      return "ZoneLightRequestOff";
    case ZoneLightRequest.ZoneLightRequestLow:
      return "ZoneLightRequestLow";
    case ZoneLightRequest.ZoneLightRequestMedium:
      return "ZoneLightRequestMedium";
    case ZoneLightRequest.ZoneLightRequestHigh:
      return "ZoneLightRequestHigh";
    case ZoneLightRequest.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Void {
}

export interface LatLong {
  latitude: number;
  longitude: number;
}

export interface ChargePortLatchState {
  SNA?: Void | undefined;
  Disengaged?: Void | undefined;
  Engaged?: Void | undefined;
  Blocking?: Void | undefined;
}

export interface PreconditioningTimes {
  allWeek?: Void | undefined;
  weekdays?: Void | undefined;
}

export interface OffPeakChargingTimes {
  allWeek?: Void | undefined;
  weekdays?: Void | undefined;
}

export interface ChargeSchedule {
  /** datetime in epoch time */
  id: number;
  name: string;
  daysOfWeek: number;
  startEnabled: boolean;
  /** 24h in minutes */
  startTime: number;
  endEnabled: boolean;
  /** 24h in minutes */
  endTime: number;
  oneTime: boolean;
  enabled: boolean;
  latitude: number;
  longitude: number;
}

export interface PreconditionSchedule {
  /** datetime in epoch time */
  id: number;
  name: string;
  daysOfWeek: number;
  /** 24h in minutes */
  preconditionTime: number;
  oneTime: boolean;
  enabled: boolean;
  latitude: number;
  longitude: number;
}

/** ===== TESLEMETRY-EXT BEGIN (app-4.58.6) ===== */
export interface ChargingAlert {
  alertName: ChargingAlertName;
  alertType: ChargingAlertType;
}

function createBaseVoid(): Void {
  return {};
}

export const Void: MessageFns<Void> = {
  encode(_: Void, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Void {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVoid();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Void {
    return {};
  },

  toJSON(_: Void): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Void>, I>>(base?: I): Void {
    return Void.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Void>, I>>(_: I): Void {
    const message = createBaseVoid();
    return message;
  },
};

function createBaseLatLong(): LatLong {
  return { latitude: 0, longitude: 0 };
}

export const LatLong: MessageFns<LatLong> = {
  encode(message: LatLong, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.latitude !== 0) {
      writer.uint32(13).float(message.latitude);
    }
    if (message.longitude !== 0) {
      writer.uint32(21).float(message.longitude);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LatLong {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLatLong();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.latitude = reader.float();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.longitude = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LatLong {
    return {
      latitude: isSet(object.latitude) ? globalThis.Number(object.latitude) : 0,
      longitude: isSet(object.longitude) ? globalThis.Number(object.longitude) : 0,
    };
  },

  toJSON(message: LatLong): unknown {
    const obj: any = {};
    if (message.latitude !== undefined) {
      obj.latitude = message.latitude;
    }
    if (message.longitude !== undefined) {
      obj.longitude = message.longitude;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LatLong>, I>>(base?: I): LatLong {
    return LatLong.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LatLong>, I>>(object: I): LatLong {
    const message = createBaseLatLong();
    message.latitude = object.latitude ?? 0;
    message.longitude = object.longitude ?? 0;
    return message;
  },
};

function createBaseChargePortLatchState(): ChargePortLatchState {
  return { SNA: undefined, Disengaged: undefined, Engaged: undefined, Blocking: undefined };
}

export const ChargePortLatchState: MessageFns<ChargePortLatchState> = {
  encode(message: ChargePortLatchState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.SNA !== undefined) {
      Void.encode(message.SNA, writer.uint32(10).fork()).join();
    }
    if (message.Disengaged !== undefined) {
      Void.encode(message.Disengaged, writer.uint32(18).fork()).join();
    }
    if (message.Engaged !== undefined) {
      Void.encode(message.Engaged, writer.uint32(26).fork()).join();
    }
    if (message.Blocking !== undefined) {
      Void.encode(message.Blocking, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChargePortLatchState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChargePortLatchState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.SNA = Void.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.Disengaged = Void.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.Engaged = Void.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.Blocking = Void.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChargePortLatchState {
    return {
      SNA: isSet(object.SNA) ? Void.fromJSON(object.SNA) : undefined,
      Disengaged: isSet(object.Disengaged) ? Void.fromJSON(object.Disengaged) : undefined,
      Engaged: isSet(object.Engaged) ? Void.fromJSON(object.Engaged) : undefined,
      Blocking: isSet(object.Blocking) ? Void.fromJSON(object.Blocking) : undefined,
    };
  },

  toJSON(message: ChargePortLatchState): unknown {
    const obj: any = {};
    if (message.SNA !== undefined) {
      obj.SNA = Void.toJSON(message.SNA);
    }
    if (message.Disengaged !== undefined) {
      obj.Disengaged = Void.toJSON(message.Disengaged);
    }
    if (message.Engaged !== undefined) {
      obj.Engaged = Void.toJSON(message.Engaged);
    }
    if (message.Blocking !== undefined) {
      obj.Blocking = Void.toJSON(message.Blocking);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChargePortLatchState>, I>>(base?: I): ChargePortLatchState {
    return ChargePortLatchState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChargePortLatchState>, I>>(object: I): ChargePortLatchState {
    const message = createBaseChargePortLatchState();
    message.SNA = (object.SNA !== undefined && object.SNA !== null) ? Void.fromPartial(object.SNA) : undefined;
    message.Disengaged = (object.Disengaged !== undefined && object.Disengaged !== null)
      ? Void.fromPartial(object.Disengaged)
      : undefined;
    message.Engaged = (object.Engaged !== undefined && object.Engaged !== null)
      ? Void.fromPartial(object.Engaged)
      : undefined;
    message.Blocking = (object.Blocking !== undefined && object.Blocking !== null)
      ? Void.fromPartial(object.Blocking)
      : undefined;
    return message;
  },
};

function createBasePreconditioningTimes(): PreconditioningTimes {
  return { allWeek: undefined, weekdays: undefined };
}

export const PreconditioningTimes: MessageFns<PreconditioningTimes> = {
  encode(message: PreconditioningTimes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.allWeek !== undefined) {
      Void.encode(message.allWeek, writer.uint32(10).fork()).join();
    }
    if (message.weekdays !== undefined) {
      Void.encode(message.weekdays, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PreconditioningTimes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePreconditioningTimes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.allWeek = Void.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.weekdays = Void.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PreconditioningTimes {
    return {
      allWeek: isSet(object.allWeek) ? Void.fromJSON(object.allWeek) : undefined,
      weekdays: isSet(object.weekdays) ? Void.fromJSON(object.weekdays) : undefined,
    };
  },

  toJSON(message: PreconditioningTimes): unknown {
    const obj: any = {};
    if (message.allWeek !== undefined) {
      obj.allWeek = Void.toJSON(message.allWeek);
    }
    if (message.weekdays !== undefined) {
      obj.weekdays = Void.toJSON(message.weekdays);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PreconditioningTimes>, I>>(base?: I): PreconditioningTimes {
    return PreconditioningTimes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PreconditioningTimes>, I>>(object: I): PreconditioningTimes {
    const message = createBasePreconditioningTimes();
    message.allWeek = (object.allWeek !== undefined && object.allWeek !== null)
      ? Void.fromPartial(object.allWeek)
      : undefined;
    message.weekdays = (object.weekdays !== undefined && object.weekdays !== null)
      ? Void.fromPartial(object.weekdays)
      : undefined;
    return message;
  },
};

function createBaseOffPeakChargingTimes(): OffPeakChargingTimes {
  return { allWeek: undefined, weekdays: undefined };
}

export const OffPeakChargingTimes: MessageFns<OffPeakChargingTimes> = {
  encode(message: OffPeakChargingTimes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.allWeek !== undefined) {
      Void.encode(message.allWeek, writer.uint32(10).fork()).join();
    }
    if (message.weekdays !== undefined) {
      Void.encode(message.weekdays, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OffPeakChargingTimes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOffPeakChargingTimes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.allWeek = Void.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.weekdays = Void.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OffPeakChargingTimes {
    return {
      allWeek: isSet(object.allWeek) ? Void.fromJSON(object.allWeek) : undefined,
      weekdays: isSet(object.weekdays) ? Void.fromJSON(object.weekdays) : undefined,
    };
  },

  toJSON(message: OffPeakChargingTimes): unknown {
    const obj: any = {};
    if (message.allWeek !== undefined) {
      obj.allWeek = Void.toJSON(message.allWeek);
    }
    if (message.weekdays !== undefined) {
      obj.weekdays = Void.toJSON(message.weekdays);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OffPeakChargingTimes>, I>>(base?: I): OffPeakChargingTimes {
    return OffPeakChargingTimes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OffPeakChargingTimes>, I>>(object: I): OffPeakChargingTimes {
    const message = createBaseOffPeakChargingTimes();
    message.allWeek = (object.allWeek !== undefined && object.allWeek !== null)
      ? Void.fromPartial(object.allWeek)
      : undefined;
    message.weekdays = (object.weekdays !== undefined && object.weekdays !== null)
      ? Void.fromPartial(object.weekdays)
      : undefined;
    return message;
  },
};

function createBaseChargeSchedule(): ChargeSchedule {
  return {
    id: 0,
    name: "",
    daysOfWeek: 0,
    startEnabled: false,
    startTime: 0,
    endEnabled: false,
    endTime: 0,
    oneTime: false,
    enabled: false,
    latitude: 0,
    longitude: 0,
  };
}

export const ChargeSchedule: MessageFns<ChargeSchedule> = {
  encode(message: ChargeSchedule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.daysOfWeek !== 0) {
      writer.uint32(24).int32(message.daysOfWeek);
    }
    if (message.startEnabled !== false) {
      writer.uint32(32).bool(message.startEnabled);
    }
    if (message.startTime !== 0) {
      writer.uint32(40).int32(message.startTime);
    }
    if (message.endEnabled !== false) {
      writer.uint32(48).bool(message.endEnabled);
    }
    if (message.endTime !== 0) {
      writer.uint32(56).int32(message.endTime);
    }
    if (message.oneTime !== false) {
      writer.uint32(64).bool(message.oneTime);
    }
    if (message.enabled !== false) {
      writer.uint32(72).bool(message.enabled);
    }
    if (message.latitude !== 0) {
      writer.uint32(85).float(message.latitude);
    }
    if (message.longitude !== 0) {
      writer.uint32(93).float(message.longitude);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChargeSchedule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChargeSchedule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.daysOfWeek = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.startEnabled = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.startTime = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.endEnabled = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.endTime = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.oneTime = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 85) {
            break;
          }

          message.latitude = reader.float();
          continue;
        }
        case 11: {
          if (tag !== 93) {
            break;
          }

          message.longitude = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChargeSchedule {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      daysOfWeek: isSet(object.daysOfWeek) ? globalThis.Number(object.daysOfWeek) : 0,
      startEnabled: isSet(object.startEnabled) ? globalThis.Boolean(object.startEnabled) : false,
      startTime: isSet(object.startTime) ? globalThis.Number(object.startTime) : 0,
      endEnabled: isSet(object.endEnabled) ? globalThis.Boolean(object.endEnabled) : false,
      endTime: isSet(object.endTime) ? globalThis.Number(object.endTime) : 0,
      oneTime: isSet(object.oneTime) ? globalThis.Boolean(object.oneTime) : false,
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
      latitude: isSet(object.latitude) ? globalThis.Number(object.latitude) : 0,
      longitude: isSet(object.longitude) ? globalThis.Number(object.longitude) : 0,
    };
  },

  toJSON(message: ChargeSchedule): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.daysOfWeek !== undefined) {
      obj.daysOfWeek = Math.round(message.daysOfWeek);
    }
    if (message.startEnabled !== undefined) {
      obj.startEnabled = message.startEnabled;
    }
    if (message.startTime !== undefined) {
      obj.startTime = Math.round(message.startTime);
    }
    if (message.endEnabled !== undefined) {
      obj.endEnabled = message.endEnabled;
    }
    if (message.endTime !== undefined) {
      obj.endTime = Math.round(message.endTime);
    }
    if (message.oneTime !== undefined) {
      obj.oneTime = message.oneTime;
    }
    if (message.enabled !== undefined) {
      obj.enabled = message.enabled;
    }
    if (message.latitude !== undefined) {
      obj.latitude = message.latitude;
    }
    if (message.longitude !== undefined) {
      obj.longitude = message.longitude;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChargeSchedule>, I>>(base?: I): ChargeSchedule {
    return ChargeSchedule.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChargeSchedule>, I>>(object: I): ChargeSchedule {
    const message = createBaseChargeSchedule();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.daysOfWeek = object.daysOfWeek ?? 0;
    message.startEnabled = object.startEnabled ?? false;
    message.startTime = object.startTime ?? 0;
    message.endEnabled = object.endEnabled ?? false;
    message.endTime = object.endTime ?? 0;
    message.oneTime = object.oneTime ?? false;
    message.enabled = object.enabled ?? false;
    message.latitude = object.latitude ?? 0;
    message.longitude = object.longitude ?? 0;
    return message;
  },
};

function createBasePreconditionSchedule(): PreconditionSchedule {
  return {
    id: 0,
    name: "",
    daysOfWeek: 0,
    preconditionTime: 0,
    oneTime: false,
    enabled: false,
    latitude: 0,
    longitude: 0,
  };
}

export const PreconditionSchedule: MessageFns<PreconditionSchedule> = {
  encode(message: PreconditionSchedule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.daysOfWeek !== 0) {
      writer.uint32(24).int32(message.daysOfWeek);
    }
    if (message.preconditionTime !== 0) {
      writer.uint32(32).int32(message.preconditionTime);
    }
    if (message.oneTime !== false) {
      writer.uint32(40).bool(message.oneTime);
    }
    if (message.enabled !== false) {
      writer.uint32(48).bool(message.enabled);
    }
    if (message.latitude !== 0) {
      writer.uint32(61).float(message.latitude);
    }
    if (message.longitude !== 0) {
      writer.uint32(69).float(message.longitude);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PreconditionSchedule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePreconditionSchedule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.daysOfWeek = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.preconditionTime = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.oneTime = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 61) {
            break;
          }

          message.latitude = reader.float();
          continue;
        }
        case 8: {
          if (tag !== 69) {
            break;
          }

          message.longitude = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PreconditionSchedule {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      daysOfWeek: isSet(object.daysOfWeek) ? globalThis.Number(object.daysOfWeek) : 0,
      preconditionTime: isSet(object.preconditionTime) ? globalThis.Number(object.preconditionTime) : 0,
      oneTime: isSet(object.oneTime) ? globalThis.Boolean(object.oneTime) : false,
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
      latitude: isSet(object.latitude) ? globalThis.Number(object.latitude) : 0,
      longitude: isSet(object.longitude) ? globalThis.Number(object.longitude) : 0,
    };
  },

  toJSON(message: PreconditionSchedule): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.daysOfWeek !== undefined) {
      obj.daysOfWeek = Math.round(message.daysOfWeek);
    }
    if (message.preconditionTime !== undefined) {
      obj.preconditionTime = Math.round(message.preconditionTime);
    }
    if (message.oneTime !== undefined) {
      obj.oneTime = message.oneTime;
    }
    if (message.enabled !== undefined) {
      obj.enabled = message.enabled;
    }
    if (message.latitude !== undefined) {
      obj.latitude = message.latitude;
    }
    if (message.longitude !== undefined) {
      obj.longitude = message.longitude;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PreconditionSchedule>, I>>(base?: I): PreconditionSchedule {
    return PreconditionSchedule.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PreconditionSchedule>, I>>(object: I): PreconditionSchedule {
    const message = createBasePreconditionSchedule();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.daysOfWeek = object.daysOfWeek ?? 0;
    message.preconditionTime = object.preconditionTime ?? 0;
    message.oneTime = object.oneTime ?? false;
    message.enabled = object.enabled ?? false;
    message.latitude = object.latitude ?? 0;
    message.longitude = object.longitude ?? 0;
    return message;
  },
};

function createBaseChargingAlert(): ChargingAlert {
  return { alertName: 0, alertType: 0 };
}

export const ChargingAlert: MessageFns<ChargingAlert> = {
  encode(message: ChargingAlert, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.alertName !== 0) {
      writer.uint32(8).int32(message.alertName);
    }
    if (message.alertType !== 0) {
      writer.uint32(16).int32(message.alertType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChargingAlert {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChargingAlert();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.alertName = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.alertType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChargingAlert {
    return {
      alertName: isSet(object.alertName) ? chargingAlertNameFromJSON(object.alertName) : 0,
      alertType: isSet(object.alertType) ? chargingAlertTypeFromJSON(object.alertType) : 0,
    };
  },

  toJSON(message: ChargingAlert): unknown {
    const obj: any = {};
    if (message.alertName !== undefined) {
      obj.alertName = chargingAlertNameToJSON(message.alertName);
    }
    if (message.alertType !== undefined) {
      obj.alertType = chargingAlertTypeToJSON(message.alertType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChargingAlert>, I>>(base?: I): ChargingAlert {
    return ChargingAlert.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChargingAlert>, I>>(object: I): ChargingAlert {
    const message = createBaseChargingAlert();
    message.alertName = object.alertName ?? 0;
    message.alertType = object.alertType ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
