syntax = "proto3";

package tesla.proto.energy_device.v1;

option go_package = "github.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1";
option java_package = "com.tesla.generated.energy_device.v1";
option java_outer_classname = "EnergySiteNet";

import "device.proto";
import "networking.proto";

enum EnergySiteNetAdditionStatus {
  ENERGY_SITE_NET_ADDITION_STATUS_INVALID                  = 0;
  ENERGY_SITE_NET_ADDITION_STATUS_IN_PROGRESS              = 1;
  ENERGY_SITE_NET_ADDITION_STATUS_ADDED                    = 2;
  ENERGY_SITE_NET_ADDITION_STATUS_FAILED_NOT_FOUND         = 3;
  ENERGY_SITE_NET_ADDITION_STATUS_FAILED_CANNOT_JOIN       = 4;
  ENERGY_SITE_NET_ADDITION_STATUS_FAILED_NO_RESPONSE       = 5;
  ENERGY_SITE_NET_ADDITION_STATUS_FAILED_BAD_RESPONSE      = 6;
  ENERGY_SITE_NET_ADDITION_STATUS_FAILED_INTERNAL_ERROR    = 7;
  ENERGY_SITE_NET_ADDITION_STATUS_FAILED_CHANGES_PROHIBITED = 8;
  ENERGY_SITE_NET_ADDITION_STATUS_FAILED_MAX_DEVICES       = 9;
  ENERGY_SITE_NET_ADDITION_STATUS_FAILED_NOT_LEADER        = 10;
  ENERGY_SITE_NET_ADDITION_STATUS_FAILED_EXISTS            = 11;
  ENERGY_SITE_NET_ADDITION_STATUS_FAILED_PROOF_OF_PRESENCE = 12;
}

enum EnergySiteNetNetworkType {
  ENERGY_SITE_NET_NETWORK_TYPE_INVALID        = 0;
  ENERGY_SITE_NET_NETWORK_TYPE_POWERWALL3     = 1;
  ENERGY_SITE_NET_NETWORK_TYPE_SMART_CHARGING = 2;
  ENERGY_SITE_NET_NETWORK_TYPE_LOAD_SHARING   = 3;
}

enum EnergySiteNetPairStatus {
  ENERGY_SITE_NET_PAIR_STATUS_INVALID                    = 0;
  ENERGY_SITE_NET_PAIR_STATUS_PENDING                    = 1;
  ENERGY_SITE_NET_PAIR_STATUS_FAILED_INTERNAL_ERROR      = 2;
  ENERGY_SITE_NET_PAIR_STATUS_PROOF_OF_PRESENCE_TIMEOUT  = 3;
}

enum EnergySiteNetRemovalStatus {
  ENERGY_SITE_NET_REMOVAL_STATUS_INVALID                  = 0;
  ENERGY_SITE_NET_REMOVAL_STATUS_IN_PROGRESS              = 1;
  ENERGY_SITE_NET_REMOVAL_STATUS_REMOVED                  = 2;
  ENERGY_SITE_NET_REMOVAL_STATUS_FAILED_NO_SUCH_DEVICE    = 3;
  ENERGY_SITE_NET_REMOVAL_STATUS_FAILED_INTERNAL_ERROR    = 4;
  ENERGY_SITE_NET_REMOVAL_STATUS_FAILED_CHANGES_PROHIBITED = 5;
  ENERGY_SITE_NET_REMOVAL_STATUS_FAILED_AM_LEADER         = 6;
  ENERGY_SITE_NET_REMOVAL_STATUS_FAILED_AM_SOLO           = 7;
  ENERGY_SITE_NET_REMOVAL_STATUS_FAILED_NOT_LEADER        = 8;
  ENERGY_SITE_NET_REMOVAL_STATUS_FAILED_LEADER_AVAILABLE  = 9;
}

enum IntraSiteServiceType {
  INTRA_SITE_SERVICE_TYPE_INVALID                  = 0;
  INTRA_SITE_SERVICE_TYPE_MULTI_PW3_FOLLOWER       = 1;
  INTRA_SITE_SERVICE_TYPE_WC_LOAD_SHARING_FOLLOWER = 2;
  INTRA_SITE_SERVICE_TYPE_WC_CURRENT_CONTROL       = 3;
}

message EnergySiteNetDevice {
  Din din                                     = 1;
  WifiConfig wifi_ap_config                   = 2;
  repeated IntraSiteServiceType service_types = 3;
}

message EnergySiteNetRecentlyAddedDevice {
  Din din                            = 1;
  EnergySiteNetAdditionStatus status = 2;
}

message EnergySiteNetRecentlyRemovedDevice {
  Din din                           = 1;
  EnergySiteNetRemovalStatus status = 2;
}

message EnergySiteNetUnpairedDevice {
  Din din                             = 1;
  EnergySiteNetPairStatus pair_status = 2;
  string firmware_version             = 3;
  DeviceType device_type              = 4;
  TEGDeviceType teg_device_type       = 100;
}

message EnergySiteNetConfig {
  repeated EnergySiteNetDevice devices                  = 1;
  EnergySiteNetRecentlyAddedDevice recently_added       = 2;
  EnergySiteNetRecentlyRemovedDevice recently_removed   = 3;
  repeated EnergySiteNetUnpairedDevice unpaired_devices = 4;
}

message EnergySiteNetAPIAddDeviceRequest {
  EnergySiteNetDevice device            = 1;
  EnergySiteNetNetworkType network_type = 2;
}

message EnergySiteNetAPIAddDeviceResponse {
  EnergySiteNetRecentlyAddedDevice recently_added = 1;
}

message EnergySiteNetAPIRemoveDeviceRequest {
  Din din                               = 1;
  EnergySiteNetNetworkType network_type = 2;
  IntraSiteServiceType service_type     = 3;
}

message EnergySiteNetAPIRemoveDeviceResponse {
  EnergySiteNetRecentlyRemovedDevice recently_removed = 1;
}

message EnergySiteNetAPIGetConfigRequest {
  EnergySiteNetNetworkType network_type = 1;
}

message EnergySiteNetAPIGetConfigResponse {
  EnergySiteNetConfig config            = 1;
  EnergySiteNetNetworkType network_type = 2;
}

message EnergySiteNetMessages {
  oneof message {
    EnergySiteNetAPIAddDeviceRequest add_device_request       = 1;
    EnergySiteNetAPIAddDeviceResponse add_device_response     = 2;
    EnergySiteNetAPIRemoveDeviceRequest remove_device_request = 3;
    EnergySiteNetAPIRemoveDeviceResponse remove_device_response = 4;
    EnergySiteNetAPIGetConfigRequest get_config_request       = 5;
    EnergySiteNetAPIGetConfigResponse get_config_response     = 6;
  }
}
