// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.31.1
// source: local_auth_api.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { WifiPassword } from "./networking.js";

export const protobufPackage = "tesla.proto.energy_device.v1";

export enum LocalAuthResult {
  LOCAL_AUTH_RESULT_INVALID = 0,
  LOCAL_AUTH_RESULT_SUCCESS = 1,
  LOCAL_AUTH_RESULT_INVALID_PARAMETERS = 2,
  LOCAL_AUTH_RESULT_INVALID_PASSWORD = 3,
  LOCAL_AUTH_RESULT_PRESENCE_PROOF_REQUIRED = 4,
  LOCAL_AUTH_RESULT_PRESENCE_PROOF_TIMED_OUT = 5,
  UNRECOGNIZED = -1,
}

export function localAuthResultFromJSON(object: any): LocalAuthResult {
  switch (object) {
    case 0:
    case "LOCAL_AUTH_RESULT_INVALID":
      return LocalAuthResult.LOCAL_AUTH_RESULT_INVALID;
    case 1:
    case "LOCAL_AUTH_RESULT_SUCCESS":
      return LocalAuthResult.LOCAL_AUTH_RESULT_SUCCESS;
    case 2:
    case "LOCAL_AUTH_RESULT_INVALID_PARAMETERS":
      return LocalAuthResult.LOCAL_AUTH_RESULT_INVALID_PARAMETERS;
    case 3:
    case "LOCAL_AUTH_RESULT_INVALID_PASSWORD":
      return LocalAuthResult.LOCAL_AUTH_RESULT_INVALID_PASSWORD;
    case 4:
    case "LOCAL_AUTH_RESULT_PRESENCE_PROOF_REQUIRED":
      return LocalAuthResult.LOCAL_AUTH_RESULT_PRESENCE_PROOF_REQUIRED;
    case 5:
    case "LOCAL_AUTH_RESULT_PRESENCE_PROOF_TIMED_OUT":
      return LocalAuthResult.LOCAL_AUTH_RESULT_PRESENCE_PROOF_TIMED_OUT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return LocalAuthResult.UNRECOGNIZED;
  }
}

export function localAuthResultToJSON(object: LocalAuthResult): string {
  switch (object) {
    case LocalAuthResult.LOCAL_AUTH_RESULT_INVALID:
      return "LOCAL_AUTH_RESULT_INVALID";
    case LocalAuthResult.LOCAL_AUTH_RESULT_SUCCESS:
      return "LOCAL_AUTH_RESULT_SUCCESS";
    case LocalAuthResult.LOCAL_AUTH_RESULT_INVALID_PARAMETERS:
      return "LOCAL_AUTH_RESULT_INVALID_PARAMETERS";
    case LocalAuthResult.LOCAL_AUTH_RESULT_INVALID_PASSWORD:
      return "LOCAL_AUTH_RESULT_INVALID_PASSWORD";
    case LocalAuthResult.LOCAL_AUTH_RESULT_PRESENCE_PROOF_REQUIRED:
      return "LOCAL_AUTH_RESULT_PRESENCE_PROOF_REQUIRED";
    case LocalAuthResult.LOCAL_AUTH_RESULT_PRESENCE_PROOF_TIMED_OUT:
      return "LOCAL_AUTH_RESULT_PRESENCE_PROOF_TIMED_OUT";
    case LocalAuthResult.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface LocalAuthAPIRequiredFactorsRequest {
}

export interface LocalAuthAPIRequiredFactorsResponse {
  password: boolean;
  presence: boolean;
}

export interface LocalAuthAPILoginRequest {
  /** enum-valued; kept scalar to avoid an import cycle */
  participant: number;
  email: string;
  password: WifiPassword | undefined;
}

export interface LocalAuthAPILoginResponse {
  result: LocalAuthResult;
}

export interface LocalAuthAPILogoutRequest {
}

export interface LocalAuthAPILogoutResponse {
}

export interface LocalAuthAPICheckAuthStatusRequest {
}

export interface LocalAuthAPICheckAuthStatusResponse {
  result: LocalAuthResult;
}

export interface LocalAuthMessages {
  requiredFactorsRequest?: LocalAuthAPIRequiredFactorsRequest | undefined;
  requiredFactorsResponse?: LocalAuthAPIRequiredFactorsResponse | undefined;
  loginRequest?: LocalAuthAPILoginRequest | undefined;
  loginResponse?: LocalAuthAPILoginResponse | undefined;
  logoutRequest?: LocalAuthAPILogoutRequest | undefined;
  logoutResponse?: LocalAuthAPILogoutResponse | undefined;
  checkAuthStatusRequest?: LocalAuthAPICheckAuthStatusRequest | undefined;
  checkAuthStatusResponse?: LocalAuthAPICheckAuthStatusResponse | undefined;
}

function createBaseLocalAuthAPIRequiredFactorsRequest(): LocalAuthAPIRequiredFactorsRequest {
  return {};
}

export const LocalAuthAPIRequiredFactorsRequest: MessageFns<LocalAuthAPIRequiredFactorsRequest> = {
  encode(_: LocalAuthAPIRequiredFactorsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LocalAuthAPIRequiredFactorsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLocalAuthAPIRequiredFactorsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): LocalAuthAPIRequiredFactorsRequest {
    return {};
  },

  toJSON(_: LocalAuthAPIRequiredFactorsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<LocalAuthAPIRequiredFactorsRequest>, I>>(
    base?: I,
  ): LocalAuthAPIRequiredFactorsRequest {
    return LocalAuthAPIRequiredFactorsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LocalAuthAPIRequiredFactorsRequest>, I>>(
    _: I,
  ): LocalAuthAPIRequiredFactorsRequest {
    const message = createBaseLocalAuthAPIRequiredFactorsRequest();
    return message;
  },
};

function createBaseLocalAuthAPIRequiredFactorsResponse(): LocalAuthAPIRequiredFactorsResponse {
  return { password: false, presence: false };
}

export const LocalAuthAPIRequiredFactorsResponse: MessageFns<LocalAuthAPIRequiredFactorsResponse> = {
  encode(message: LocalAuthAPIRequiredFactorsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.password !== false) {
      writer.uint32(8).bool(message.password);
    }
    if (message.presence !== false) {
      writer.uint32(16).bool(message.presence);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LocalAuthAPIRequiredFactorsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLocalAuthAPIRequiredFactorsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.password = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.presence = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LocalAuthAPIRequiredFactorsResponse {
    return {
      password: isSet(object.password) ? globalThis.Boolean(object.password) : false,
      presence: isSet(object.presence) ? globalThis.Boolean(object.presence) : false,
    };
  },

  toJSON(message: LocalAuthAPIRequiredFactorsResponse): unknown {
    const obj: any = {};
    if (message.password !== undefined) {
      obj.password = message.password;
    }
    if (message.presence !== undefined) {
      obj.presence = message.presence;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LocalAuthAPIRequiredFactorsResponse>, I>>(
    base?: I,
  ): LocalAuthAPIRequiredFactorsResponse {
    return LocalAuthAPIRequiredFactorsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LocalAuthAPIRequiredFactorsResponse>, I>>(
    object: I,
  ): LocalAuthAPIRequiredFactorsResponse {
    const message = createBaseLocalAuthAPIRequiredFactorsResponse();
    message.password = object.password ?? false;
    message.presence = object.presence ?? false;
    return message;
  },
};

function createBaseLocalAuthAPILoginRequest(): LocalAuthAPILoginRequest {
  return { participant: 0, email: "", password: undefined };
}

export const LocalAuthAPILoginRequest: MessageFns<LocalAuthAPILoginRequest> = {
  encode(message: LocalAuthAPILoginRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.participant !== 0) {
      writer.uint32(8).int32(message.participant);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.password !== undefined) {
      WifiPassword.encode(message.password, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LocalAuthAPILoginRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLocalAuthAPILoginRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.participant = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.password = WifiPassword.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LocalAuthAPILoginRequest {
    return {
      participant: isSet(object.participant) ? globalThis.Number(object.participant) : 0,
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      password: isSet(object.password) ? WifiPassword.fromJSON(object.password) : undefined,
    };
  },

  toJSON(message: LocalAuthAPILoginRequest): unknown {
    const obj: any = {};
    if (message.participant !== undefined) {
      obj.participant = Math.round(message.participant);
    }
    if (message.email !== undefined) {
      obj.email = message.email;
    }
    if (message.password !== undefined) {
      obj.password = WifiPassword.toJSON(message.password);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LocalAuthAPILoginRequest>, I>>(base?: I): LocalAuthAPILoginRequest {
    return LocalAuthAPILoginRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LocalAuthAPILoginRequest>, I>>(object: I): LocalAuthAPILoginRequest {
    const message = createBaseLocalAuthAPILoginRequest();
    message.participant = object.participant ?? 0;
    message.email = object.email ?? "";
    message.password = (object.password !== undefined && object.password !== null)
      ? WifiPassword.fromPartial(object.password)
      : undefined;
    return message;
  },
};

function createBaseLocalAuthAPILoginResponse(): LocalAuthAPILoginResponse {
  return { result: 0 };
}

export const LocalAuthAPILoginResponse: MessageFns<LocalAuthAPILoginResponse> = {
  encode(message: LocalAuthAPILoginResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.result !== 0) {
      writer.uint32(8).int32(message.result);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LocalAuthAPILoginResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLocalAuthAPILoginResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.result = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LocalAuthAPILoginResponse {
    return { result: isSet(object.result) ? localAuthResultFromJSON(object.result) : 0 };
  },

  toJSON(message: LocalAuthAPILoginResponse): unknown {
    const obj: any = {};
    if (message.result !== undefined) {
      obj.result = localAuthResultToJSON(message.result);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LocalAuthAPILoginResponse>, I>>(base?: I): LocalAuthAPILoginResponse {
    return LocalAuthAPILoginResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LocalAuthAPILoginResponse>, I>>(object: I): LocalAuthAPILoginResponse {
    const message = createBaseLocalAuthAPILoginResponse();
    message.result = object.result ?? 0;
    return message;
  },
};

function createBaseLocalAuthAPILogoutRequest(): LocalAuthAPILogoutRequest {
  return {};
}

export const LocalAuthAPILogoutRequest: MessageFns<LocalAuthAPILogoutRequest> = {
  encode(_: LocalAuthAPILogoutRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LocalAuthAPILogoutRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLocalAuthAPILogoutRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): LocalAuthAPILogoutRequest {
    return {};
  },

  toJSON(_: LocalAuthAPILogoutRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<LocalAuthAPILogoutRequest>, I>>(base?: I): LocalAuthAPILogoutRequest {
    return LocalAuthAPILogoutRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LocalAuthAPILogoutRequest>, I>>(_: I): LocalAuthAPILogoutRequest {
    const message = createBaseLocalAuthAPILogoutRequest();
    return message;
  },
};

function createBaseLocalAuthAPILogoutResponse(): LocalAuthAPILogoutResponse {
  return {};
}

export const LocalAuthAPILogoutResponse: MessageFns<LocalAuthAPILogoutResponse> = {
  encode(_: LocalAuthAPILogoutResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LocalAuthAPILogoutResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLocalAuthAPILogoutResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): LocalAuthAPILogoutResponse {
    return {};
  },

  toJSON(_: LocalAuthAPILogoutResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<LocalAuthAPILogoutResponse>, I>>(base?: I): LocalAuthAPILogoutResponse {
    return LocalAuthAPILogoutResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LocalAuthAPILogoutResponse>, I>>(_: I): LocalAuthAPILogoutResponse {
    const message = createBaseLocalAuthAPILogoutResponse();
    return message;
  },
};

function createBaseLocalAuthAPICheckAuthStatusRequest(): LocalAuthAPICheckAuthStatusRequest {
  return {};
}

export const LocalAuthAPICheckAuthStatusRequest: MessageFns<LocalAuthAPICheckAuthStatusRequest> = {
  encode(_: LocalAuthAPICheckAuthStatusRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LocalAuthAPICheckAuthStatusRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLocalAuthAPICheckAuthStatusRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): LocalAuthAPICheckAuthStatusRequest {
    return {};
  },

  toJSON(_: LocalAuthAPICheckAuthStatusRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<LocalAuthAPICheckAuthStatusRequest>, I>>(
    base?: I,
  ): LocalAuthAPICheckAuthStatusRequest {
    return LocalAuthAPICheckAuthStatusRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LocalAuthAPICheckAuthStatusRequest>, I>>(
    _: I,
  ): LocalAuthAPICheckAuthStatusRequest {
    const message = createBaseLocalAuthAPICheckAuthStatusRequest();
    return message;
  },
};

function createBaseLocalAuthAPICheckAuthStatusResponse(): LocalAuthAPICheckAuthStatusResponse {
  return { result: 0 };
}

export const LocalAuthAPICheckAuthStatusResponse: MessageFns<LocalAuthAPICheckAuthStatusResponse> = {
  encode(message: LocalAuthAPICheckAuthStatusResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.result !== 0) {
      writer.uint32(8).int32(message.result);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LocalAuthAPICheckAuthStatusResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLocalAuthAPICheckAuthStatusResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.result = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LocalAuthAPICheckAuthStatusResponse {
    return { result: isSet(object.result) ? localAuthResultFromJSON(object.result) : 0 };
  },

  toJSON(message: LocalAuthAPICheckAuthStatusResponse): unknown {
    const obj: any = {};
    if (message.result !== undefined) {
      obj.result = localAuthResultToJSON(message.result);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LocalAuthAPICheckAuthStatusResponse>, I>>(
    base?: I,
  ): LocalAuthAPICheckAuthStatusResponse {
    return LocalAuthAPICheckAuthStatusResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LocalAuthAPICheckAuthStatusResponse>, I>>(
    object: I,
  ): LocalAuthAPICheckAuthStatusResponse {
    const message = createBaseLocalAuthAPICheckAuthStatusResponse();
    message.result = object.result ?? 0;
    return message;
  },
};

function createBaseLocalAuthMessages(): LocalAuthMessages {
  return {
    requiredFactorsRequest: undefined,
    requiredFactorsResponse: undefined,
    loginRequest: undefined,
    loginResponse: undefined,
    logoutRequest: undefined,
    logoutResponse: undefined,
    checkAuthStatusRequest: undefined,
    checkAuthStatusResponse: undefined,
  };
}

export const LocalAuthMessages: MessageFns<LocalAuthMessages> = {
  encode(message: LocalAuthMessages, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requiredFactorsRequest !== undefined) {
      LocalAuthAPIRequiredFactorsRequest.encode(message.requiredFactorsRequest, writer.uint32(10).fork()).join();
    }
    if (message.requiredFactorsResponse !== undefined) {
      LocalAuthAPIRequiredFactorsResponse.encode(message.requiredFactorsResponse, writer.uint32(18).fork()).join();
    }
    if (message.loginRequest !== undefined) {
      LocalAuthAPILoginRequest.encode(message.loginRequest, writer.uint32(26).fork()).join();
    }
    if (message.loginResponse !== undefined) {
      LocalAuthAPILoginResponse.encode(message.loginResponse, writer.uint32(34).fork()).join();
    }
    if (message.logoutRequest !== undefined) {
      LocalAuthAPILogoutRequest.encode(message.logoutRequest, writer.uint32(42).fork()).join();
    }
    if (message.logoutResponse !== undefined) {
      LocalAuthAPILogoutResponse.encode(message.logoutResponse, writer.uint32(50).fork()).join();
    }
    if (message.checkAuthStatusRequest !== undefined) {
      LocalAuthAPICheckAuthStatusRequest.encode(message.checkAuthStatusRequest, writer.uint32(58).fork()).join();
    }
    if (message.checkAuthStatusResponse !== undefined) {
      LocalAuthAPICheckAuthStatusResponse.encode(message.checkAuthStatusResponse, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LocalAuthMessages {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLocalAuthMessages();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requiredFactorsRequest = LocalAuthAPIRequiredFactorsRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.requiredFactorsResponse = LocalAuthAPIRequiredFactorsResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.loginRequest = LocalAuthAPILoginRequest.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.loginResponse = LocalAuthAPILoginResponse.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.logoutRequest = LocalAuthAPILogoutRequest.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.logoutResponse = LocalAuthAPILogoutResponse.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.checkAuthStatusRequest = LocalAuthAPICheckAuthStatusRequest.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.checkAuthStatusResponse = LocalAuthAPICheckAuthStatusResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LocalAuthMessages {
    return {
      requiredFactorsRequest: isSet(object.requiredFactorsRequest)
        ? LocalAuthAPIRequiredFactorsRequest.fromJSON(object.requiredFactorsRequest)
        : undefined,
      requiredFactorsResponse: isSet(object.requiredFactorsResponse)
        ? LocalAuthAPIRequiredFactorsResponse.fromJSON(object.requiredFactorsResponse)
        : undefined,
      loginRequest: isSet(object.loginRequest) ? LocalAuthAPILoginRequest.fromJSON(object.loginRequest) : undefined,
      loginResponse: isSet(object.loginResponse) ? LocalAuthAPILoginResponse.fromJSON(object.loginResponse) : undefined,
      logoutRequest: isSet(object.logoutRequest) ? LocalAuthAPILogoutRequest.fromJSON(object.logoutRequest) : undefined,
      logoutResponse: isSet(object.logoutResponse)
        ? LocalAuthAPILogoutResponse.fromJSON(object.logoutResponse)
        : undefined,
      checkAuthStatusRequest: isSet(object.checkAuthStatusRequest)
        ? LocalAuthAPICheckAuthStatusRequest.fromJSON(object.checkAuthStatusRequest)
        : undefined,
      checkAuthStatusResponse: isSet(object.checkAuthStatusResponse)
        ? LocalAuthAPICheckAuthStatusResponse.fromJSON(object.checkAuthStatusResponse)
        : undefined,
    };
  },

  toJSON(message: LocalAuthMessages): unknown {
    const obj: any = {};
    if (message.requiredFactorsRequest !== undefined) {
      obj.requiredFactorsRequest = LocalAuthAPIRequiredFactorsRequest.toJSON(message.requiredFactorsRequest);
    }
    if (message.requiredFactorsResponse !== undefined) {
      obj.requiredFactorsResponse = LocalAuthAPIRequiredFactorsResponse.toJSON(message.requiredFactorsResponse);
    }
    if (message.loginRequest !== undefined) {
      obj.loginRequest = LocalAuthAPILoginRequest.toJSON(message.loginRequest);
    }
    if (message.loginResponse !== undefined) {
      obj.loginResponse = LocalAuthAPILoginResponse.toJSON(message.loginResponse);
    }
    if (message.logoutRequest !== undefined) {
      obj.logoutRequest = LocalAuthAPILogoutRequest.toJSON(message.logoutRequest);
    }
    if (message.logoutResponse !== undefined) {
      obj.logoutResponse = LocalAuthAPILogoutResponse.toJSON(message.logoutResponse);
    }
    if (message.checkAuthStatusRequest !== undefined) {
      obj.checkAuthStatusRequest = LocalAuthAPICheckAuthStatusRequest.toJSON(message.checkAuthStatusRequest);
    }
    if (message.checkAuthStatusResponse !== undefined) {
      obj.checkAuthStatusResponse = LocalAuthAPICheckAuthStatusResponse.toJSON(message.checkAuthStatusResponse);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LocalAuthMessages>, I>>(base?: I): LocalAuthMessages {
    return LocalAuthMessages.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LocalAuthMessages>, I>>(object: I): LocalAuthMessages {
    const message = createBaseLocalAuthMessages();
    message.requiredFactorsRequest =
      (object.requiredFactorsRequest !== undefined && object.requiredFactorsRequest !== null)
        ? LocalAuthAPIRequiredFactorsRequest.fromPartial(object.requiredFactorsRequest)
        : undefined;
    message.requiredFactorsResponse =
      (object.requiredFactorsResponse !== undefined && object.requiredFactorsResponse !== null)
        ? LocalAuthAPIRequiredFactorsResponse.fromPartial(object.requiredFactorsResponse)
        : undefined;
    message.loginRequest = (object.loginRequest !== undefined && object.loginRequest !== null)
      ? LocalAuthAPILoginRequest.fromPartial(object.loginRequest)
      : undefined;
    message.loginResponse = (object.loginResponse !== undefined && object.loginResponse !== null)
      ? LocalAuthAPILoginResponse.fromPartial(object.loginResponse)
      : undefined;
    message.logoutRequest = (object.logoutRequest !== undefined && object.logoutRequest !== null)
      ? LocalAuthAPILogoutRequest.fromPartial(object.logoutRequest)
      : undefined;
    message.logoutResponse = (object.logoutResponse !== undefined && object.logoutResponse !== null)
      ? LocalAuthAPILogoutResponse.fromPartial(object.logoutResponse)
      : undefined;
    message.checkAuthStatusRequest =
      (object.checkAuthStatusRequest !== undefined && object.checkAuthStatusRequest !== null)
        ? LocalAuthAPICheckAuthStatusRequest.fromPartial(object.checkAuthStatusRequest)
        : undefined;
    message.checkAuthStatusResponse =
      (object.checkAuthStatusResponse !== undefined && object.checkAuthStatusResponse !== null)
        ? LocalAuthAPICheckAuthStatusResponse.fromPartial(object.checkAuthStatusResponse)
        : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
