// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.31.1
// source: networking.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Int32Value, UInt32Value } from "./google/protobuf/wrappers.js";

export const protobufPackage = "tesla.proto.energy_device.v1";

/**
 * TESLEMETRY SOURCE-OF-RECORD - no upstream.
 * Provenance: Tesla Energy gateway (TEG) local API, from our own
 * observations and contributions from the community
 */

export enum WifiNetworkSecurityType {
  WIFI_NETWORK_SECURITY_TYPE_INVALID = 0,
  WIFI_NETWORK_SECURITY_TYPE_NONE = 1,
  WIFI_NETWORK_SECURITY_TYPE_DYNAMIC_WEP = 2,
  WIFI_NETWORK_SECURITY_TYPE_WPA2_PERSONAL = 3,
  WIFI_NETWORK_SECURITY_TYPE_WPA2_ENTERPRISE = 4,
  UNRECOGNIZED = -1,
}

export function wifiNetworkSecurityTypeFromJSON(object: any): WifiNetworkSecurityType {
  switch (object) {
    case 0:
    case "WIFI_NETWORK_SECURITY_TYPE_INVALID":
      return WifiNetworkSecurityType.WIFI_NETWORK_SECURITY_TYPE_INVALID;
    case 1:
    case "WIFI_NETWORK_SECURITY_TYPE_NONE":
      return WifiNetworkSecurityType.WIFI_NETWORK_SECURITY_TYPE_NONE;
    case 2:
    case "WIFI_NETWORK_SECURITY_TYPE_DYNAMIC_WEP":
      return WifiNetworkSecurityType.WIFI_NETWORK_SECURITY_TYPE_DYNAMIC_WEP;
    case 3:
    case "WIFI_NETWORK_SECURITY_TYPE_WPA2_PERSONAL":
      return WifiNetworkSecurityType.WIFI_NETWORK_SECURITY_TYPE_WPA2_PERSONAL;
    case 4:
    case "WIFI_NETWORK_SECURITY_TYPE_WPA2_ENTERPRISE":
      return WifiNetworkSecurityType.WIFI_NETWORK_SECURITY_TYPE_WPA2_ENTERPRISE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return WifiNetworkSecurityType.UNRECOGNIZED;
  }
}

export function wifiNetworkSecurityTypeToJSON(object: WifiNetworkSecurityType): string {
  switch (object) {
    case WifiNetworkSecurityType.WIFI_NETWORK_SECURITY_TYPE_INVALID:
      return "WIFI_NETWORK_SECURITY_TYPE_INVALID";
    case WifiNetworkSecurityType.WIFI_NETWORK_SECURITY_TYPE_NONE:
      return "WIFI_NETWORK_SECURITY_TYPE_NONE";
    case WifiNetworkSecurityType.WIFI_NETWORK_SECURITY_TYPE_DYNAMIC_WEP:
      return "WIFI_NETWORK_SECURITY_TYPE_DYNAMIC_WEP";
    case WifiNetworkSecurityType.WIFI_NETWORK_SECURITY_TYPE_WPA2_PERSONAL:
      return "WIFI_NETWORK_SECURITY_TYPE_WPA2_PERSONAL";
    case WifiNetworkSecurityType.WIFI_NETWORK_SECURITY_TYPE_WPA2_ENTERPRISE:
      return "WIFI_NETWORK_SECURITY_TYPE_WPA2_ENTERPRISE";
    case WifiNetworkSecurityType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum WifiConfigureResult {
  WIFI_CONFIGURE_RESULT_INVALID = 0,
  WIFI_CONFIGURE_RESULT_SUCCESS = 1,
  WIFI_CONFIGURE_RESULT_FAILURE_GENERIC = 2,
  WIFI_CONFIGURE_RESULT_FAILED_WITH_INVALID_CONFIG = 3,
  WIFI_CONFIGURE_RESULT_FAILED_TO_CONNECT = 4,
  UNRECOGNIZED = -1,
}

export function wifiConfigureResultFromJSON(object: any): WifiConfigureResult {
  switch (object) {
    case 0:
    case "WIFI_CONFIGURE_RESULT_INVALID":
      return WifiConfigureResult.WIFI_CONFIGURE_RESULT_INVALID;
    case 1:
    case "WIFI_CONFIGURE_RESULT_SUCCESS":
      return WifiConfigureResult.WIFI_CONFIGURE_RESULT_SUCCESS;
    case 2:
    case "WIFI_CONFIGURE_RESULT_FAILURE_GENERIC":
      return WifiConfigureResult.WIFI_CONFIGURE_RESULT_FAILURE_GENERIC;
    case 3:
    case "WIFI_CONFIGURE_RESULT_FAILED_WITH_INVALID_CONFIG":
      return WifiConfigureResult.WIFI_CONFIGURE_RESULT_FAILED_WITH_INVALID_CONFIG;
    case 4:
    case "WIFI_CONFIGURE_RESULT_FAILED_TO_CONNECT":
      return WifiConfigureResult.WIFI_CONFIGURE_RESULT_FAILED_TO_CONNECT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return WifiConfigureResult.UNRECOGNIZED;
  }
}

export function wifiConfigureResultToJSON(object: WifiConfigureResult): string {
  switch (object) {
    case WifiConfigureResult.WIFI_CONFIGURE_RESULT_INVALID:
      return "WIFI_CONFIGURE_RESULT_INVALID";
    case WifiConfigureResult.WIFI_CONFIGURE_RESULT_SUCCESS:
      return "WIFI_CONFIGURE_RESULT_SUCCESS";
    case WifiConfigureResult.WIFI_CONFIGURE_RESULT_FAILURE_GENERIC:
      return "WIFI_CONFIGURE_RESULT_FAILURE_GENERIC";
    case WifiConfigureResult.WIFI_CONFIGURE_RESULT_FAILED_WITH_INVALID_CONFIG:
      return "WIFI_CONFIGURE_RESULT_FAILED_WITH_INVALID_CONFIG";
    case WifiConfigureResult.WIFI_CONFIGURE_RESULT_FAILED_TO_CONNECT:
      return "WIFI_CONFIGURE_RESULT_FAILED_TO_CONNECT";
    case WifiConfigureResult.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum CellularProfileType {
  CELLULAR_PROFILE_TYPE_INVALID = 0,
  CELLULAR_PROFILE_TYPE_TWILIO = 1,
  CELLULAR_PROFILE_TYPE_ATT = 2,
  CELLULAR_PROFILE_TYPE_KPN = 3,
  CELLULAR_PROFILE_TYPE_TELEFONICA = 4,
  CELLULAR_PROFILE_TYPE_TELSTRA = 5,
  CELLULAR_PROFILE_TYPE_TELUS = 6,
  CELLULAR_PROFILE_TYPE_DOCOMO = 7,
  CELLULAR_PROFILE_TYPE_UNICOM = 8,
  UNRECOGNIZED = -1,
}

export function cellularProfileTypeFromJSON(object: any): CellularProfileType {
  switch (object) {
    case 0:
    case "CELLULAR_PROFILE_TYPE_INVALID":
      return CellularProfileType.CELLULAR_PROFILE_TYPE_INVALID;
    case 1:
    case "CELLULAR_PROFILE_TYPE_TWILIO":
      return CellularProfileType.CELLULAR_PROFILE_TYPE_TWILIO;
    case 2:
    case "CELLULAR_PROFILE_TYPE_ATT":
      return CellularProfileType.CELLULAR_PROFILE_TYPE_ATT;
    case 3:
    case "CELLULAR_PROFILE_TYPE_KPN":
      return CellularProfileType.CELLULAR_PROFILE_TYPE_KPN;
    case 4:
    case "CELLULAR_PROFILE_TYPE_TELEFONICA":
      return CellularProfileType.CELLULAR_PROFILE_TYPE_TELEFONICA;
    case 5:
    case "CELLULAR_PROFILE_TYPE_TELSTRA":
      return CellularProfileType.CELLULAR_PROFILE_TYPE_TELSTRA;
    case 6:
    case "CELLULAR_PROFILE_TYPE_TELUS":
      return CellularProfileType.CELLULAR_PROFILE_TYPE_TELUS;
    case 7:
    case "CELLULAR_PROFILE_TYPE_DOCOMO":
      return CellularProfileType.CELLULAR_PROFILE_TYPE_DOCOMO;
    case 8:
    case "CELLULAR_PROFILE_TYPE_UNICOM":
      return CellularProfileType.CELLULAR_PROFILE_TYPE_UNICOM;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CellularProfileType.UNRECOGNIZED;
  }
}

export function cellularProfileTypeToJSON(object: CellularProfileType): string {
  switch (object) {
    case CellularProfileType.CELLULAR_PROFILE_TYPE_INVALID:
      return "CELLULAR_PROFILE_TYPE_INVALID";
    case CellularProfileType.CELLULAR_PROFILE_TYPE_TWILIO:
      return "CELLULAR_PROFILE_TYPE_TWILIO";
    case CellularProfileType.CELLULAR_PROFILE_TYPE_ATT:
      return "CELLULAR_PROFILE_TYPE_ATT";
    case CellularProfileType.CELLULAR_PROFILE_TYPE_KPN:
      return "CELLULAR_PROFILE_TYPE_KPN";
    case CellularProfileType.CELLULAR_PROFILE_TYPE_TELEFONICA:
      return "CELLULAR_PROFILE_TYPE_TELEFONICA";
    case CellularProfileType.CELLULAR_PROFILE_TYPE_TELSTRA:
      return "CELLULAR_PROFILE_TYPE_TELSTRA";
    case CellularProfileType.CELLULAR_PROFILE_TYPE_TELUS:
      return "CELLULAR_PROFILE_TYPE_TELUS";
    case CellularProfileType.CELLULAR_PROFILE_TYPE_DOCOMO:
      return "CELLULAR_PROFILE_TYPE_DOCOMO";
    case CellularProfileType.CELLULAR_PROFILE_TYPE_UNICOM:
      return "CELLULAR_PROFILE_TYPE_UNICOM";
    case CellularProfileType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum NetworkDeviceState {
  NETWORK_DEVICE_STATE_INVALID = 0,
  NETWORK_DEVICE_STATE_UNMANAGED = 1,
  NETWORK_DEVICE_STATE_UNAVAILABLE = 2,
  NETWORK_DEVICE_STATE_IDLE = 3,
  NETWORK_DEVICE_STATE_ASSOCIATION = 4,
  NETWORK_DEVICE_STATE_CONFIGURATION = 5,
  NETWORK_DEVICE_STATE_READY = 6,
  NETWORK_DEVICE_STATE_DISCONNECT = 7,
  NETWORK_DEVICE_STATE_FAILURE = 8,
  UNRECOGNIZED = -1,
}

export function networkDeviceStateFromJSON(object: any): NetworkDeviceState {
  switch (object) {
    case 0:
    case "NETWORK_DEVICE_STATE_INVALID":
      return NetworkDeviceState.NETWORK_DEVICE_STATE_INVALID;
    case 1:
    case "NETWORK_DEVICE_STATE_UNMANAGED":
      return NetworkDeviceState.NETWORK_DEVICE_STATE_UNMANAGED;
    case 2:
    case "NETWORK_DEVICE_STATE_UNAVAILABLE":
      return NetworkDeviceState.NETWORK_DEVICE_STATE_UNAVAILABLE;
    case 3:
    case "NETWORK_DEVICE_STATE_IDLE":
      return NetworkDeviceState.NETWORK_DEVICE_STATE_IDLE;
    case 4:
    case "NETWORK_DEVICE_STATE_ASSOCIATION":
      return NetworkDeviceState.NETWORK_DEVICE_STATE_ASSOCIATION;
    case 5:
    case "NETWORK_DEVICE_STATE_CONFIGURATION":
      return NetworkDeviceState.NETWORK_DEVICE_STATE_CONFIGURATION;
    case 6:
    case "NETWORK_DEVICE_STATE_READY":
      return NetworkDeviceState.NETWORK_DEVICE_STATE_READY;
    case 7:
    case "NETWORK_DEVICE_STATE_DISCONNECT":
      return NetworkDeviceState.NETWORK_DEVICE_STATE_DISCONNECT;
    case 8:
    case "NETWORK_DEVICE_STATE_FAILURE":
      return NetworkDeviceState.NETWORK_DEVICE_STATE_FAILURE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return NetworkDeviceState.UNRECOGNIZED;
  }
}

export function networkDeviceStateToJSON(object: NetworkDeviceState): string {
  switch (object) {
    case NetworkDeviceState.NETWORK_DEVICE_STATE_INVALID:
      return "NETWORK_DEVICE_STATE_INVALID";
    case NetworkDeviceState.NETWORK_DEVICE_STATE_UNMANAGED:
      return "NETWORK_DEVICE_STATE_UNMANAGED";
    case NetworkDeviceState.NETWORK_DEVICE_STATE_UNAVAILABLE:
      return "NETWORK_DEVICE_STATE_UNAVAILABLE";
    case NetworkDeviceState.NETWORK_DEVICE_STATE_IDLE:
      return "NETWORK_DEVICE_STATE_IDLE";
    case NetworkDeviceState.NETWORK_DEVICE_STATE_ASSOCIATION:
      return "NETWORK_DEVICE_STATE_ASSOCIATION";
    case NetworkDeviceState.NETWORK_DEVICE_STATE_CONFIGURATION:
      return "NETWORK_DEVICE_STATE_CONFIGURATION";
    case NetworkDeviceState.NETWORK_DEVICE_STATE_READY:
      return "NETWORK_DEVICE_STATE_READY";
    case NetworkDeviceState.NETWORK_DEVICE_STATE_DISCONNECT:
      return "NETWORK_DEVICE_STATE_DISCONNECT";
    case NetworkDeviceState.NETWORK_DEVICE_STATE_FAILURE:
      return "NETWORK_DEVICE_STATE_FAILURE";
    case NetworkDeviceState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum NetworkDeviceStateReason {
  NETWORK_DEVICE_STATE_REASON_INVALID = 0,
  NETWORK_DEVICE_STATE_REASON_NONE = 1,
  NETWORK_DEVICE_STATE_REASON_CONFIG_FAILED = 2,
  NETWORK_DEVICE_STATE_REASON_DHCP_FAILED = 3,
  NETWORK_DEVICE_STATE_REASON_IP_ADDRESS_DUPLICATE = 4,
  NETWORK_DEVICE_STATE_REASON_IP_CONFIG_EXPIRED = 5,
  NETWORK_DEVICE_STATE_REASON_IP_CONFIG_UNAVAILABLE = 6,
  NETWORK_DEVICE_STATE_REASON_IP_METHOD_UNSUPPORTED = 7,
  NETWORK_DEVICE_STATE_REASON_NEW_ACTIVATION = 8,
  NETWORK_DEVICE_STATE_REASON_NO_SECRETS = 9,
  NETWORK_DEVICE_STATE_REASON_PPP_FAILED = 10,
  NETWORK_DEVICE_STATE_REASON_SSID_NOT_FOUND = 11,
  NETWORK_DEVICE_STATE_REASON_SIM_PIN_INCORRECT = 12,
  NETWORK_DEVICE_STATE_REASON_SUPPLICANT_FAILED = 13,
  NETWORK_DEVICE_STATE_REASON_REMOVED = 14,
  NETWORK_DEVICE_STATE_REASON_MODEM_FAILED = 15,
  UNRECOGNIZED = -1,
}

export function networkDeviceStateReasonFromJSON(object: any): NetworkDeviceStateReason {
  switch (object) {
    case 0:
    case "NETWORK_DEVICE_STATE_REASON_INVALID":
      return NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_INVALID;
    case 1:
    case "NETWORK_DEVICE_STATE_REASON_NONE":
      return NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_NONE;
    case 2:
    case "NETWORK_DEVICE_STATE_REASON_CONFIG_FAILED":
      return NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_CONFIG_FAILED;
    case 3:
    case "NETWORK_DEVICE_STATE_REASON_DHCP_FAILED":
      return NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_DHCP_FAILED;
    case 4:
    case "NETWORK_DEVICE_STATE_REASON_IP_ADDRESS_DUPLICATE":
      return NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_IP_ADDRESS_DUPLICATE;
    case 5:
    case "NETWORK_DEVICE_STATE_REASON_IP_CONFIG_EXPIRED":
      return NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_IP_CONFIG_EXPIRED;
    case 6:
    case "NETWORK_DEVICE_STATE_REASON_IP_CONFIG_UNAVAILABLE":
      return NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_IP_CONFIG_UNAVAILABLE;
    case 7:
    case "NETWORK_DEVICE_STATE_REASON_IP_METHOD_UNSUPPORTED":
      return NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_IP_METHOD_UNSUPPORTED;
    case 8:
    case "NETWORK_DEVICE_STATE_REASON_NEW_ACTIVATION":
      return NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_NEW_ACTIVATION;
    case 9:
    case "NETWORK_DEVICE_STATE_REASON_NO_SECRETS":
      return NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_NO_SECRETS;
    case 10:
    case "NETWORK_DEVICE_STATE_REASON_PPP_FAILED":
      return NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_PPP_FAILED;
    case 11:
    case "NETWORK_DEVICE_STATE_REASON_SSID_NOT_FOUND":
      return NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_SSID_NOT_FOUND;
    case 12:
    case "NETWORK_DEVICE_STATE_REASON_SIM_PIN_INCORRECT":
      return NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_SIM_PIN_INCORRECT;
    case 13:
    case "NETWORK_DEVICE_STATE_REASON_SUPPLICANT_FAILED":
      return NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_SUPPLICANT_FAILED;
    case 14:
    case "NETWORK_DEVICE_STATE_REASON_REMOVED":
      return NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_REMOVED;
    case 15:
    case "NETWORK_DEVICE_STATE_REASON_MODEM_FAILED":
      return NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_MODEM_FAILED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return NetworkDeviceStateReason.UNRECOGNIZED;
  }
}

export function networkDeviceStateReasonToJSON(object: NetworkDeviceStateReason): string {
  switch (object) {
    case NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_INVALID:
      return "NETWORK_DEVICE_STATE_REASON_INVALID";
    case NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_NONE:
      return "NETWORK_DEVICE_STATE_REASON_NONE";
    case NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_CONFIG_FAILED:
      return "NETWORK_DEVICE_STATE_REASON_CONFIG_FAILED";
    case NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_DHCP_FAILED:
      return "NETWORK_DEVICE_STATE_REASON_DHCP_FAILED";
    case NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_IP_ADDRESS_DUPLICATE:
      return "NETWORK_DEVICE_STATE_REASON_IP_ADDRESS_DUPLICATE";
    case NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_IP_CONFIG_EXPIRED:
      return "NETWORK_DEVICE_STATE_REASON_IP_CONFIG_EXPIRED";
    case NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_IP_CONFIG_UNAVAILABLE:
      return "NETWORK_DEVICE_STATE_REASON_IP_CONFIG_UNAVAILABLE";
    case NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_IP_METHOD_UNSUPPORTED:
      return "NETWORK_DEVICE_STATE_REASON_IP_METHOD_UNSUPPORTED";
    case NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_NEW_ACTIVATION:
      return "NETWORK_DEVICE_STATE_REASON_NEW_ACTIVATION";
    case NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_NO_SECRETS:
      return "NETWORK_DEVICE_STATE_REASON_NO_SECRETS";
    case NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_PPP_FAILED:
      return "NETWORK_DEVICE_STATE_REASON_PPP_FAILED";
    case NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_SSID_NOT_FOUND:
      return "NETWORK_DEVICE_STATE_REASON_SSID_NOT_FOUND";
    case NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_SIM_PIN_INCORRECT:
      return "NETWORK_DEVICE_STATE_REASON_SIM_PIN_INCORRECT";
    case NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_SUPPLICANT_FAILED:
      return "NETWORK_DEVICE_STATE_REASON_SUPPLICANT_FAILED";
    case NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_REMOVED:
      return "NETWORK_DEVICE_STATE_REASON_REMOVED";
    case NetworkDeviceStateReason.NETWORK_DEVICE_STATE_REASON_MODEM_FAILED:
      return "NETWORK_DEVICE_STATE_REASON_MODEM_FAILED";
    case NetworkDeviceStateReason.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Rssi {
  value: number;
  signalStrengthPercent: number | undefined;
}

export interface WifiPassword {
  value: string;
}

export interface WifiConfig {
  ssid: string;
  password: WifiPassword | undefined;
  securityType: WifiNetworkSecurityType;
}

export interface WifiNetwork {
  ssid: string;
  rssiValue: number;
  rssi: Rssi | undefined;
  securityType: WifiNetworkSecurityType;
}

export interface NetworkInterfaceIPv4Config {
  dhcpEnabled: boolean;
  address: number;
  subnetMask: number;
  gateway: number;
  dns: number[];
}

export interface NetworkConnectivityStatus {
  connectedPhysical: boolean;
  connectedInternet: boolean;
  connectedTesla: boolean;
  rssi: Rssi | undefined;
  snr: number | undefined;
}

export interface NetworkInterface {
  macAddress: Uint8Array;
  enabled: boolean;
  activeRoute: boolean;
  ipv4Config: NetworkInterfaceIPv4Config | undefined;
  connectivityStatus: NetworkConnectivityStatus | undefined;
}

export interface CellularEID {
  value: string;
}

function createBaseRssi(): Rssi {
  return { value: 0, signalStrengthPercent: undefined };
}

export const Rssi: MessageFns<Rssi> = {
  encode(message: Rssi, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== 0) {
      writer.uint32(8).sint32(message.value);
    }
    if (message.signalStrengthPercent !== undefined) {
      UInt32Value.encode({ value: message.signalStrengthPercent! }, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Rssi {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRssi();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.value = reader.sint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.signalStrengthPercent = UInt32Value.decode(reader, reader.uint32()).value;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Rssi {
    return {
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
      signalStrengthPercent: isSet(object.signalStrengthPercent) ? Number(object.signalStrengthPercent) : undefined,
    };
  },

  toJSON(message: Rssi): unknown {
    const obj: any = {};
    if (message.value !== undefined) {
      obj.value = Math.round(message.value);
    }
    if (message.signalStrengthPercent !== undefined) {
      obj.signalStrengthPercent = message.signalStrengthPercent;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Rssi>, I>>(base?: I): Rssi {
    return Rssi.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Rssi>, I>>(object: I): Rssi {
    const message = createBaseRssi();
    message.value = object.value ?? 0;
    message.signalStrengthPercent = object.signalStrengthPercent ?? undefined;
    return message;
  },
};

function createBaseWifiPassword(): WifiPassword {
  return { value: "" };
}

export const WifiPassword: MessageFns<WifiPassword> = {
  encode(message: WifiPassword, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== "") {
      writer.uint32(10).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WifiPassword {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWifiPassword();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WifiPassword {
    return { value: isSet(object.value) ? globalThis.String(object.value) : "" };
  },

  toJSON(message: WifiPassword): unknown {
    const obj: any = {};
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WifiPassword>, I>>(base?: I): WifiPassword {
    return WifiPassword.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WifiPassword>, I>>(object: I): WifiPassword {
    const message = createBaseWifiPassword();
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseWifiConfig(): WifiConfig {
  return { ssid: "", password: undefined, securityType: 0 };
}

export const WifiConfig: MessageFns<WifiConfig> = {
  encode(message: WifiConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ssid !== "") {
      writer.uint32(10).string(message.ssid);
    }
    if (message.password !== undefined) {
      WifiPassword.encode(message.password, writer.uint32(18).fork()).join();
    }
    if (message.securityType !== 0) {
      writer.uint32(24).int32(message.securityType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WifiConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWifiConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ssid = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = WifiPassword.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.securityType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WifiConfig {
    return {
      ssid: isSet(object.ssid) ? globalThis.String(object.ssid) : "",
      password: isSet(object.password) ? WifiPassword.fromJSON(object.password) : undefined,
      securityType: isSet(object.securityType) ? wifiNetworkSecurityTypeFromJSON(object.securityType) : 0,
    };
  },

  toJSON(message: WifiConfig): unknown {
    const obj: any = {};
    if (message.ssid !== undefined) {
      obj.ssid = message.ssid;
    }
    if (message.password !== undefined) {
      obj.password = WifiPassword.toJSON(message.password);
    }
    if (message.securityType !== undefined) {
      obj.securityType = wifiNetworkSecurityTypeToJSON(message.securityType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WifiConfig>, I>>(base?: I): WifiConfig {
    return WifiConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WifiConfig>, I>>(object: I): WifiConfig {
    const message = createBaseWifiConfig();
    message.ssid = object.ssid ?? "";
    message.password = (object.password !== undefined && object.password !== null)
      ? WifiPassword.fromPartial(object.password)
      : undefined;
    message.securityType = object.securityType ?? 0;
    return message;
  },
};

function createBaseWifiNetwork(): WifiNetwork {
  return { ssid: "", rssiValue: 0, rssi: undefined, securityType: 0 };
}

export const WifiNetwork: MessageFns<WifiNetwork> = {
  encode(message: WifiNetwork, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ssid !== "") {
      writer.uint32(10).string(message.ssid);
    }
    if (message.rssiValue !== 0) {
      writer.uint32(16).sint32(message.rssiValue);
    }
    if (message.rssi !== undefined) {
      Rssi.encode(message.rssi, writer.uint32(26).fork()).join();
    }
    if (message.securityType !== 0) {
      writer.uint32(32).int32(message.securityType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WifiNetwork {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWifiNetwork();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ssid = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.rssiValue = reader.sint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.rssi = Rssi.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.securityType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WifiNetwork {
    return {
      ssid: isSet(object.ssid) ? globalThis.String(object.ssid) : "",
      rssiValue: isSet(object.rssiValue) ? globalThis.Number(object.rssiValue) : 0,
      rssi: isSet(object.rssi) ? Rssi.fromJSON(object.rssi) : undefined,
      securityType: isSet(object.securityType) ? wifiNetworkSecurityTypeFromJSON(object.securityType) : 0,
    };
  },

  toJSON(message: WifiNetwork): unknown {
    const obj: any = {};
    if (message.ssid !== undefined) {
      obj.ssid = message.ssid;
    }
    if (message.rssiValue !== undefined) {
      obj.rssiValue = Math.round(message.rssiValue);
    }
    if (message.rssi !== undefined) {
      obj.rssi = Rssi.toJSON(message.rssi);
    }
    if (message.securityType !== undefined) {
      obj.securityType = wifiNetworkSecurityTypeToJSON(message.securityType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WifiNetwork>, I>>(base?: I): WifiNetwork {
    return WifiNetwork.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WifiNetwork>, I>>(object: I): WifiNetwork {
    const message = createBaseWifiNetwork();
    message.ssid = object.ssid ?? "";
    message.rssiValue = object.rssiValue ?? 0;
    message.rssi = (object.rssi !== undefined && object.rssi !== null) ? Rssi.fromPartial(object.rssi) : undefined;
    message.securityType = object.securityType ?? 0;
    return message;
  },
};

function createBaseNetworkInterfaceIPv4Config(): NetworkInterfaceIPv4Config {
  return { dhcpEnabled: false, address: 0, subnetMask: 0, gateway: 0, dns: [] };
}

export const NetworkInterfaceIPv4Config: MessageFns<NetworkInterfaceIPv4Config> = {
  encode(message: NetworkInterfaceIPv4Config, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.dhcpEnabled !== false) {
      writer.uint32(16).bool(message.dhcpEnabled);
    }
    if (message.address !== 0) {
      writer.uint32(29).fixed32(message.address);
    }
    if (message.subnetMask !== 0) {
      writer.uint32(37).fixed32(message.subnetMask);
    }
    if (message.gateway !== 0) {
      writer.uint32(45).fixed32(message.gateway);
    }
    writer.uint32(50).fork();
    for (const v of message.dns) {
      writer.fixed32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NetworkInterfaceIPv4Config {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNetworkInterfaceIPv4Config();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.dhcpEnabled = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.address = reader.fixed32();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.subnetMask = reader.fixed32();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.gateway = reader.fixed32();
          continue;
        }
        case 6: {
          if (tag === 53) {
            message.dns.push(reader.fixed32());

            continue;
          }

          if (tag === 50) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.dns.push(reader.fixed32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NetworkInterfaceIPv4Config {
    return {
      dhcpEnabled: isSet(object.dhcpEnabled) ? globalThis.Boolean(object.dhcpEnabled) : false,
      address: isSet(object.address) ? globalThis.Number(object.address) : 0,
      subnetMask: isSet(object.subnetMask) ? globalThis.Number(object.subnetMask) : 0,
      gateway: isSet(object.gateway) ? globalThis.Number(object.gateway) : 0,
      dns: globalThis.Array.isArray(object?.dns) ? object.dns.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: NetworkInterfaceIPv4Config): unknown {
    const obj: any = {};
    if (message.dhcpEnabled !== undefined) {
      obj.dhcpEnabled = message.dhcpEnabled;
    }
    if (message.address !== undefined) {
      obj.address = Math.round(message.address);
    }
    if (message.subnetMask !== undefined) {
      obj.subnetMask = Math.round(message.subnetMask);
    }
    if (message.gateway !== undefined) {
      obj.gateway = Math.round(message.gateway);
    }
    if (message.dns?.length) {
      obj.dns = message.dns.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NetworkInterfaceIPv4Config>, I>>(base?: I): NetworkInterfaceIPv4Config {
    return NetworkInterfaceIPv4Config.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NetworkInterfaceIPv4Config>, I>>(object: I): NetworkInterfaceIPv4Config {
    const message = createBaseNetworkInterfaceIPv4Config();
    message.dhcpEnabled = object.dhcpEnabled ?? false;
    message.address = object.address ?? 0;
    message.subnetMask = object.subnetMask ?? 0;
    message.gateway = object.gateway ?? 0;
    message.dns = object.dns?.map((e) => e) || [];
    return message;
  },
};

function createBaseNetworkConnectivityStatus(): NetworkConnectivityStatus {
  return { connectedPhysical: false, connectedInternet: false, connectedTesla: false, rssi: undefined, snr: undefined };
}

export const NetworkConnectivityStatus: MessageFns<NetworkConnectivityStatus> = {
  encode(message: NetworkConnectivityStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.connectedPhysical !== false) {
      writer.uint32(8).bool(message.connectedPhysical);
    }
    if (message.connectedInternet !== false) {
      writer.uint32(16).bool(message.connectedInternet);
    }
    if (message.connectedTesla !== false) {
      writer.uint32(24).bool(message.connectedTesla);
    }
    if (message.rssi !== undefined) {
      Rssi.encode(message.rssi, writer.uint32(34).fork()).join();
    }
    if (message.snr !== undefined) {
      Int32Value.encode({ value: message.snr! }, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NetworkConnectivityStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNetworkConnectivityStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.connectedPhysical = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.connectedInternet = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.connectedTesla = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.rssi = Rssi.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.snr = Int32Value.decode(reader, reader.uint32()).value;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NetworkConnectivityStatus {
    return {
      connectedPhysical: isSet(object.connectedPhysical) ? globalThis.Boolean(object.connectedPhysical) : false,
      connectedInternet: isSet(object.connectedInternet) ? globalThis.Boolean(object.connectedInternet) : false,
      connectedTesla: isSet(object.connectedTesla) ? globalThis.Boolean(object.connectedTesla) : false,
      rssi: isSet(object.rssi) ? Rssi.fromJSON(object.rssi) : undefined,
      snr: isSet(object.snr) ? Number(object.snr) : undefined,
    };
  },

  toJSON(message: NetworkConnectivityStatus): unknown {
    const obj: any = {};
    if (message.connectedPhysical !== undefined) {
      obj.connectedPhysical = message.connectedPhysical;
    }
    if (message.connectedInternet !== undefined) {
      obj.connectedInternet = message.connectedInternet;
    }
    if (message.connectedTesla !== undefined) {
      obj.connectedTesla = message.connectedTesla;
    }
    if (message.rssi !== undefined) {
      obj.rssi = Rssi.toJSON(message.rssi);
    }
    if (message.snr !== undefined) {
      obj.snr = message.snr;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NetworkConnectivityStatus>, I>>(base?: I): NetworkConnectivityStatus {
    return NetworkConnectivityStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NetworkConnectivityStatus>, I>>(object: I): NetworkConnectivityStatus {
    const message = createBaseNetworkConnectivityStatus();
    message.connectedPhysical = object.connectedPhysical ?? false;
    message.connectedInternet = object.connectedInternet ?? false;
    message.connectedTesla = object.connectedTesla ?? false;
    message.rssi = (object.rssi !== undefined && object.rssi !== null) ? Rssi.fromPartial(object.rssi) : undefined;
    message.snr = object.snr ?? undefined;
    return message;
  },
};

function createBaseNetworkInterface(): NetworkInterface {
  return {
    macAddress: new Uint8Array(0),
    enabled: false,
    activeRoute: false,
    ipv4Config: undefined,
    connectivityStatus: undefined,
  };
}

export const NetworkInterface: MessageFns<NetworkInterface> = {
  encode(message: NetworkInterface, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.macAddress.length !== 0) {
      writer.uint32(10).bytes(message.macAddress);
    }
    if (message.enabled !== false) {
      writer.uint32(16).bool(message.enabled);
    }
    if (message.activeRoute !== false) {
      writer.uint32(24).bool(message.activeRoute);
    }
    if (message.ipv4Config !== undefined) {
      NetworkInterfaceIPv4Config.encode(message.ipv4Config, writer.uint32(34).fork()).join();
    }
    if (message.connectivityStatus !== undefined) {
      NetworkConnectivityStatus.encode(message.connectivityStatus, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NetworkInterface {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNetworkInterface();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.macAddress = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.activeRoute = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.ipv4Config = NetworkInterfaceIPv4Config.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.connectivityStatus = NetworkConnectivityStatus.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NetworkInterface {
    return {
      macAddress: isSet(object.macAddress) ? bytesFromBase64(object.macAddress) : new Uint8Array(0),
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
      activeRoute: isSet(object.activeRoute) ? globalThis.Boolean(object.activeRoute) : false,
      ipv4Config: isSet(object.ipv4Config) ? NetworkInterfaceIPv4Config.fromJSON(object.ipv4Config) : undefined,
      connectivityStatus: isSet(object.connectivityStatus)
        ? NetworkConnectivityStatus.fromJSON(object.connectivityStatus)
        : undefined,
    };
  },

  toJSON(message: NetworkInterface): unknown {
    const obj: any = {};
    if (message.macAddress !== undefined) {
      obj.macAddress = base64FromBytes(message.macAddress);
    }
    if (message.enabled !== undefined) {
      obj.enabled = message.enabled;
    }
    if (message.activeRoute !== undefined) {
      obj.activeRoute = message.activeRoute;
    }
    if (message.ipv4Config !== undefined) {
      obj.ipv4Config = NetworkInterfaceIPv4Config.toJSON(message.ipv4Config);
    }
    if (message.connectivityStatus !== undefined) {
      obj.connectivityStatus = NetworkConnectivityStatus.toJSON(message.connectivityStatus);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NetworkInterface>, I>>(base?: I): NetworkInterface {
    return NetworkInterface.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NetworkInterface>, I>>(object: I): NetworkInterface {
    const message = createBaseNetworkInterface();
    message.macAddress = object.macAddress ?? new Uint8Array(0);
    message.enabled = object.enabled ?? false;
    message.activeRoute = object.activeRoute ?? false;
    message.ipv4Config = (object.ipv4Config !== undefined && object.ipv4Config !== null)
      ? NetworkInterfaceIPv4Config.fromPartial(object.ipv4Config)
      : undefined;
    message.connectivityStatus = (object.connectivityStatus !== undefined && object.connectivityStatus !== null)
      ? NetworkConnectivityStatus.fromPartial(object.connectivityStatus)
      : undefined;
    return message;
  },
};

function createBaseCellularEID(): CellularEID {
  return { value: "" };
}

export const CellularEID: MessageFns<CellularEID> = {
  encode(message: CellularEID, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== "") {
      writer.uint32(10).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CellularEID {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCellularEID();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CellularEID {
    return { value: isSet(object.value) ? globalThis.String(object.value) : "" };
  },

  toJSON(message: CellularEID): unknown {
    const obj: any = {};
    if (message.value !== undefined) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CellularEID>, I>>(base?: I): CellularEID {
    return CellularEID.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CellularEID>, I>>(object: I): CellularEID {
    const message = createBaseCellularEID();
    message.value = object.value ?? "";
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
