// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.31.1
// source: teg_api.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "./google/protobuf/timestamp.js";

export const protobufPackage = "tesla.proto.energy_device.v1";

/**
 * TESLEMETRY SOURCE-OF-RECORD - no upstream.
 * Provenance: Tesla Energy gateway (TEG) local API, from our own
 * observations and contributions from the community
 */

export interface ControlEventSchedulingInfo {
  startTime: Date | undefined;
  durationSeconds: number;
  priority: number;
}

export interface BackupEvent {
  id: string;
  name: string;
  shedulingInfo: ControlEventSchedulingInfo | undefined;
}

export interface ManualBackupEvent {
  schedulingInfo: ControlEventSchedulingInfo | undefined;
}

export interface TEGAPIScheduleManualBackupEventRequest {
  schedulingInfo: ControlEventSchedulingInfo | undefined;
}

export interface TEGAPIScheduleManualBackupEventResponse {
}

export interface TEGAPICancelManualBackupEventRequest {
}

export interface TEGAPICancelManualBackupEventResponse {
}

export interface TEGAPIGetBackupEventsRequest {
}

export interface TEGAPIGetBackupEventsResponse {
  manualBackupEvent: ManualBackupEvent | undefined;
  backupEvents: BackupEvent[];
}

export interface TEGAPIRegisterRequest {
}

export interface TEGAPIRegisterResponse {
}

export interface TEGMessages {
  /**
   * TEGAPIGetConfigRequest get_config_request                                                              = 1;
   * TEGAPIGetConfigResponse get_config_response                                                            = 2;
   * TEGAPISetIslandModeRequest set_island_mode_request                                                     = 3;
   * TEGAPISetIslandModeResponse set_island_mode_response                                                   = 4;
   * TEGAPITriggerIslandingBlackStartRequest trigger_islanding_black_start_request                          = 5;
   * TEGAPITriggerIslandingBlackStartResponse trigger_islanding_black_start_response                        = 6;
   * TEGAPITriggerAssetManifestUploadRequest trigger_asset_manifest_upload_request                          = 7;
   * TEGAPITriggerAssetManifestUploadResponse trigger_asset_manifest_upload_response                        = 8;
   * TEGAPITriggerPowerwall2EnumerationRequest trigger_powerwall2_enumeration_request                       = 9;
   * TEGAPITriggerPowerwall2EnumerationResponse trigger_powerwall2_enumeration_response                     = 10;
   * TEGAPITriggerEsCanFirmwareUpdateRequest trigger_es_can_firmware_update_request                         = 11;
   * TEGAPITriggerEsCanFirmwareUpdateResponse trigger_es_can_firmware_update_response                       = 12;
   * TEGAPIRegisterRequest register_request                                                                 = 13;
   * TEGAPIRegisterResponse register_response                                                               = 14;
   * TEGAPITriggerPowerwall2PhaseDetectionRequest trigger_powerwall2_phase_detection_request                = 15;
   * TEGAPITriggerPowerwall2PhaseDetectionResponse trigger_powerwall2_phase_detection_response              = 16;
   * TEGAPIResetPowerwall2PhaseDetectionRequest reset_powerwall2_phase_detection_request                    = 17;
   * TEGAPIResetPowerwall2PhaseDetectionResponse reset_powerwall2_phase_detection_response                  = 18;
   * TEGAPIForceWifiScanRequest force_wifi_scan_request                                                     = 19;
   * TEGAPIForceWifiScanResponse force_wifi_scan_response                                                   = 20;
   * TEGAPIStartPowerwall2InverterSelfTestsRequest start_powerwall2_inverter_self_tests_request             = 21;
   * TEGAPIStartPowerwall2InverterSelfTestsResponse start_powerwall2_inverter_self_tests_response           = 22;
   * TEGAPIStopPowerwall2InverterSelfTestsRequest stop_powerwall2_inverter_self_tests_request               = 23;
   * TEGAPIStopPowerwall2InverterSelfTestsResponse stop_powerwall2_inverter_self_tests_response             = 24;
   * TEGAPIStartPowerwall2BubbleShedRequest start_powerwall2_bubble_shed_request                            = 25;
   * TEGAPIStartPowerwall2BubbleShedResponse start_powerwall2_bubble_shed_response                          = 26;
   * TEGAPIClearSolarInverterAlertsRequest clear_solar_inverter_alerts_request                              = 27;
   * TEGAPIClearSolarInverterAlertsResponse clear_solar_inverter_alerts_response                            = 28;
   * TEGAPIGetWifiConfigWithCredentialsRequest get_wifi_config_with_credentials_request                     = 29;
   * TEGAPIGetWifiConfigWithCredentialsResponse get_wifi_config_with_credentials_response                   = 30;
   * TEGAPIDisableBatteriesRequest disable_batteries_request                                                = 31;
   * TEGAPIDisableBatteriesResponse disable_batteries_response                                              = 32;
   * TEGAPITriggerPW3CanFirmwareUpdateRequest trigger_p_w3_can_firmware_update_request                      = 33;
   * TEGAPITriggerPW3CanFirmwareUpdateResponse trigger_p_w3_can_firmware_update_response                    = 34;
   * TEGAPITriggerPowerwall3EnumerationRequest trigger_powerwall3_enumeration_request                       = 35;
   * TEGAPITriggerPowerwall3EnumerationResponse trigger_powerwall3_enumeration_response                     = 36;
   * TEGAPIDispatchBatteryPowerRequest dispatch_battery_power_request                                       = 37;
   * TEGAPIDispatchBatteryPowerResponse dispatch_battery_power_response                                     = 38;
   * TEGAPIDetectWiredMetersRequest detect_wired_meters_request                                             = 39;
   * TEGAPIDetectWiredMetersResponse detect_wired_meters_response                                           = 40;
   * TEGAPIBypassBatterySoeAdjustmentConstraintsRequest bypass_battery_soe_adjustment_constraints_request   = 41;
   * TEGAPIBypassBatterySoeAdjustmentConstraintsResponse bypass_battery_soe_adjustment_constraints_response = 42;
   * TEGAPIEnsureCertificateRequest ensure_certificate_request                                              = 43;
   * TEGAPIEnsureCertificateResponse ensure_certificate_response                                            = 44;
   */
  scheduleManualBackupEventRequest?: TEGAPIScheduleManualBackupEventRequest | undefined;
  scheduleManualBackupEventResponse?: TEGAPIScheduleManualBackupEventResponse | undefined;
  cancelManualBackupEventRequest?: TEGAPICancelManualBackupEventRequest | undefined;
  cancelManualBackupEventResponse?: TEGAPICancelManualBackupEventResponse | undefined;
  getBackupEventsRequest?:
    | TEGAPIGetBackupEventsRequest
    | undefined;
  /**
   * TEGAPIGetCsmsPropertiesRequest get_csms_properties_request                                             = 51;
   * TEGAPIGetCsmsPropertiesResponse get_csms_properties_response                                           = 52;
   * TEGAPIConfigureOcppRequest configure_ocpp_request                                                      = 53;
   * TEGAPIConfigureOcppResponse configure_ocpp_response                                                    = 54;
   * TEGAPIRetrieveSiteUuidRequest retrieve_site_uuid_request                                               = 55;
   * TEGAPIRetrieveSiteUuidResponse retrieve_site_uuid_response                                             = 56;
   * TEGAPIRetrieveSiteSuggestionRequest retrieve_site_suggestion_request                                   = 57;
   * TEGAPIRetrieveSiteSuggestionResponse retrieve_site_suggestion_response                                 = 58;
   * TEGAPIStartProtectionTripSelfTestRequest start_protection_trip_self_test_request                       = 59;
   * TEGAPIStartProtectionTripSelfTestResponse start_protection_trip_self_test_response                     = 60;
   * TEGAPIStopProtectionTripSelfTestRequest stop_protection_trip_self_test_request                         = 61;
   * TEGAPIStopProtectionTripSelfTestResponse stop_protection_trip_self_test_response                       = 62;
   * TEGAPIProvisionEatonSmartBreakerRequest provision_eaton_smart_breaker_request                          = 63;
   * TEGAPIProvisionEatonSmartBreakerResponse provision_eaton_smart_breaker_response                        = 64;
   * TEGAPIIdentifyEatonSmartBreakerRequest identify_eaton_smart_breaker_request                            = 65;
   * TEGAPIIdentifyEatonSmartBreakerResponse identify_eaton_smart_breaker_response                          = 66;
   * TEGAPITriggerPvacFanSelfTestRequest trigger_pvac_fan_self_test_request                                 = 67;
   * TEGAPITriggerPvacFanSelfTestResponse trigger_pvac_fan_self_test_response                               = 68;
   * TEGAPIProxyPrepareRegistrationPayloadRequest proxy_prepare_registration_payload_request                = 69;
   * TEGAPIProxyPrepareRegistrationPayloadResponse proxy_prepare_registration_payload_response              = 70;
   * TEGAPITriggerWallboxVehicleAbsentSelfTestRequest trigger_wallbox_vehicle_absent_self_test_request      = 71;
   * TEGAPITriggerWallboxVehicleAbsentSelfTestResponse trigger_wallbox_vehicle_absent_self_test_response    = 72;
   * TEGAPICustomerResetRequest customer_reset_request                                                      = 73;
   * TEGAPICustomerResetResponse customer_reset_response                                                    = 74;
   */
  getBackupEventsResponse?: TEGAPIGetBackupEventsResponse | undefined;
}

function createBaseControlEventSchedulingInfo(): ControlEventSchedulingInfo {
  return { startTime: undefined, durationSeconds: 0, priority: 0 };
}

export const ControlEventSchedulingInfo: MessageFns<ControlEventSchedulingInfo> = {
  encode(message: ControlEventSchedulingInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.startTime !== undefined) {
      Timestamp.encode(toTimestamp(message.startTime), writer.uint32(10).fork()).join();
    }
    if (message.durationSeconds !== 0) {
      writer.uint32(16).uint32(message.durationSeconds);
    }
    if (message.priority !== 0) {
      writer.uint32(24).uint64(message.priority);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ControlEventSchedulingInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseControlEventSchedulingInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.startTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.durationSeconds = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.priority = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ControlEventSchedulingInfo {
    return {
      startTime: isSet(object.startTime) ? fromJsonTimestamp(object.startTime) : undefined,
      durationSeconds: isSet(object.durationSeconds) ? globalThis.Number(object.durationSeconds) : 0,
      priority: isSet(object.priority) ? globalThis.Number(object.priority) : 0,
    };
  },

  toJSON(message: ControlEventSchedulingInfo): unknown {
    const obj: any = {};
    if (message.startTime !== undefined) {
      obj.startTime = message.startTime.toISOString();
    }
    if (message.durationSeconds !== undefined) {
      obj.durationSeconds = Math.round(message.durationSeconds);
    }
    if (message.priority !== undefined) {
      obj.priority = Math.round(message.priority);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ControlEventSchedulingInfo>, I>>(base?: I): ControlEventSchedulingInfo {
    return ControlEventSchedulingInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ControlEventSchedulingInfo>, I>>(object: I): ControlEventSchedulingInfo {
    const message = createBaseControlEventSchedulingInfo();
    message.startTime = object.startTime ?? undefined;
    message.durationSeconds = object.durationSeconds ?? 0;
    message.priority = object.priority ?? 0;
    return message;
  },
};

function createBaseBackupEvent(): BackupEvent {
  return { id: "", name: "", shedulingInfo: undefined };
}

export const BackupEvent: MessageFns<BackupEvent> = {
  encode(message: BackupEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.shedulingInfo !== undefined) {
      ControlEventSchedulingInfo.encode(message.shedulingInfo, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BackupEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBackupEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.shedulingInfo = ControlEventSchedulingInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BackupEvent {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      shedulingInfo: isSet(object.shedulingInfo)
        ? ControlEventSchedulingInfo.fromJSON(object.shedulingInfo)
        : undefined,
    };
  },

  toJSON(message: BackupEvent): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = message.id;
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.shedulingInfo !== undefined) {
      obj.shedulingInfo = ControlEventSchedulingInfo.toJSON(message.shedulingInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BackupEvent>, I>>(base?: I): BackupEvent {
    return BackupEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BackupEvent>, I>>(object: I): BackupEvent {
    const message = createBaseBackupEvent();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.shedulingInfo = (object.shedulingInfo !== undefined && object.shedulingInfo !== null)
      ? ControlEventSchedulingInfo.fromPartial(object.shedulingInfo)
      : undefined;
    return message;
  },
};

function createBaseManualBackupEvent(): ManualBackupEvent {
  return { schedulingInfo: undefined };
}

export const ManualBackupEvent: MessageFns<ManualBackupEvent> = {
  encode(message: ManualBackupEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.schedulingInfo !== undefined) {
      ControlEventSchedulingInfo.encode(message.schedulingInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ManualBackupEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseManualBackupEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.schedulingInfo = ControlEventSchedulingInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ManualBackupEvent {
    return {
      schedulingInfo: isSet(object.schedulingInfo)
        ? ControlEventSchedulingInfo.fromJSON(object.schedulingInfo)
        : undefined,
    };
  },

  toJSON(message: ManualBackupEvent): unknown {
    const obj: any = {};
    if (message.schedulingInfo !== undefined) {
      obj.schedulingInfo = ControlEventSchedulingInfo.toJSON(message.schedulingInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ManualBackupEvent>, I>>(base?: I): ManualBackupEvent {
    return ManualBackupEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ManualBackupEvent>, I>>(object: I): ManualBackupEvent {
    const message = createBaseManualBackupEvent();
    message.schedulingInfo = (object.schedulingInfo !== undefined && object.schedulingInfo !== null)
      ? ControlEventSchedulingInfo.fromPartial(object.schedulingInfo)
      : undefined;
    return message;
  },
};

function createBaseTEGAPIScheduleManualBackupEventRequest(): TEGAPIScheduleManualBackupEventRequest {
  return { schedulingInfo: undefined };
}

export const TEGAPIScheduleManualBackupEventRequest: MessageFns<TEGAPIScheduleManualBackupEventRequest> = {
  encode(message: TEGAPIScheduleManualBackupEventRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.schedulingInfo !== undefined) {
      ControlEventSchedulingInfo.encode(message.schedulingInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TEGAPIScheduleManualBackupEventRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTEGAPIScheduleManualBackupEventRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.schedulingInfo = ControlEventSchedulingInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TEGAPIScheduleManualBackupEventRequest {
    return {
      schedulingInfo: isSet(object.schedulingInfo)
        ? ControlEventSchedulingInfo.fromJSON(object.schedulingInfo)
        : undefined,
    };
  },

  toJSON(message: TEGAPIScheduleManualBackupEventRequest): unknown {
    const obj: any = {};
    if (message.schedulingInfo !== undefined) {
      obj.schedulingInfo = ControlEventSchedulingInfo.toJSON(message.schedulingInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TEGAPIScheduleManualBackupEventRequest>, I>>(
    base?: I,
  ): TEGAPIScheduleManualBackupEventRequest {
    return TEGAPIScheduleManualBackupEventRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TEGAPIScheduleManualBackupEventRequest>, I>>(
    object: I,
  ): TEGAPIScheduleManualBackupEventRequest {
    const message = createBaseTEGAPIScheduleManualBackupEventRequest();
    message.schedulingInfo = (object.schedulingInfo !== undefined && object.schedulingInfo !== null)
      ? ControlEventSchedulingInfo.fromPartial(object.schedulingInfo)
      : undefined;
    return message;
  },
};

function createBaseTEGAPIScheduleManualBackupEventResponse(): TEGAPIScheduleManualBackupEventResponse {
  return {};
}

export const TEGAPIScheduleManualBackupEventResponse: MessageFns<TEGAPIScheduleManualBackupEventResponse> = {
  encode(_: TEGAPIScheduleManualBackupEventResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TEGAPIScheduleManualBackupEventResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTEGAPIScheduleManualBackupEventResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): TEGAPIScheduleManualBackupEventResponse {
    return {};
  },

  toJSON(_: TEGAPIScheduleManualBackupEventResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<TEGAPIScheduleManualBackupEventResponse>, I>>(
    base?: I,
  ): TEGAPIScheduleManualBackupEventResponse {
    return TEGAPIScheduleManualBackupEventResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TEGAPIScheduleManualBackupEventResponse>, I>>(
    _: I,
  ): TEGAPIScheduleManualBackupEventResponse {
    const message = createBaseTEGAPIScheduleManualBackupEventResponse();
    return message;
  },
};

function createBaseTEGAPICancelManualBackupEventRequest(): TEGAPICancelManualBackupEventRequest {
  return {};
}

export const TEGAPICancelManualBackupEventRequest: MessageFns<TEGAPICancelManualBackupEventRequest> = {
  encode(_: TEGAPICancelManualBackupEventRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TEGAPICancelManualBackupEventRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTEGAPICancelManualBackupEventRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): TEGAPICancelManualBackupEventRequest {
    return {};
  },

  toJSON(_: TEGAPICancelManualBackupEventRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<TEGAPICancelManualBackupEventRequest>, I>>(
    base?: I,
  ): TEGAPICancelManualBackupEventRequest {
    return TEGAPICancelManualBackupEventRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TEGAPICancelManualBackupEventRequest>, I>>(
    _: I,
  ): TEGAPICancelManualBackupEventRequest {
    const message = createBaseTEGAPICancelManualBackupEventRequest();
    return message;
  },
};

function createBaseTEGAPICancelManualBackupEventResponse(): TEGAPICancelManualBackupEventResponse {
  return {};
}

export const TEGAPICancelManualBackupEventResponse: MessageFns<TEGAPICancelManualBackupEventResponse> = {
  encode(_: TEGAPICancelManualBackupEventResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TEGAPICancelManualBackupEventResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTEGAPICancelManualBackupEventResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): TEGAPICancelManualBackupEventResponse {
    return {};
  },

  toJSON(_: TEGAPICancelManualBackupEventResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<TEGAPICancelManualBackupEventResponse>, I>>(
    base?: I,
  ): TEGAPICancelManualBackupEventResponse {
    return TEGAPICancelManualBackupEventResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TEGAPICancelManualBackupEventResponse>, I>>(
    _: I,
  ): TEGAPICancelManualBackupEventResponse {
    const message = createBaseTEGAPICancelManualBackupEventResponse();
    return message;
  },
};

function createBaseTEGAPIGetBackupEventsRequest(): TEGAPIGetBackupEventsRequest {
  return {};
}

export const TEGAPIGetBackupEventsRequest: MessageFns<TEGAPIGetBackupEventsRequest> = {
  encode(_: TEGAPIGetBackupEventsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TEGAPIGetBackupEventsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTEGAPIGetBackupEventsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): TEGAPIGetBackupEventsRequest {
    return {};
  },

  toJSON(_: TEGAPIGetBackupEventsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<TEGAPIGetBackupEventsRequest>, I>>(base?: I): TEGAPIGetBackupEventsRequest {
    return TEGAPIGetBackupEventsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TEGAPIGetBackupEventsRequest>, I>>(_: I): TEGAPIGetBackupEventsRequest {
    const message = createBaseTEGAPIGetBackupEventsRequest();
    return message;
  },
};

function createBaseTEGAPIGetBackupEventsResponse(): TEGAPIGetBackupEventsResponse {
  return { manualBackupEvent: undefined, backupEvents: [] };
}

export const TEGAPIGetBackupEventsResponse: MessageFns<TEGAPIGetBackupEventsResponse> = {
  encode(message: TEGAPIGetBackupEventsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.manualBackupEvent !== undefined) {
      ManualBackupEvent.encode(message.manualBackupEvent, writer.uint32(10).fork()).join();
    }
    for (const v of message.backupEvents) {
      BackupEvent.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TEGAPIGetBackupEventsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTEGAPIGetBackupEventsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.manualBackupEvent = ManualBackupEvent.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.backupEvents.push(BackupEvent.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TEGAPIGetBackupEventsResponse {
    return {
      manualBackupEvent: isSet(object.manualBackupEvent)
        ? ManualBackupEvent.fromJSON(object.manualBackupEvent)
        : undefined,
      backupEvents: globalThis.Array.isArray(object?.backupEvents)
        ? object.backupEvents.map((e: any) => BackupEvent.fromJSON(e))
        : [],
    };
  },

  toJSON(message: TEGAPIGetBackupEventsResponse): unknown {
    const obj: any = {};
    if (message.manualBackupEvent !== undefined) {
      obj.manualBackupEvent = ManualBackupEvent.toJSON(message.manualBackupEvent);
    }
    if (message.backupEvents?.length) {
      obj.backupEvents = message.backupEvents.map((e) => BackupEvent.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TEGAPIGetBackupEventsResponse>, I>>(base?: I): TEGAPIGetBackupEventsResponse {
    return TEGAPIGetBackupEventsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TEGAPIGetBackupEventsResponse>, I>>(
    object: I,
  ): TEGAPIGetBackupEventsResponse {
    const message = createBaseTEGAPIGetBackupEventsResponse();
    message.manualBackupEvent = (object.manualBackupEvent !== undefined && object.manualBackupEvent !== null)
      ? ManualBackupEvent.fromPartial(object.manualBackupEvent)
      : undefined;
    message.backupEvents = object.backupEvents?.map((e) => BackupEvent.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTEGAPIRegisterRequest(): TEGAPIRegisterRequest {
  return {};
}

export const TEGAPIRegisterRequest: MessageFns<TEGAPIRegisterRequest> = {
  encode(_: TEGAPIRegisterRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TEGAPIRegisterRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTEGAPIRegisterRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): TEGAPIRegisterRequest {
    return {};
  },

  toJSON(_: TEGAPIRegisterRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<TEGAPIRegisterRequest>, I>>(base?: I): TEGAPIRegisterRequest {
    return TEGAPIRegisterRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TEGAPIRegisterRequest>, I>>(_: I): TEGAPIRegisterRequest {
    const message = createBaseTEGAPIRegisterRequest();
    return message;
  },
};

function createBaseTEGAPIRegisterResponse(): TEGAPIRegisterResponse {
  return {};
}

export const TEGAPIRegisterResponse: MessageFns<TEGAPIRegisterResponse> = {
  encode(_: TEGAPIRegisterResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TEGAPIRegisterResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTEGAPIRegisterResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): TEGAPIRegisterResponse {
    return {};
  },

  toJSON(_: TEGAPIRegisterResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<TEGAPIRegisterResponse>, I>>(base?: I): TEGAPIRegisterResponse {
    return TEGAPIRegisterResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TEGAPIRegisterResponse>, I>>(_: I): TEGAPIRegisterResponse {
    const message = createBaseTEGAPIRegisterResponse();
    return message;
  },
};

function createBaseTEGMessages(): TEGMessages {
  return {
    scheduleManualBackupEventRequest: undefined,
    scheduleManualBackupEventResponse: undefined,
    cancelManualBackupEventRequest: undefined,
    cancelManualBackupEventResponse: undefined,
    getBackupEventsRequest: undefined,
    getBackupEventsResponse: undefined,
  };
}

export const TEGMessages: MessageFns<TEGMessages> = {
  encode(message: TEGMessages, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.scheduleManualBackupEventRequest !== undefined) {
      TEGAPIScheduleManualBackupEventRequest.encode(message.scheduleManualBackupEventRequest, writer.uint32(362).fork())
        .join();
    }
    if (message.scheduleManualBackupEventResponse !== undefined) {
      TEGAPIScheduleManualBackupEventResponse.encode(
        message.scheduleManualBackupEventResponse,
        writer.uint32(370).fork(),
      ).join();
    }
    if (message.cancelManualBackupEventRequest !== undefined) {
      TEGAPICancelManualBackupEventRequest.encode(message.cancelManualBackupEventRequest, writer.uint32(378).fork())
        .join();
    }
    if (message.cancelManualBackupEventResponse !== undefined) {
      TEGAPICancelManualBackupEventResponse.encode(message.cancelManualBackupEventResponse, writer.uint32(386).fork())
        .join();
    }
    if (message.getBackupEventsRequest !== undefined) {
      TEGAPIGetBackupEventsRequest.encode(message.getBackupEventsRequest, writer.uint32(394).fork()).join();
    }
    if (message.getBackupEventsResponse !== undefined) {
      TEGAPIGetBackupEventsResponse.encode(message.getBackupEventsResponse, writer.uint32(402).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TEGMessages {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTEGMessages();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 45: {
          if (tag !== 362) {
            break;
          }

          message.scheduleManualBackupEventRequest = TEGAPIScheduleManualBackupEventRequest.decode(
            reader,
            reader.uint32(),
          );
          continue;
        }
        case 46: {
          if (tag !== 370) {
            break;
          }

          message.scheduleManualBackupEventResponse = TEGAPIScheduleManualBackupEventResponse.decode(
            reader,
            reader.uint32(),
          );
          continue;
        }
        case 47: {
          if (tag !== 378) {
            break;
          }

          message.cancelManualBackupEventRequest = TEGAPICancelManualBackupEventRequest.decode(reader, reader.uint32());
          continue;
        }
        case 48: {
          if (tag !== 386) {
            break;
          }

          message.cancelManualBackupEventResponse = TEGAPICancelManualBackupEventResponse.decode(
            reader,
            reader.uint32(),
          );
          continue;
        }
        case 49: {
          if (tag !== 394) {
            break;
          }

          message.getBackupEventsRequest = TEGAPIGetBackupEventsRequest.decode(reader, reader.uint32());
          continue;
        }
        case 50: {
          if (tag !== 402) {
            break;
          }

          message.getBackupEventsResponse = TEGAPIGetBackupEventsResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TEGMessages {
    return {
      scheduleManualBackupEventRequest: isSet(object.scheduleManualBackupEventRequest)
        ? TEGAPIScheduleManualBackupEventRequest.fromJSON(object.scheduleManualBackupEventRequest)
        : undefined,
      scheduleManualBackupEventResponse: isSet(object.scheduleManualBackupEventResponse)
        ? TEGAPIScheduleManualBackupEventResponse.fromJSON(object.scheduleManualBackupEventResponse)
        : undefined,
      cancelManualBackupEventRequest: isSet(object.cancelManualBackupEventRequest)
        ? TEGAPICancelManualBackupEventRequest.fromJSON(object.cancelManualBackupEventRequest)
        : undefined,
      cancelManualBackupEventResponse: isSet(object.cancelManualBackupEventResponse)
        ? TEGAPICancelManualBackupEventResponse.fromJSON(object.cancelManualBackupEventResponse)
        : undefined,
      getBackupEventsRequest: isSet(object.getBackupEventsRequest)
        ? TEGAPIGetBackupEventsRequest.fromJSON(object.getBackupEventsRequest)
        : undefined,
      getBackupEventsResponse: isSet(object.getBackupEventsResponse)
        ? TEGAPIGetBackupEventsResponse.fromJSON(object.getBackupEventsResponse)
        : undefined,
    };
  },

  toJSON(message: TEGMessages): unknown {
    const obj: any = {};
    if (message.scheduleManualBackupEventRequest !== undefined) {
      obj.scheduleManualBackupEventRequest = TEGAPIScheduleManualBackupEventRequest.toJSON(
        message.scheduleManualBackupEventRequest,
      );
    }
    if (message.scheduleManualBackupEventResponse !== undefined) {
      obj.scheduleManualBackupEventResponse = TEGAPIScheduleManualBackupEventResponse.toJSON(
        message.scheduleManualBackupEventResponse,
      );
    }
    if (message.cancelManualBackupEventRequest !== undefined) {
      obj.cancelManualBackupEventRequest = TEGAPICancelManualBackupEventRequest.toJSON(
        message.cancelManualBackupEventRequest,
      );
    }
    if (message.cancelManualBackupEventResponse !== undefined) {
      obj.cancelManualBackupEventResponse = TEGAPICancelManualBackupEventResponse.toJSON(
        message.cancelManualBackupEventResponse,
      );
    }
    if (message.getBackupEventsRequest !== undefined) {
      obj.getBackupEventsRequest = TEGAPIGetBackupEventsRequest.toJSON(message.getBackupEventsRequest);
    }
    if (message.getBackupEventsResponse !== undefined) {
      obj.getBackupEventsResponse = TEGAPIGetBackupEventsResponse.toJSON(message.getBackupEventsResponse);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TEGMessages>, I>>(base?: I): TEGMessages {
    return TEGMessages.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TEGMessages>, I>>(object: I): TEGMessages {
    const message = createBaseTEGMessages();
    message.scheduleManualBackupEventRequest =
      (object.scheduleManualBackupEventRequest !== undefined && object.scheduleManualBackupEventRequest !== null)
        ? TEGAPIScheduleManualBackupEventRequest.fromPartial(object.scheduleManualBackupEventRequest)
        : undefined;
    message.scheduleManualBackupEventResponse =
      (object.scheduleManualBackupEventResponse !== undefined && object.scheduleManualBackupEventResponse !== null)
        ? TEGAPIScheduleManualBackupEventResponse.fromPartial(object.scheduleManualBackupEventResponse)
        : undefined;
    message.cancelManualBackupEventRequest =
      (object.cancelManualBackupEventRequest !== undefined && object.cancelManualBackupEventRequest !== null)
        ? TEGAPICancelManualBackupEventRequest.fromPartial(object.cancelManualBackupEventRequest)
        : undefined;
    message.cancelManualBackupEventResponse =
      (object.cancelManualBackupEventResponse !== undefined && object.cancelManualBackupEventResponse !== null)
        ? TEGAPICancelManualBackupEventResponse.fromPartial(object.cancelManualBackupEventResponse)
        : undefined;
    message.getBackupEventsRequest =
      (object.getBackupEventsRequest !== undefined && object.getBackupEventsRequest !== null)
        ? TEGAPIGetBackupEventsRequest.fromPartial(object.getBackupEventsRequest)
        : undefined;
    message.getBackupEventsResponse =
      (object.getBackupEventsResponse !== undefined && object.getBackupEventsResponse !== null)
        ? TEGAPIGetBackupEventsResponse.fromPartial(object.getBackupEventsResponse)
        : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
