// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.31.1
// source: dashcam_sei.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "DashcamSei";

/**
 * SeiMetadata is the per-frame vehicle telemetry carried in the SEI (supplemental
 * enhancement information) payload embedded in TeslaCam / Sentry / live-camera
 * H.264 video, synchronized to the frame it accompanies.
 */
export interface SeiMetadata {
  /** Schema/frame-type version byte; meaning beyond that is not confirmed. */
  field1: number;
  gearState: SeiMetadata_Gear;
  frameSeqNo: number;
  vehicleSpeedMps: number;
  acceleratorPedalPosition: number;
  steeringWheelAngle: number;
  blinkerOnLeft: boolean;
  blinkerOnRight: boolean;
  brakeApplied: boolean;
  autopilotState: SeiMetadata_AutopilotState;
  latitudeDeg: number;
  longitudeDeg: number;
  headingDeg: number;
  linearAccelerationMps2X: number;
  linearAccelerationMps2Y: number;
  linearAccelerationMps2Z: number;
}

export enum SeiMetadata_Gear {
  GEAR_PARK = 0,
  GEAR_DRIVE = 1,
  GEAR_REVERSE = 2,
  GEAR_NEUTRAL = 3,
  UNRECOGNIZED = -1,
}

export function seiMetadata_GearFromJSON(object: any): SeiMetadata_Gear {
  switch (object) {
    case 0:
    case "GEAR_PARK":
      return SeiMetadata_Gear.GEAR_PARK;
    case 1:
    case "GEAR_DRIVE":
      return SeiMetadata_Gear.GEAR_DRIVE;
    case 2:
    case "GEAR_REVERSE":
      return SeiMetadata_Gear.GEAR_REVERSE;
    case 3:
    case "GEAR_NEUTRAL":
      return SeiMetadata_Gear.GEAR_NEUTRAL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SeiMetadata_Gear.UNRECOGNIZED;
  }
}

export function seiMetadata_GearToJSON(object: SeiMetadata_Gear): string {
  switch (object) {
    case SeiMetadata_Gear.GEAR_PARK:
      return "GEAR_PARK";
    case SeiMetadata_Gear.GEAR_DRIVE:
      return "GEAR_DRIVE";
    case SeiMetadata_Gear.GEAR_REVERSE:
      return "GEAR_REVERSE";
    case SeiMetadata_Gear.GEAR_NEUTRAL:
      return "GEAR_NEUTRAL";
    case SeiMetadata_Gear.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum SeiMetadata_AutopilotState {
  NONE = 0,
  SELF_DRIVING = 1,
  AUTOSTEER = 2,
  TACC = 3,
  UNRECOGNIZED = -1,
}

export function seiMetadata_AutopilotStateFromJSON(object: any): SeiMetadata_AutopilotState {
  switch (object) {
    case 0:
    case "NONE":
      return SeiMetadata_AutopilotState.NONE;
    case 1:
    case "SELF_DRIVING":
      return SeiMetadata_AutopilotState.SELF_DRIVING;
    case 2:
    case "AUTOSTEER":
      return SeiMetadata_AutopilotState.AUTOSTEER;
    case 3:
    case "TACC":
      return SeiMetadata_AutopilotState.TACC;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SeiMetadata_AutopilotState.UNRECOGNIZED;
  }
}

export function seiMetadata_AutopilotStateToJSON(object: SeiMetadata_AutopilotState): string {
  switch (object) {
    case SeiMetadata_AutopilotState.NONE:
      return "NONE";
    case SeiMetadata_AutopilotState.SELF_DRIVING:
      return "SELF_DRIVING";
    case SeiMetadata_AutopilotState.AUTOSTEER:
      return "AUTOSTEER";
    case SeiMetadata_AutopilotState.TACC:
      return "TACC";
    case SeiMetadata_AutopilotState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

function createBaseSeiMetadata(): SeiMetadata {
  return {
    field1: 0,
    gearState: 0,
    frameSeqNo: 0,
    vehicleSpeedMps: 0,
    acceleratorPedalPosition: 0,
    steeringWheelAngle: 0,
    blinkerOnLeft: false,
    blinkerOnRight: false,
    brakeApplied: false,
    autopilotState: 0,
    latitudeDeg: 0,
    longitudeDeg: 0,
    headingDeg: 0,
    linearAccelerationMps2X: 0,
    linearAccelerationMps2Y: 0,
    linearAccelerationMps2Z: 0,
  };
}

export const SeiMetadata: MessageFns<SeiMetadata> = {
  encode(message: SeiMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.field1 !== 0) {
      writer.uint32(8).uint32(message.field1);
    }
    if (message.gearState !== 0) {
      writer.uint32(16).int32(message.gearState);
    }
    if (message.frameSeqNo !== 0) {
      writer.uint32(24).uint64(message.frameSeqNo);
    }
    if (message.vehicleSpeedMps !== 0) {
      writer.uint32(37).float(message.vehicleSpeedMps);
    }
    if (message.acceleratorPedalPosition !== 0) {
      writer.uint32(45).float(message.acceleratorPedalPosition);
    }
    if (message.steeringWheelAngle !== 0) {
      writer.uint32(53).float(message.steeringWheelAngle);
    }
    if (message.blinkerOnLeft !== false) {
      writer.uint32(56).bool(message.blinkerOnLeft);
    }
    if (message.blinkerOnRight !== false) {
      writer.uint32(64).bool(message.blinkerOnRight);
    }
    if (message.brakeApplied !== false) {
      writer.uint32(72).bool(message.brakeApplied);
    }
    if (message.autopilotState !== 0) {
      writer.uint32(80).int32(message.autopilotState);
    }
    if (message.latitudeDeg !== 0) {
      writer.uint32(89).double(message.latitudeDeg);
    }
    if (message.longitudeDeg !== 0) {
      writer.uint32(97).double(message.longitudeDeg);
    }
    if (message.headingDeg !== 0) {
      writer.uint32(105).double(message.headingDeg);
    }
    if (message.linearAccelerationMps2X !== 0) {
      writer.uint32(113).double(message.linearAccelerationMps2X);
    }
    if (message.linearAccelerationMps2Y !== 0) {
      writer.uint32(121).double(message.linearAccelerationMps2Y);
    }
    if (message.linearAccelerationMps2Z !== 0) {
      writer.uint32(129).double(message.linearAccelerationMps2Z);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SeiMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSeiMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.field1 = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.gearState = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.frameSeqNo = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.vehicleSpeedMps = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.acceleratorPedalPosition = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 53) {
            break;
          }

          message.steeringWheelAngle = reader.float();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.blinkerOnLeft = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.blinkerOnRight = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.brakeApplied = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.autopilotState = reader.int32() as any;
          continue;
        }
        case 11: {
          if (tag !== 89) {
            break;
          }

          message.latitudeDeg = reader.double();
          continue;
        }
        case 12: {
          if (tag !== 97) {
            break;
          }

          message.longitudeDeg = reader.double();
          continue;
        }
        case 13: {
          if (tag !== 105) {
            break;
          }

          message.headingDeg = reader.double();
          continue;
        }
        case 14: {
          if (tag !== 113) {
            break;
          }

          message.linearAccelerationMps2X = reader.double();
          continue;
        }
        case 15: {
          if (tag !== 121) {
            break;
          }

          message.linearAccelerationMps2Y = reader.double();
          continue;
        }
        case 16: {
          if (tag !== 129) {
            break;
          }

          message.linearAccelerationMps2Z = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SeiMetadata {
    return {
      field1: isSet(object.field1) ? globalThis.Number(object.field1) : 0,
      gearState: isSet(object.gearState) ? seiMetadata_GearFromJSON(object.gearState) : 0,
      frameSeqNo: isSet(object.frameSeqNo) ? globalThis.Number(object.frameSeqNo) : 0,
      vehicleSpeedMps: isSet(object.vehicleSpeedMps) ? globalThis.Number(object.vehicleSpeedMps) : 0,
      acceleratorPedalPosition: isSet(object.acceleratorPedalPosition)
        ? globalThis.Number(object.acceleratorPedalPosition)
        : 0,
      steeringWheelAngle: isSet(object.steeringWheelAngle) ? globalThis.Number(object.steeringWheelAngle) : 0,
      blinkerOnLeft: isSet(object.blinkerOnLeft) ? globalThis.Boolean(object.blinkerOnLeft) : false,
      blinkerOnRight: isSet(object.blinkerOnRight) ? globalThis.Boolean(object.blinkerOnRight) : false,
      brakeApplied: isSet(object.brakeApplied) ? globalThis.Boolean(object.brakeApplied) : false,
      autopilotState: isSet(object.autopilotState) ? seiMetadata_AutopilotStateFromJSON(object.autopilotState) : 0,
      latitudeDeg: isSet(object.latitudeDeg) ? globalThis.Number(object.latitudeDeg) : 0,
      longitudeDeg: isSet(object.longitudeDeg) ? globalThis.Number(object.longitudeDeg) : 0,
      headingDeg: isSet(object.headingDeg) ? globalThis.Number(object.headingDeg) : 0,
      linearAccelerationMps2X: isSet(object.linearAccelerationMps2X)
        ? globalThis.Number(object.linearAccelerationMps2X)
        : 0,
      linearAccelerationMps2Y: isSet(object.linearAccelerationMps2Y)
        ? globalThis.Number(object.linearAccelerationMps2Y)
        : 0,
      linearAccelerationMps2Z: isSet(object.linearAccelerationMps2Z)
        ? globalThis.Number(object.linearAccelerationMps2Z)
        : 0,
    };
  },

  toJSON(message: SeiMetadata): unknown {
    const obj: any = {};
    if (message.field1 !== undefined) {
      obj.field1 = Math.round(message.field1);
    }
    if (message.gearState !== undefined) {
      obj.gearState = seiMetadata_GearToJSON(message.gearState);
    }
    if (message.frameSeqNo !== undefined) {
      obj.frameSeqNo = Math.round(message.frameSeqNo);
    }
    if (message.vehicleSpeedMps !== undefined) {
      obj.vehicleSpeedMps = message.vehicleSpeedMps;
    }
    if (message.acceleratorPedalPosition !== undefined) {
      obj.acceleratorPedalPosition = message.acceleratorPedalPosition;
    }
    if (message.steeringWheelAngle !== undefined) {
      obj.steeringWheelAngle = message.steeringWheelAngle;
    }
    if (message.blinkerOnLeft !== undefined) {
      obj.blinkerOnLeft = message.blinkerOnLeft;
    }
    if (message.blinkerOnRight !== undefined) {
      obj.blinkerOnRight = message.blinkerOnRight;
    }
    if (message.brakeApplied !== undefined) {
      obj.brakeApplied = message.brakeApplied;
    }
    if (message.autopilotState !== undefined) {
      obj.autopilotState = seiMetadata_AutopilotStateToJSON(message.autopilotState);
    }
    if (message.latitudeDeg !== undefined) {
      obj.latitudeDeg = message.latitudeDeg;
    }
    if (message.longitudeDeg !== undefined) {
      obj.longitudeDeg = message.longitudeDeg;
    }
    if (message.headingDeg !== undefined) {
      obj.headingDeg = message.headingDeg;
    }
    if (message.linearAccelerationMps2X !== undefined) {
      obj.linearAccelerationMps2X = message.linearAccelerationMps2X;
    }
    if (message.linearAccelerationMps2Y !== undefined) {
      obj.linearAccelerationMps2Y = message.linearAccelerationMps2Y;
    }
    if (message.linearAccelerationMps2Z !== undefined) {
      obj.linearAccelerationMps2Z = message.linearAccelerationMps2Z;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SeiMetadata>, I>>(base?: I): SeiMetadata {
    return SeiMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SeiMetadata>, I>>(object: I): SeiMetadata {
    const message = createBaseSeiMetadata();
    message.field1 = object.field1 ?? 0;
    message.gearState = object.gearState ?? 0;
    message.frameSeqNo = object.frameSeqNo ?? 0;
    message.vehicleSpeedMps = object.vehicleSpeedMps ?? 0;
    message.acceleratorPedalPosition = object.acceleratorPedalPosition ?? 0;
    message.steeringWheelAngle = object.steeringWheelAngle ?? 0;
    message.blinkerOnLeft = object.blinkerOnLeft ?? false;
    message.blinkerOnRight = object.blinkerOnRight ?? false;
    message.brakeApplied = object.brakeApplied ?? false;
    message.autopilotState = object.autopilotState ?? 0;
    message.latitudeDeg = object.latitudeDeg ?? 0;
    message.longitudeDeg = object.longitudeDeg ?? 0;
    message.headingDeg = object.headingDeg ?? 0;
    message.linearAccelerationMps2X = object.linearAccelerationMps2X ?? 0;
    message.linearAccelerationMps2Y = object.linearAccelerationMps2Y ?? 0;
    message.linearAccelerationMps2Z = object.linearAccelerationMps2Z ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
