"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, '', 'wall_connector.proto')
_sym_db = _symbol_database.Default()
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14wall_connector.proto\x12\x1ctesla.proto.energy_device.v1"\x0c\n\nWCMessages*\xb5\x03\n\x1eWCChargeScheduleChargingStatus\x12.\n*WC_CHARGE_SCHEDULE_CHARGING_STATUS_INVALID\x10\x00\x12<\n8WC_CHARGE_SCHEDULE_CHARGING_STATUS_UNCONFIGURED_DISABLED\x10\x01\x125\n1WC_CHARGE_SCHEDULE_CHARGING_STATUS_CHARGE_BLOCKED\x10\x02\x12=\n9WC_CHARGE_SCHEDULE_CHARGING_STATUS_DELAYED_CHARGE_BLOCKED\x10\x03\x125\n1WC_CHARGE_SCHEDULE_CHARGING_STATUS_CHARGE_ALLOWED\x10\x04\x12=\n9WC_CHARGE_SCHEDULE_CHARGING_STATUS_DELAYED_CHARGE_ALLOWED\x10\x05\x129\n5WC_CHARGE_SCHEDULE_CHARGING_STATUS_VEHICLE_OVERRIDDEN\x10\x06*\xc3\x02\n\x1bWCChargeScheduleConfigError\x12+\n\'WC_CHARGE_SCHEDULE_CONFIG_ERROR_INVALID\x10\x00\x12(\n$WC_CHARGE_SCHEDULE_CONFIG_ERROR_NONE\x10\x01\x120\n,WC_CHARGE_SCHEDULE_CONFIG_ERROR_NO_SITE_WIFI\x10\x02\x12/\n+WC_CHARGE_SCHEDULE_CONFIG_ERROR_NO_INTERNET\x10\x03\x126\n2WC_CHARGE_SCHEDULE_CONFIG_ERROR_INVALID_PARAMETERS\x10\x04\x122\n.WC_CHARGE_SCHEDULE_CONFIG_ERROR_INTERNAL_ERROR\x10\x05*\xb6\x02\n\x13WCChargeScheduleDay\x12"\n\x1eWC_CHARGE_SCHEDULE_DAY_INVALID\x10\x00\x12!\n\x1dWC_CHARGE_SCHEDULE_DAY_SUNDAY\x10\x01\x12!\n\x1dWC_CHARGE_SCHEDULE_DAY_MONDAY\x10\x02\x12"\n\x1eWC_CHARGE_SCHEDULE_DAY_TUESDAY\x10\x04\x12$\n WC_CHARGE_SCHEDULE_DAY_WEDNESDAY\x10\x08\x12#\n\x1fWC_CHARGE_SCHEDULE_DAY_THURSDAY\x10\x10\x12!\n\x1dWC_CHARGE_SCHEDULE_DAY_FRIDAY\x10 \x12#\n\x1fWC_CHARGE_SCHEDULE_DAY_SATURDAY\x10@*\xf1\x01\n\x15WCChargeScheduleError\x12$\n WC_CHARGE_SCHEDULE_ERROR_INVALID\x10\x00\x12!\n\x1dWC_CHARGE_SCHEDULE_ERROR_NONE\x10\x01\x12(\n$WC_CHARGE_SCHEDULE_ERROR_NO_INTERNET\x10\x02\x12>\n:WC_CHARGE_SCHEDULE_ERROR_NON_VOLATILE_DATA_READ_WRITE_FAIL\x10\x03\x12%\n!WC_CHARGE_SCHEDULE_ERROR_INTERNAL\x10\x04*\x9e\x02\n!WCConfigureAccessControlOperation\x121\n-WC_CONFIGURE_ACCESS_CONTROL_OPERATION_INVALID\x10\x00\x12-\n)WC_CONFIGURE_ACCESS_CONTROL_OPERATION_ADD\x10\x01\x120\n,WC_CONFIGURE_ACCESS_CONTROL_OPERATION_REMOVE\x10\x02\x123\n/WC_CONFIGURE_ACCESS_CONTROL_OPERATION_CLEAR_ALL\x10\x03\x120\n,WC_CONFIGURE_ACCESS_CONTROL_OPERATION_RENAME\x10\x04*\x99\x03\n\x12WCFaultStatusState\x12!\n\x1dWC_FAULT_STATUS_STATE_INVALID\x10\x00\x12!\n\x1dWC_FAULT_STATUS_STATE_STARTUP\x10\x01\x12\x1f\n\x1bWC_FAULT_STATUS_STATE_READY\x10\x02\x12(\n$WC_FAULT_STATUS_STATE_CRITICAL_FAULT\x10\x03\x12,\n(WC_FAULT_STATUS_STATE_NON_CRITICAL_FAULT\x10\x04\x12\'\n#WC_FAULT_STATUS_STATE_RETRY_PENDING\x10\x05\x12!\n\x1dWC_FAULT_STATUS_STATE_LOCKOUT\x10\x06\x12"\n\x1eWC_FAULT_STATUS_STATE_FOLDBACK\x10\x07\x12"\n\x1eWC_FAULT_STATUS_STATE_CHARGING\x10\x08\x120\n,WC_FAULT_STATUS_STATE_CONFIGURATION_REQUIRED\x10\t*\xac\x01\n\x13WCGroundMonitorMode\x12"\n\x1eWC_GROUND_MONITOR_MODE_INVALID\x10\x00\x12#\n\x1fWC_GROUND_MONITOR_MODE_DISABLED\x10\x01\x12(\n$WC_GROUND_MONITOR_MODE_INFORMATIONAL\x10\x02\x12"\n\x1eWC_GROUND_MONITOR_MODE_ENABLED\x10\x03*\xa5\x02\n%WCLoadSharingNetworkChargingInhibitor\x126\n2WC_LOAD_SHARING_NETWORK_CHARGING_INHIBITOR_INVALID\x10\x00\x12C\n?WC_LOAD_SHARING_NETWORK_CHARGING_INHIBITOR_INSUFFICIENT_CURRENT\x10\x01\x12C\n?WC_LOAD_SHARING_NETWORK_CHARGING_INHIBITOR_INSUFFICIENT_DEVICES\x10\x02\x12:\n6WC_LOAD_SHARING_NETWORK_CHARGING_INHIBITOR_DEVICES_MIA\x10\x03*\x9a\x01\n\x19WCPpuSessionReportingMode\x12)\n%WC_PPU_SESSION_REPORTING_MODE_INVALID\x10\x00\x12&\n"WC_PPU_SESSION_REPORTING_MODE_NONE\x10\x01\x12*\n&WC_PPU_SESSION_REPORTING_MODE_ALL_INFO\x10\x02*\xa0\x02\n\x17WCTeslaVehicleDriveType\x12\'\n#WC_TESLA_VEHICLE_DRIVE_TYPE_INVALID\x10\x00\x125\n1WC_TESLA_VEHICLE_DRIVE_TYPE_SINGLE_MOTOR_STANDARD\x10\x01\x128\n4WC_TESLA_VEHICLE_DRIVE_TYPE_SINGLE_MOTOR_PERFORMANCE\x10\x02\x123\n/WC_TESLA_VEHICLE_DRIVE_TYPE_DUAL_MOTOR_STANDARD\x10\x03\x126\n2WC_TESLA_VEHICLE_DRIVE_TYPE_DUAL_MOTOR_PERFORMANCE\x10\x04*\xb1\x01\n\x13WCTeslaVehicleModel\x12"\n\x1eWC_TESLA_VEHICLE_MODEL_INVALID\x10\x00\x12\x1c\n\x18WC_TESLA_VEHICLE_MODEL_S\x10\x01\x12\x1c\n\x18WC_TESLA_VEHICLE_MODEL_X\x10\x02\x12\x1c\n\x18WC_TESLA_VEHICLE_MODEL_3\x10\x03\x12\x1c\n\x18WC_TESLA_VEHICLE_MODEL_Y\x10\x04*\xfb\x01\n\x17WCThirdPartyVehicleMode\x12\'\n#WC_THIRD_PARTY_VEHICLE_MODE_INVALID\x10\x00\x12\'\n#WC_THIRD_PARTY_VEHICLE_MODE_ENABLED\x10\x01\x12(\n$WC_THIRD_PARTY_VEHICLE_MODE_DISABLED\x10\x02\x124\n0WC_THIRD_PARTY_VEHICLE_MODE_DISABLED_NO_ROADSTER\x10\x03\x12.\n*WC_THIRD_PARTY_VEHICLE_MODE_VIN_ALLOW_LIST\x10\x04*\x91\x05\n\x14WCEvseNotReadyReason\x12$\n WC_EVSE_NOT_READY_REASON_INVALID\x10\x00\x12-\n)WC_EVSE_NOT_READY_REASON_COLD_LOAD_PICKUP\x10\x01\x12*\n&WC_EVSE_NOT_READY_REASON_HANDLE_BUTTON\x10\x02\x12)\n%WC_EVSE_NOT_READY_REASON_SESSION_AUTH\x10\x03\x12,\n(WC_EVSE_NOT_READY_REASON_FAULT_NO_CHARGE\x10\x04\x12*\n&WC_EVSE_NOT_READY_REASON_FAULT_STARTUP\x10\x05\x12*\n&WC_EVSE_NOT_READY_REASON_GMI_NO_CHARGE\x10\x06\x12+\n\'WC_EVSE_NOT_READY_REASON_PILOT_NOT_CONN\x10\x07\x12,\n(WC_EVSE_NOT_READY_REASON_CONFIG_NOT_RECV\x10\x08\x121\n-WC_EVSE_NOT_READY_REASON_LOAD_SHARE_NO_CHARGE\x10\t\x12+\n\'WC_EVSE_NOT_READY_REASON_OCPP_NO_CHARGE\x10\n\x120\n,WC_EVSE_NOT_READY_REASON_ACCESS_CONTROL_LIST\x10\x0b\x12(\n$WC_EVSE_NOT_READY_REASON_PAY_PER_USE\x10\x0c\x120\n,WC_EVSE_NOT_READY_REASON_THIRD_PARTY_VEHICLE\x10\r*\xb5\x02\n\x0cWCOcppStatus\x12\x1a\n\x16WC_OCPP_STATUS_INVALID\x10\x00\x12\x1f\n\x1bWC_OCPP_STATUS_UNCONFIGURED\x10\x01\x12+\n\'WC_OCPP_STATUS_INCOMPLETE_CONFIGURATION\x10\x02\x12&\n"WC_OCPP_STATUS_CONFIGURED_DISABLED\x10\x03\x12%\n!WC_OCPP_STATUS_CONFIGURED_ENABLED\x10\x04\x12/\n+WC_OCPP_STATUS_CONFIGURED_ENABLED_CONNECTED\x10\x05\x12;\n7WC_OCPP_STATUS_CONFIGURED_ENABLED_INVALID_CONFIGURATION\x10\x06B\x81\x01\n$com.tesla.generated.energy_device.v1B\rWallConnectorZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wall_connector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n$com.tesla.generated.energy_device.v1B\rWallConnectorZJgithub.com/teslamotors/energy_device/pkg/protocol/protobuf/energydevice/v1'
    _globals['_WCCHARGESCHEDULECHARGINGSTATUS']._serialized_start = 69
    _globals['_WCCHARGESCHEDULECHARGINGSTATUS']._serialized_end = 506
    _globals['_WCCHARGESCHEDULECONFIGERROR']._serialized_start = 509
    _globals['_WCCHARGESCHEDULECONFIGERROR']._serialized_end = 832
    _globals['_WCCHARGESCHEDULEDAY']._serialized_start = 835
    _globals['_WCCHARGESCHEDULEDAY']._serialized_end = 1145
    _globals['_WCCHARGESCHEDULEERROR']._serialized_start = 1148
    _globals['_WCCHARGESCHEDULEERROR']._serialized_end = 1389
    _globals['_WCCONFIGUREACCESSCONTROLOPERATION']._serialized_start = 1392
    _globals['_WCCONFIGUREACCESSCONTROLOPERATION']._serialized_end = 1678
    _globals['_WCFAULTSTATUSSTATE']._serialized_start = 1681
    _globals['_WCFAULTSTATUSSTATE']._serialized_end = 2090
    _globals['_WCGROUNDMONITORMODE']._serialized_start = 2093
    _globals['_WCGROUNDMONITORMODE']._serialized_end = 2265
    _globals['_WCLOADSHARINGNETWORKCHARGINGINHIBITOR']._serialized_start = 2268
    _globals['_WCLOADSHARINGNETWORKCHARGINGINHIBITOR']._serialized_end = 2561
    _globals['_WCPPUSESSIONREPORTINGMODE']._serialized_start = 2564
    _globals['_WCPPUSESSIONREPORTINGMODE']._serialized_end = 2718
    _globals['_WCTESLAVEHICLEDRIVETYPE']._serialized_start = 2721
    _globals['_WCTESLAVEHICLEDRIVETYPE']._serialized_end = 3009
    _globals['_WCTESLAVEHICLEMODEL']._serialized_start = 3012
    _globals['_WCTESLAVEHICLEMODEL']._serialized_end = 3189
    _globals['_WCTHIRDPARTYVEHICLEMODE']._serialized_start = 3192
    _globals['_WCTHIRDPARTYVEHICLEMODE']._serialized_end = 3443
    _globals['_WCEVSENOTREADYREASON']._serialized_start = 3446
    _globals['_WCEVSENOTREADYREASON']._serialized_end = 4103
    _globals['_WCOCPPSTATUS']._serialized_start = 4106
    _globals['_WCOCPPSTATUS']._serialized_end = 4415
    _globals['_WCMESSAGES']._serialized_start = 54
    _globals['_WCMESSAGES']._serialized_end = 66